/* This file was generated by lv6 version 6.101.17. */
/*  lv6 -2c -cc -node main max.lus */
/* on s27 the 25/03/2020 at 17:27:58 */

#ifndef _SOC2C_PREDEF_TYPES
#define _SOC2C_PREDEF_TYPES
typedef int _boolean;
typedef int _integer;
typedef char* _string;
typedef double _real;
typedef double _double;
typedef float _float;
#define _false 0
#define _true 1
#endif
// end of _SOC2C_PREDEF_TYPES
// User typedef 
#ifndef _max_main_TYPES
#define _max_main_TYPES
#endif // enf of  _max_main_TYPES
// Memoryless soc ctx typedef 
// Memoryfull soc ctx typedef 
