/* This file was generated by lv6 version 6.101.17. */
/*  lv6 -2c -cc -n Main robustSpec_v3.lus */
/* on s27 the 26/03/2020 at 12:25:05 */
#include "lustre_types.h"
// Constant definitions 
#define robustSpec_v3_TRUE_r 9999.0
