/* This file was generated by lv6 version 6.101.17. */
/*  lv6 -2c -cc -node main max.lus */
/* on s27 the 25/03/2020 at 17:27:58 */

#include <stdlib.h>
#include <string.h>

#include "lustre_consts.h"

#ifndef _max_main_H_FILE
#define _max_main_H_FILE
void max_main_step(_real ,_real ,_real *);

/////////////////////////////////////////////////
#endif
