/* This file was generated by lv6 version 6.101.17. */
/*  lv6 -2c -cc -node main max.lus */
/* on s27 the 25/03/2020 at 17:27:58 */
#include "max_main.h"
//// Defining step functions
// Step function(s) for max_main_ctx
void max_main_step(_real x,_real y,_real *z){
   _boolean _split_1;

  _split_1 = x > y;
   if (_split_1 == _true) {
     *z = x;
   } else {
     *z = y;
   }

} // End of max_main_step

