/* This file was generated by lv6 version 6.101.17. */
/*  lv6 -2c -cc -n Main robustSpec_v3.lus */
/* on s27 the 26/03/2020 at 12:25:05 */

#include <stdlib.h>
#include <string.h>

#include "lustre_consts.h"

#ifndef _robustSpec_v3_Main_H_FILE
#define _robustSpec_v3_Main_H_FILE
void Delay_0_step(_real ,_real *);

void Delay_1_ctx_reset(Delay_1_ctx_type* ctx);
Delay_1_ctx_type* Delay_1_ctx_new_ctx();
void Delay_1_step(_real ,_real *,Delay_1_ctx_type*);

void Delay_2_ctx_reset(Delay_2_ctx_type* ctx);
Delay_2_ctx_type* Delay_2_ctx_new_ctx();
void Delay_2_step(_real ,_real *,Delay_2_ctx_type*);

void Delay_m1_step(_real ,_real *);

void Lustre_arrow_ctx_reset(Lustre_arrow_ctx_type* ctx);
Lustre_arrow_ctx_type* Lustre_arrow_ctx_new_ctx();
void Lustre_arrow_step(_real ,_real ,_real *,Lustre_arrow_ctx_type*);

void Lustre_pre_ctx_reset(Lustre_pre_ctx_type* ctx);
Lustre_pre_ctx_type* Lustre_pre_ctx_new_ctx();
void Lustre_pre_get(_real *,Lustre_pre_ctx_type*);

void Lustre_pre_set(_real ,Lustre_pre_ctx_type*);

void Once_Interval_0_2_ctx_reset(Once_Interval_0_2_ctx_type* ctx);
Once_Interval_0_2_ctx_type* Once_Interval_0_2_ctx_new_ctx();
void Once_Interval_0_2_step(_real ,_real *,Once_Interval_0_2_ctx_type*);

void Since_Interval_0_2_ctx_reset(Since_Interval_0_2_ctx_type* ctx);
Since_Interval_0_2_ctx_type* Since_Interval_0_2_ctx_new_ctx();
void Since_Interval_0_2_step(_real ,_real ,_real *,Since_Interval_0_2_ctx_type*);

void Since_Recurse_0_2_0_ctx_reset(Since_Recurse_0_2_0_ctx_type* ctx);
Since_Recurse_0_2_0_ctx_type* Since_Recurse_0_2_0_ctx_new_ctx();
void Since_Recurse_0_2_0_step(_real ,_real ,_real *,Since_Recurse_0_2_0_ctx_type*);

void Since_Recurse_0_2_1_ctx_reset(Since_Recurse_0_2_1_ctx_type* ctx);
Since_Recurse_0_2_1_ctx_type* Since_Recurse_0_2_1_ctx_new_ctx();
void Since_Recurse_0_2_1_step(_real ,_real ,_real *,Since_Recurse_0_2_1_ctx_type*);

void Since_Recurse_0_2_2_ctx_reset(Since_Recurse_0_2_2_ctx_type* ctx);
Since_Recurse_0_2_2_ctx_type* Since_Recurse_0_2_2_ctx_new_ctx();
void Since_Recurse_0_2_2_step(_real ,_real ,_real *,Since_Recurse_0_2_2_ctx_type*);

void Sliding_Min_m1_step(_real ,_real *);

void robustSpec_v3_Main_ctx_reset(robustSpec_v3_Main_ctx_type* ctx);
robustSpec_v3_Main_ctx_type* robustSpec_v3_Main_ctx_new_ctx();
void robustSpec_v3_Main_step(_real ,_real ,_real *,robustSpec_v3_Main_ctx_type*);

void robustSpec_v3_Max_2_step(_real ,_real ,_real *);

void robustSpec_v3_Min_2_step(_real ,_real ,_real *);

/////////////////////////////////////////////////
#endif
