/* This file was generated by lv6 version 6.101.17. */
/*  lv6 -n Main -2c -cc robustSpec_v2.lus */
/* on s27 the 24/03/2020 at 22:25:57 */

#include <stdlib.h>
#include <string.h>

#include "lustre_consts.h"

#ifndef _robustSpec_v2_Main_H_FILE
#define _robustSpec_v2_Main_H_FILE
void Lustre_arrow_ctx_reset(Lustre_arrow_ctx_type* ctx);
Lustre_arrow_ctx_type* Lustre_arrow_ctx_new_ctx();
void Lustre_arrow_step(_real ,_real ,_real *,Lustre_arrow_ctx_type*);

void Lustre_pre_ctx_reset(Lustre_pre_ctx_type* ctx);
Lustre_pre_ctx_type* Lustre_pre_ctx_new_ctx();
void Lustre_pre_get(_real *,Lustre_pre_ctx_type*);

void Lustre_pre_set(_real ,Lustre_pre_ctx_type*);

void robustSpec_v2_Main_ctx_reset(robustSpec_v2_Main_ctx_type* ctx);
robustSpec_v2_Main_ctx_type* robustSpec_v2_Main_ctx_new_ctx();
void robustSpec_v2_Main_step(_real ,_real *,robustSpec_v2_Main_ctx_type*);

void robustSpec_v2_Max_ctx_reset(robustSpec_v2_Max_ctx_type* ctx);
robustSpec_v2_Max_ctx_type* robustSpec_v2_Max_ctx_new_ctx();
void robustSpec_v2_Max_step(_real ,_real *,robustSpec_v2_Max_ctx_type*);

void robustSpec_v2_Once_Inf_ctx_reset(robustSpec_v2_Once_Inf_ctx_type* ctx);
robustSpec_v2_Once_Inf_ctx_type* robustSpec_v2_Once_Inf_ctx_new_ctx();
void robustSpec_v2_Once_Inf_step(_real ,_real *,robustSpec_v2_Once_Inf_ctx_type*);

/////////////////////////////////////////////////
#endif
