/* This file was generated by lv6 version 6.101.17. */
/*  lv6 -2c -cc -n Main robustSpec_v3.lus */
/* on s27 the 26/03/2020 at 12:25:05 */
#include "robustSpec_v3_Main.h"
//// Defining step functions
// Step function(s) for Delay_0_ctx
void Delay_0_step(_real x,_real *z){

  *z = x;

} // End of Delay_0_step

// Memory initialisation for Delay_1_ctx
void Delay_1_ctx_reset(Delay_1_ctx_type* ctx){
  int _i;

    Lustre_pre_ctx_reset(&ctx->Lustre_pre_ctx_tab[0]);
    Lustre_arrow_ctx_reset(&ctx->Lustre_arrow_ctx_tab[0]);
}
// Memory allocation for Delay_1_ctx
Delay_1_ctx_type* Delay_1_ctx_new_ctx(){

   Delay_1_ctx_type* ctx = (Delay_1_ctx_type*)calloc(1, sizeof(Delay_1_ctx_type));
   // ctx->client_data = cdata;
   Delay_1_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Delay_1_ctx
void Delay_1_step(_real x,_real *z,Delay_1_ctx_type* ctx){   _real _split_2;
   _real _split_1;

  Lustre_pre_get(&_split_2,&ctx->Lustre_pre_ctx_tab[0]); 
  Delay_0_step(x,&_split_1); 
  Lustre_pre_set(_split_1,&ctx->Lustre_pre_ctx_tab[0]); 
  Lustre_arrow_step(x,_split_2,z,&ctx->Lustre_arrow_ctx_tab[0]); 

} // End of Delay_1_step

// Memory initialisation for Delay_2_ctx
void Delay_2_ctx_reset(Delay_2_ctx_type* ctx){
  int _i;

    Lustre_pre_ctx_reset(&ctx->Lustre_pre_ctx_tab[0]);
    Lustre_arrow_ctx_reset(&ctx->Lustre_arrow_ctx_tab[0]);
    Delay_1_ctx_reset(&ctx->Delay_1_ctx_tab[0]);
}
// Memory allocation for Delay_2_ctx
Delay_2_ctx_type* Delay_2_ctx_new_ctx(){

   Delay_2_ctx_type* ctx = (Delay_2_ctx_type*)calloc(1, sizeof(Delay_2_ctx_type));
   // ctx->client_data = cdata;
   Delay_2_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Delay_2_ctx
void Delay_2_step(_real x,_real *z,Delay_2_ctx_type* ctx){   _real _split_4;
   _real _split_3;

  Lustre_pre_get(&_split_4,&ctx->Lustre_pre_ctx_tab[0]); 
  Delay_1_step(x,&_split_3,&ctx->Delay_1_ctx_tab[0]); 
  Lustre_pre_set(_split_3,&ctx->Lustre_pre_ctx_tab[0]); 
  Lustre_arrow_step(x,_split_4,z,&ctx->Lustre_arrow_ctx_tab[0]); 

} // End of Delay_2_step

// Step function(s) for Delay_m1_ctx
void Delay_m1_step(_real x,_real *z){

  *z = x;

} // End of Delay_m1_step

// Memory initialisation for Lustre_arrow_ctx
void Lustre_arrow_ctx_reset(Lustre_arrow_ctx_type* ctx){  ctx->_memory = _true;
}
// Memory allocation for Lustre_arrow_ctx
Lustre_arrow_ctx_type* Lustre_arrow_ctx_new_ctx(){

   Lustre_arrow_ctx_type* ctx = (Lustre_arrow_ctx_type*)calloc(1, sizeof(Lustre_arrow_ctx_type));
   // ctx->client_data = cdata;
   Lustre_arrow_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Lustre_arrow_ctx
void Lustre_arrow_step(_real i1,_real i2,_real *out,Lustre_arrow_ctx_type* ctx){  *out = ((ctx->_memory)? i1 : i2);
  ctx->_memory = _false;

} // End of Lustre_arrow_step

// Memory initialisation for Lustre_pre_ctx
void Lustre_pre_ctx_reset(Lustre_pre_ctx_type* ctx){
}
// Memory allocation for Lustre_pre_ctx
Lustre_pre_ctx_type* Lustre_pre_ctx_new_ctx(){

   Lustre_pre_ctx_type* ctx = (Lustre_pre_ctx_type*)calloc(1, sizeof(Lustre_pre_ctx_type));
   // ctx->client_data = cdata;
   Lustre_pre_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Lustre_pre_ctx
void Lustre_pre_get(_real *out,Lustre_pre_ctx_type* ctx){
  *out = ctx->_memory;

} // End of Lustre_pre_get

void Lustre_pre_set(_real i1,Lustre_pre_ctx_type* ctx){
  ctx->_memory = i1;

} // End of Lustre_pre_set

// Memory initialisation for Once_Interval_0_2_ctx
void Once_Interval_0_2_ctx_reset(Once_Interval_0_2_ctx_type* ctx){
  int _i;

    Since_Interval_0_2_ctx_reset(&ctx->Since_Interval_0_2_ctx_tab[0]);
}
// Memory allocation for Once_Interval_0_2_ctx
Once_Interval_0_2_ctx_type* Once_Interval_0_2_ctx_new_ctx(){

   Once_Interval_0_2_ctx_type* ctx = (Once_Interval_0_2_ctx_type*)calloc(1, sizeof(Once_Interval_0_2_ctx_type));
   // ctx->client_data = cdata;
   Once_Interval_0_2_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Once_Interval_0_2_ctx
void Once_Interval_0_2_step(_real x,_real *z,Once_Interval_0_2_ctx_type* ctx){
  Since_Interval_0_2_step(x,9999.0,z,&ctx->Since_Interval_0_2_ctx_tab[0]); 

} // End of Once_Interval_0_2_step

// Memory initialisation for Since_Interval_0_2_ctx
void Since_Interval_0_2_ctx_reset(Since_Interval_0_2_ctx_type* ctx){
  int _i;

    Since_Recurse_0_2_0_ctx_reset(&ctx->Since_Recurse_0_2_0_ctx_tab[0]);
}
// Memory allocation for Since_Interval_0_2_ctx
Since_Interval_0_2_ctx_type* Since_Interval_0_2_ctx_new_ctx(){

   Since_Interval_0_2_ctx_type* ctx = (Since_Interval_0_2_ctx_type*)calloc(1, sizeof(Since_Interval_0_2_ctx_type));
   // ctx->client_data = cdata;
   Since_Interval_0_2_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Since_Interval_0_2_ctx
void Since_Interval_0_2_step(_real x,_real y,_real *z,Since_Interval_0_2_ctx_type* ctx){   _boolean _split_7;
   _boolean _split_8;

  _split_8 = 2 > 0;
  _split_7 = 0 >= 0;
  Since_Recurse_0_2_0_step(x,y,z,&ctx->Since_Recurse_0_2_0_ctx_tab[0]); 

} // End of Since_Interval_0_2_step

// Memory initialisation for Since_Recurse_0_2_0_ctx
void Since_Recurse_0_2_0_ctx_reset(Since_Recurse_0_2_0_ctx_type* ctx){
  int _i;

    Since_Recurse_0_2_1_ctx_reset(&ctx->Since_Recurse_0_2_1_ctx_tab[0]);
}
// Memory allocation for Since_Recurse_0_2_0_ctx
Since_Recurse_0_2_0_ctx_type* Since_Recurse_0_2_0_ctx_new_ctx(){

   Since_Recurse_0_2_0_ctx_type* ctx = (Since_Recurse_0_2_0_ctx_type*)calloc(1, sizeof(Since_Recurse_0_2_0_ctx_type));
   // ctx->client_data = cdata;
   Since_Recurse_0_2_0_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Since_Recurse_0_2_0_ctx
void Since_Recurse_0_2_0_step(_real x,_real y,_real *z,Since_Recurse_0_2_0_ctx_type* ctx){   _real _split_9;
   _real x_delay;
   _real x_n;
   _real min_m;
   _real min_n;
   _integer _split_10;
   _boolean _split_11;

  _split_10 = 2 - 0;
  _split_11 = _split_10 >= 0;
  Delay_0_step(x,&x_delay); 
  Delay_0_step(x_delay,&x_n); 
  Sliding_Min_m1_step(y,&min_m); 
  robustSpec_v3_Min_2_step(x_n,min_m,&min_n); 
  Since_Recurse_0_2_1_step(x,y,&_split_9,&ctx->Since_Recurse_0_2_1_ctx_tab[0]); 
  robustSpec_v3_Max_2_step(min_n,_split_9,z); 

} // End of Since_Recurse_0_2_0_step

// Memory initialisation for Since_Recurse_0_2_1_ctx
void Since_Recurse_0_2_1_ctx_reset(Since_Recurse_0_2_1_ctx_type* ctx){
  int _i;

    Since_Recurse_0_2_2_ctx_reset(&ctx->Since_Recurse_0_2_2_ctx_tab[0]);
    Delay_1_ctx_reset(&ctx->Delay_1_ctx_tab[0]);
}
// Memory allocation for Since_Recurse_0_2_1_ctx
Since_Recurse_0_2_1_ctx_type* Since_Recurse_0_2_1_ctx_new_ctx(){

   Since_Recurse_0_2_1_ctx_type* ctx = (Since_Recurse_0_2_1_ctx_type*)calloc(1, sizeof(Since_Recurse_0_2_1_ctx_type));
   // ctx->client_data = cdata;
   Since_Recurse_0_2_1_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Since_Recurse_0_2_1_ctx
void Since_Recurse_0_2_1_step(_real x,_real y,_real *z,Since_Recurse_0_2_1_ctx_type* ctx){   _real _split_12;
   _real x_delay;
   _real x_n;
   _real min_m;
   _real min_n;
   _integer _split_13;
   _boolean _split_14;

  _split_13 = 2 - 0;
  _split_14 = _split_13 >= 0;
  Delay_0_step(x,&x_delay); 
  Delay_1_step(x_delay,&x_n,&ctx->Delay_1_ctx_tab[0]); 
  Sliding_Min_m1_step(y,&min_m); 
  robustSpec_v3_Min_2_step(x_n,min_m,&min_n); 
  Since_Recurse_0_2_2_step(x,y,&_split_12,&ctx->Since_Recurse_0_2_2_ctx_tab[0]); 
  robustSpec_v3_Max_2_step(min_n,_split_12,z); 

} // End of Since_Recurse_0_2_1_step

// Memory initialisation for Since_Recurse_0_2_2_ctx
void Since_Recurse_0_2_2_ctx_reset(Since_Recurse_0_2_2_ctx_type* ctx){
  int _i;

    Delay_2_ctx_reset(&ctx->Delay_2_ctx_tab[0]);
}
// Memory allocation for Since_Recurse_0_2_2_ctx
Since_Recurse_0_2_2_ctx_type* Since_Recurse_0_2_2_ctx_new_ctx(){

   Since_Recurse_0_2_2_ctx_type* ctx = (Since_Recurse_0_2_2_ctx_type*)calloc(1, sizeof(Since_Recurse_0_2_2_ctx_type));
   // ctx->client_data = cdata;
   Since_Recurse_0_2_2_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Since_Recurse_0_2_2_ctx
void Since_Recurse_0_2_2_step(_real x,_real y,_real *z,Since_Recurse_0_2_2_ctx_type* ctx){   _real x_delay;
   _real x_n;
   _real min_m;
   _real min_n;
   _integer _split_15;
   _boolean _split_16;

  _split_15 = 2 - 0;
  _split_16 = _split_15 >= 0;
  Delay_0_step(x,&x_delay); 
  Delay_2_step(x_delay,&x_n,&ctx->Delay_2_ctx_tab[0]); 
  Sliding_Min_m1_step(y,&min_m); 
  robustSpec_v3_Min_2_step(x_n,min_m,&min_n); 
  *z = min_n;

} // End of Since_Recurse_0_2_2_step

// Step function(s) for Sliding_Min_m1_ctx
void Sliding_Min_m1_step(_real x,_real *z){
   _real x_n;

  Delay_m1_step(x,&x_n); 
  *z = x;

} // End of Sliding_Min_m1_step

// Memory initialisation for robustSpec_v3_Main_ctx
void robustSpec_v3_Main_ctx_reset(robustSpec_v3_Main_ctx_type* ctx){
  int _i;

    Once_Interval_0_2_ctx_reset(&ctx->Once_Interval_0_2_ctx_tab[0]);
}
// Memory allocation for robustSpec_v3_Main_ctx
robustSpec_v3_Main_ctx_type* robustSpec_v3_Main_ctx_new_ctx(){

   robustSpec_v3_Main_ctx_type* ctx = (robustSpec_v3_Main_ctx_type*)calloc(1, sizeof(robustSpec_v3_Main_ctx_type));
   // ctx->client_data = cdata;
   robustSpec_v3_Main_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for robustSpec_v3_Main_ctx
void robustSpec_v3_Main_step(_real x,_real y,_real *z,robustSpec_v3_Main_ctx_type* ctx){
  Once_Interval_0_2_step(x,z,&ctx->Once_Interval_0_2_ctx_tab[0]); 

} // End of robustSpec_v3_Main_step

// Step function(s) for robustSpec_v3_Max_2_ctx
void robustSpec_v3_Max_2_step(_real x,_real y,_real *max){
   _boolean _split_5;

  _split_5 = x > y;
   if (_split_5 == _true) {
     *max = x;
   } else {
     *max = y;
   }

} // End of robustSpec_v3_Max_2_step

// Step function(s) for robustSpec_v3_Min_2_ctx
void robustSpec_v3_Min_2_step(_real x,_real y,_real *min){
   _boolean _split_6;

  _split_6 = x > y;
   if (_split_6 == _true) {
     *min = y;
   } else {
     *min = x;
   }

} // End of robustSpec_v3_Min_2_step

