/* This file was generated by lv6 version 6.101.17. */
/*  lv6 -n Main -2c -cc robustSpec_v2.lus */
/* on s27 the 24/03/2020 at 22:25:57 */
#include "robustSpec_v2_Main.h"
//// Defining step functions
// Memory initialisation for Lustre_arrow_ctx
void Lustre_arrow_ctx_reset(Lustre_arrow_ctx_type* ctx){  ctx->_memory = _true;
}
// Memory allocation for Lustre_arrow_ctx
Lustre_arrow_ctx_type* Lustre_arrow_ctx_new_ctx(){

   Lustre_arrow_ctx_type* ctx = (Lustre_arrow_ctx_type*)calloc(1, sizeof(Lustre_arrow_ctx_type));
   // ctx->client_data = cdata;
   Lustre_arrow_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Lustre_arrow_ctx
void Lustre_arrow_step(_real i1,_real i2,_real *out,Lustre_arrow_ctx_type* ctx){  *out = ((ctx->_memory)? i1 : i2);
  ctx->_memory = _false;

} // End of Lustre_arrow_step

// Memory initialisation for Lustre_pre_ctx
void Lustre_pre_ctx_reset(Lustre_pre_ctx_type* ctx){
}
// Memory allocation for Lustre_pre_ctx
Lustre_pre_ctx_type* Lustre_pre_ctx_new_ctx(){

   Lustre_pre_ctx_type* ctx = (Lustre_pre_ctx_type*)calloc(1, sizeof(Lustre_pre_ctx_type));
   // ctx->client_data = cdata;
   Lustre_pre_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Lustre_pre_ctx
void Lustre_pre_get(_real *out,Lustre_pre_ctx_type* ctx){
  *out = ctx->_memory;

} // End of Lustre_pre_get

void Lustre_pre_set(_real i1,Lustre_pre_ctx_type* ctx){
  ctx->_memory = i1;

} // End of Lustre_pre_set

// Memory initialisation for robustSpec_v2_Main_ctx
void robustSpec_v2_Main_ctx_reset(robustSpec_v2_Main_ctx_type* ctx){
  int _i;

    robustSpec_v2_Once_Inf_ctx_reset(&ctx->robustSpec_v2_Once_Inf_ctx_tab[0]);
}
// Memory allocation for robustSpec_v2_Main_ctx
robustSpec_v2_Main_ctx_type* robustSpec_v2_Main_ctx_new_ctx(){

   robustSpec_v2_Main_ctx_type* ctx = (robustSpec_v2_Main_ctx_type*)calloc(1, sizeof(robustSpec_v2_Main_ctx_type));
   // ctx->client_data = cdata;
   robustSpec_v2_Main_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for robustSpec_v2_Main_ctx
void robustSpec_v2_Main_step(_real x,_real *z,robustSpec_v2_Main_ctx_type* ctx){
  robustSpec_v2_Once_Inf_step(x,z,&ctx->robustSpec_v2_Once_Inf_ctx_tab[0]); 

} // End of robustSpec_v2_Main_step

// Memory initialisation for robustSpec_v2_Max_ctx
void robustSpec_v2_Max_ctx_reset(robustSpec_v2_Max_ctx_type* ctx){
  int _i;

    Lustre_pre_ctx_reset(&ctx->Lustre_pre_ctx_tab[0]);
    Lustre_pre_ctx_reset(&ctx->Lustre_pre_ctx_tab[1]);
    Lustre_arrow_ctx_reset(&ctx->Lustre_arrow_ctx_tab[0]);
}
// Memory allocation for robustSpec_v2_Max_ctx
robustSpec_v2_Max_ctx_type* robustSpec_v2_Max_ctx_new_ctx(){

   robustSpec_v2_Max_ctx_type* ctx = (robustSpec_v2_Max_ctx_type*)calloc(1, sizeof(robustSpec_v2_Max_ctx_type));
   // ctx->client_data = cdata;
   robustSpec_v2_Max_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for robustSpec_v2_Max_ctx
void robustSpec_v2_Max_step(_real x,_real *max,robustSpec_v2_Max_ctx_type* ctx){   _real _split_4;
   _real _split_3;
   _boolean _split_2;
   _real _split_1;

  Lustre_pre_get(&_split_3,&ctx->Lustre_pre_ctx_tab[0]); 
  Lustre_pre_get(&_split_1,&ctx->Lustre_pre_ctx_tab[1]); 
  _split_2 = x > _split_1;
   if (_split_2 == _true) {
     _split_4 = x;
   } else {
     _split_4 = _split_3;
   }
  Lustre_arrow_step(x,_split_4,max,&ctx->Lustre_arrow_ctx_tab[0]); 
  Lustre_pre_set(*max,&ctx->Lustre_pre_ctx_tab[0]); 
  Lustre_pre_set(*max,&ctx->Lustre_pre_ctx_tab[1]); 

} // End of robustSpec_v2_Max_step

// Memory initialisation for robustSpec_v2_Once_Inf_ctx
void robustSpec_v2_Once_Inf_ctx_reset(robustSpec_v2_Once_Inf_ctx_type* ctx){
  int _i;

    robustSpec_v2_Max_ctx_reset(&ctx->robustSpec_v2_Max_ctx_tab[0]);
}
// Memory allocation for robustSpec_v2_Once_Inf_ctx
robustSpec_v2_Once_Inf_ctx_type* robustSpec_v2_Once_Inf_ctx_new_ctx(){

   robustSpec_v2_Once_Inf_ctx_type* ctx = (robustSpec_v2_Once_Inf_ctx_type*)calloc(1, sizeof(robustSpec_v2_Once_Inf_ctx_type));
   // ctx->client_data = cdata;
   robustSpec_v2_Once_Inf_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for robustSpec_v2_Once_Inf_ctx
void robustSpec_v2_Once_Inf_step(_real x,_real *z,robustSpec_v2_Once_Inf_ctx_type* ctx){
  robustSpec_v2_Max_step(x,z,&ctx->robustSpec_v2_Max_ctx_tab[0]); 

} // End of robustSpec_v2_Once_Inf_step

