/* This file was generated by lv6 version master.737 (2727a7744111c84f7984634d2bd3ad6f7c6c7ff9). */
/*  lv6 -2c -cc -n Main robustSpec_v6.lus */
/* on s27 the 03/04/2020 at 08:27:05 */

#ifndef _SOC2C_PREDEF_TYPES
#define _SOC2C_PREDEF_TYPES
typedef int _boolean;
typedef int _integer;
typedef char* _string;
typedef double _real;
typedef double _double;
typedef float _float;
#define _false 0
#define _true 1
#endif
// end of _SOC2C_PREDEF_TYPES
// User typedef 
#ifndef _robustSpec_v6_Main_TYPES
#define _robustSpec_v6_Main_TYPES
typedef _real robustSpec_v6_PerformancePoint[3];
typedef _real robustSpec_v6_PerformancePoint_AP[2];
typedef struct { 
   _real t;
   _real s[3];
  } robustSpec_v6_SamplePoint;
#endif // enf of  _robustSpec_v6_Main_TYPES
// Memoryless soc ctx typedef 
// Memoryfull soc ctx typedef 
/* Lustre_pre_ctx */
typedef struct {
   /*Memory cell*/
   _real _memory ;
} Lustre_pre_ctx_type;

/* Lustre_arrow_ctx */
typedef struct {
   /*Memory cell*/
   _boolean _memory ;
} Lustre_arrow_ctx_type;

/* Delay_1_ctx */
typedef struct {
   /*INSTANCES*/
   Lustre_pre_ctx_type Lustre_pre_ctx_tab[1];
   Lustre_arrow_ctx_type Lustre_arrow_ctx_tab[1];
} Delay_1_ctx_type;

/* Since_Recurse_1_1_0_ctx */
typedef struct {
   /*INSTANCES*/
   Delay_1_ctx_type Delay_1_ctx_tab[1];
} Since_Recurse_1_1_0_ctx_type;

/* Since_Interval_1_1_ctx */
typedef struct {
   /*INSTANCES*/
   Since_Recurse_1_1_0_ctx_type Since_Recurse_1_1_0_ctx_tab[1];
} Since_Interval_1_1_ctx_type;

/* robustSpec_v6_Previous_ctx */
typedef struct {
   /*INSTANCES*/
   Since_Interval_1_1_ctx_type Since_Interval_1_1_ctx_tab[1];
} robustSpec_v6_Previous_ctx_type;

/* robustSpec_v6_f_AP_0_ctx */
typedef struct {
   /*INSTANCES*/
   robustSpec_v6_Previous_ctx_type robustSpec_v6_Previous_ctx_tab[1];
} robustSpec_v6_f_AP_0_ctx_type;

/* robustSpec_v6_ComputeRho_AP_ctx */
typedef struct {
   /*INSTANCES*/
   robustSpec_v6_f_AP_0_ctx_type robustSpec_v6_f_AP_0_ctx_tab[1];
} robustSpec_v6_ComputeRho_AP_ctx_type;

/* Delay_2_ctx */
typedef struct {
   /*INSTANCES*/
   Lustre_pre_ctx_type Lustre_pre_ctx_tab[1];
   Lustre_arrow_ctx_type Lustre_arrow_ctx_tab[1];
   Delay_1_ctx_type Delay_1_ctx_tab[1];
} Delay_2_ctx_type;

/* Sliding_Min_1_ctx */
typedef struct {
   /*INSTANCES*/
   Delay_1_ctx_type Delay_1_ctx_tab[1];
} Sliding_Min_1_ctx_type;

/* Delay_3_ctx */
typedef struct {
   /*INSTANCES*/
   Lustre_pre_ctx_type Lustre_pre_ctx_tab[1];
   Lustre_arrow_ctx_type Lustre_arrow_ctx_tab[1];
   Delay_2_ctx_type Delay_2_ctx_tab[1];
} Delay_3_ctx_type;

/* Sliding_Min_2_ctx */
typedef struct {
   /*INSTANCES*/
   Sliding_Min_1_ctx_type Sliding_Min_1_ctx_tab[1];
   Delay_2_ctx_type Delay_2_ctx_tab[1];
} Sliding_Min_2_ctx_type;

/* Delay_4_ctx */
typedef struct {
   /*INSTANCES*/
   Lustre_pre_ctx_type Lustre_pre_ctx_tab[1];
   Lustre_arrow_ctx_type Lustre_arrow_ctx_tab[1];
   Delay_3_ctx_type Delay_3_ctx_tab[1];
} Delay_4_ctx_type;

/* Sliding_Min_3_ctx */
typedef struct {
   /*INSTANCES*/
   Sliding_Min_2_ctx_type Sliding_Min_2_ctx_tab[1];
   Delay_3_ctx_type Delay_3_ctx_tab[1];
} Sliding_Min_3_ctx_type;

/* Delay_5_ctx */
typedef struct {
   /*INSTANCES*/
   Lustre_pre_ctx_type Lustre_pre_ctx_tab[1];
   Lustre_arrow_ctx_type Lustre_arrow_ctx_tab[1];
   Delay_4_ctx_type Delay_4_ctx_tab[1];
} Delay_5_ctx_type;

/* Sliding_Min_4_ctx */
typedef struct {
   /*INSTANCES*/
   Sliding_Min_3_ctx_type Sliding_Min_3_ctx_tab[1];
   Delay_4_ctx_type Delay_4_ctx_tab[1];
} Sliding_Min_4_ctx_type;

/* Since_Recurse_0_5_5_ctx */
typedef struct {
   /*INSTANCES*/
   Sliding_Min_4_ctx_type Sliding_Min_4_ctx_tab[1];
   Delay_5_ctx_type Delay_5_ctx_tab[1];
} Since_Recurse_0_5_5_ctx_type;

/* Since_Recurse_0_5_4_ctx */
typedef struct {
   /*INSTANCES*/
   Sliding_Min_3_ctx_type Sliding_Min_3_ctx_tab[1];
   Since_Recurse_0_5_5_ctx_type Since_Recurse_0_5_5_ctx_tab[1];
   Delay_4_ctx_type Delay_4_ctx_tab[1];
} Since_Recurse_0_5_4_ctx_type;

/* Since_Recurse_0_5_3_ctx */
typedef struct {
   /*INSTANCES*/
   Sliding_Min_2_ctx_type Sliding_Min_2_ctx_tab[1];
   Since_Recurse_0_5_4_ctx_type Since_Recurse_0_5_4_ctx_tab[1];
   Delay_3_ctx_type Delay_3_ctx_tab[1];
} Since_Recurse_0_5_3_ctx_type;

/* Since_Recurse_0_5_2_ctx */
typedef struct {
   /*INSTANCES*/
   Sliding_Min_1_ctx_type Sliding_Min_1_ctx_tab[1];
   Since_Recurse_0_5_3_ctx_type Since_Recurse_0_5_3_ctx_tab[1];
   Delay_2_ctx_type Delay_2_ctx_tab[1];
} Since_Recurse_0_5_2_ctx_type;

/* Since_Recurse_0_5_1_ctx */
typedef struct {
   /*INSTANCES*/
   Since_Recurse_0_5_2_ctx_type Since_Recurse_0_5_2_ctx_tab[1];
   Delay_1_ctx_type Delay_1_ctx_tab[1];
} Since_Recurse_0_5_1_ctx_type;

/* Since_Recurse_0_5_0_ctx */
typedef struct {
   /*INSTANCES*/
   Since_Recurse_0_5_1_ctx_type Since_Recurse_0_5_1_ctx_tab[1];
} Since_Recurse_0_5_0_ctx_type;

/* Since_Interval_0_5_ctx */
typedef struct {
   /*INSTANCES*/
   Since_Recurse_0_5_0_ctx_type Since_Recurse_0_5_0_ctx_tab[1];
} Since_Interval_0_5_ctx_type;

/* Once_Interval_0_5_ctx */
typedef struct {
   /*INSTANCES*/
   Since_Interval_0_5_ctx_type Since_Interval_0_5_ctx_tab[1];
} Once_Interval_0_5_ctx_type;

/* robustSpec_v6_ComputeRho_Phi_ctx */
typedef struct {
   /*INSTANCES*/
   Once_Interval_0_5_ctx_type Once_Interval_0_5_ctx_tab[1];
} robustSpec_v6_ComputeRho_Phi_ctx_type;

/* robustSpec_v6_Main_ctx */
typedef struct {
   /*INSTANCES*/
   robustSpec_v6_ComputeRho_Phi_ctx_type robustSpec_v6_ComputeRho_Phi_ctx_tab[1];
   robustSpec_v6_ComputeRho_AP_ctx_type robustSpec_v6_ComputeRho_AP_ctx_tab[1];
} robustSpec_v6_Main_ctx_type;

// Defining array and extern types assignments 

#ifndef _assign_rp2 
#define _assign_rp2(dest, source, size) memcpy(dest, source, size)
#endif

#ifndef _assign_rp3 
#define _assign_rp3(dest, source, size) memcpy(dest, source, size)
#endif
