/* This file was generated by lv6 version 6.101.17. */
/*  lv6 -2c -cc -n Main robustSpec_v6.lus */
/* on s27 the 01/04/2020 at 12:32:34 */
#include "lustre_types.h"
// Constant definitions 
#define robustSpec_v6_AP_size 2
#define robustSpec_v6_Phi_size 3
#define robustSpec_v6_TRUE_r 9999.0
#define robustSpec_v6_n 3
#define robustSpec_v6_set_point 2
#define robustSpec_v6_theta 0
