/* This file was generated by lv6 version 6.101.17. */
/*  lv6 -2c -cc -n Main robustSpec_v6.lus */
/* on s27 the 01/04/2020 at 12:32:34 */

#ifndef _SOC2C_PREDEF_TYPES
#define _SOC2C_PREDEF_TYPES
typedef int _boolean;
typedef int _integer;
typedef char* _string;
typedef double _real;
typedef double _double;
typedef float _float;
#define _false 0
#define _true 1
#endif
// end of _SOC2C_PREDEF_TYPES
// User typedef 
#ifndef _robustSpec_v6_Main_TYPES
#define _robustSpec_v6_Main_TYPES
typedef _real robustSpec_v6_PerformancePoint[3];
typedef _real robustSpec_v6_PerformancePoint_AP[2];
typedef struct { 
   _real t;
   _real s[3];
  } robustSpec_v6_SamplePoint;
#endif // enf of  _robustSpec_v6_Main_TYPES
// Memoryless soc ctx typedef 
// Memoryfull soc ctx typedef 
/* Lustre_pre_ctx */
typedef struct {
   /*Memory cell*/
   _real _memory ;
} Lustre_pre_ctx_type;

/* Lustre_arrow_ctx */
typedef struct {
   /*Memory cell*/
   _boolean _memory ;
} Lustre_arrow_ctx_type;

/* Delay_1_ctx */
typedef struct {
   /*INSTANCES*/
   Lustre_pre_ctx_type Lustre_pre_ctx_tab[1];
   Lustre_arrow_ctx_type Lustre_arrow_ctx_tab[1];
} Delay_1_ctx_type;

/* Since_Recurse_1_1_0_ctx */
typedef struct {
   /*INSTANCES*/
   Delay_1_ctx_type Delay_1_ctx_tab[1];
} Since_Recurse_1_1_0_ctx_type;

/* Since_Interval_1_1_ctx */
typedef struct {
   /*INSTANCES*/
   Since_Recurse_1_1_0_ctx_type Since_Recurse_1_1_0_ctx_tab[1];
} Since_Interval_1_1_ctx_type;

/* robustSpec_v6_Previous_ctx */
typedef struct {
   /*INSTANCES*/
   Since_Interval_1_1_ctx_type Since_Interval_1_1_ctx_tab[1];
} robustSpec_v6_Previous_ctx_type;

/* robustSpec_v6_f_AP_0_ctx */
typedef struct {
   /*INSTANCES*/
   robustSpec_v6_Previous_ctx_type robustSpec_v6_Previous_ctx_tab[1];
} robustSpec_v6_f_AP_0_ctx_type;

/* robustSpec_v6_ComputeRho_AP_ctx */
typedef struct {
   /*INSTANCES*/
   robustSpec_v6_f_AP_0_ctx_type robustSpec_v6_f_AP_0_ctx_tab[1];
} robustSpec_v6_ComputeRho_AP_ctx_type;

/* Delay_2_ctx */
typedef struct {
   /*INSTANCES*/
   Lustre_pre_ctx_type Lustre_pre_ctx_tab[1];
   Lustre_arrow_ctx_type Lustre_arrow_ctx_tab[1];
   Delay_1_ctx_type Delay_1_ctx_tab[1];
} Delay_2_ctx_type;

/* Sliding_Min_1_ctx */
typedef struct {
   /*INSTANCES*/
   Delay_1_ctx_type Delay_1_ctx_tab[1];
} Sliding_Min_1_ctx_type;

/* Delay_3_ctx */
typedef struct {
   /*INSTANCES*/
   Lustre_pre_ctx_type Lustre_pre_ctx_tab[1];
   Lustre_arrow_ctx_type Lustre_arrow_ctx_tab[1];
   Delay_2_ctx_type Delay_2_ctx_tab[1];
} Delay_3_ctx_type;

/* Sliding_Min_2_ctx */
typedef struct {
   /*INSTANCES*/
   Sliding_Min_1_ctx_type Sliding_Min_1_ctx_tab[1];
   Delay_2_ctx_type Delay_2_ctx_tab[1];
} Sliding_Min_2_ctx_type;

/* Delay_4_ctx */
typedef struct {
   /*INSTANCES*/
   Lustre_pre_ctx_type Lustre_pre_ctx_tab[1];
   Lustre_arrow_ctx_type Lustre_arrow_ctx_tab[1];
   Delay_3_ctx_type Delay_3_ctx_tab[1];
} Delay_4_ctx_type;

/* Sliding_Min_3_ctx */
typedef struct {
   /*INSTANCES*/
   Sliding_Min_2_ctx_type Sliding_Min_2_ctx_tab[1];
   Delay_3_ctx_type Delay_3_ctx_tab[1];
} Sliding_Min_3_ctx_type;

/* Delay_5_ctx */
typedef struct {
   /*INSTANCES*/
   Lustre_pre_ctx_type Lustre_pre_ctx_tab[1];
   Lustre_arrow_ctx_type Lustre_arrow_ctx_tab[1];
   Delay_4_ctx_type Delay_4_ctx_tab[1];
} Delay_5_ctx_type;

/* Sliding_Min_4_ctx */
typedef struct {
   /*INSTANCES*/
   Sliding_Min_3_ctx_type Sliding_Min_3_ctx_tab[1];
   Delay_4_ctx_type Delay_4_ctx_tab[1];
} Sliding_Min_4_ctx_type;

/* Delay_6_ctx */
typedef struct {
   /*INSTANCES*/
   Lustre_pre_ctx_type Lustre_pre_ctx_tab[1];
   Lustre_arrow_ctx_type Lustre_arrow_ctx_tab[1];
   Delay_5_ctx_type Delay_5_ctx_tab[1];
} Delay_6_ctx_type;

/* Sliding_Min_5_ctx */
typedef struct {
   /*INSTANCES*/
   Sliding_Min_4_ctx_type Sliding_Min_4_ctx_tab[1];
   Delay_5_ctx_type Delay_5_ctx_tab[1];
} Sliding_Min_5_ctx_type;

/* Delay_7_ctx */
typedef struct {
   /*INSTANCES*/
   Lustre_pre_ctx_type Lustre_pre_ctx_tab[1];
   Lustre_arrow_ctx_type Lustre_arrow_ctx_tab[1];
   Delay_6_ctx_type Delay_6_ctx_tab[1];
} Delay_7_ctx_type;

/* Sliding_Min_6_ctx */
typedef struct {
   /*INSTANCES*/
   Sliding_Min_5_ctx_type Sliding_Min_5_ctx_tab[1];
   Delay_6_ctx_type Delay_6_ctx_tab[1];
} Sliding_Min_6_ctx_type;

/* Delay_8_ctx */
typedef struct {
   /*INSTANCES*/
   Lustre_pre_ctx_type Lustre_pre_ctx_tab[1];
   Lustre_arrow_ctx_type Lustre_arrow_ctx_tab[1];
   Delay_7_ctx_type Delay_7_ctx_tab[1];
} Delay_8_ctx_type;

/* Sliding_Min_7_ctx */
typedef struct {
   /*INSTANCES*/
   Sliding_Min_6_ctx_type Sliding_Min_6_ctx_tab[1];
   Delay_7_ctx_type Delay_7_ctx_tab[1];
} Sliding_Min_7_ctx_type;

/* Delay_9_ctx */
typedef struct {
   /*INSTANCES*/
   Lustre_pre_ctx_type Lustre_pre_ctx_tab[1];
   Lustre_arrow_ctx_type Lustre_arrow_ctx_tab[1];
   Delay_8_ctx_type Delay_8_ctx_tab[1];
} Delay_9_ctx_type;

/* Sliding_Min_8_ctx */
typedef struct {
   /*INSTANCES*/
   Sliding_Min_7_ctx_type Sliding_Min_7_ctx_tab[1];
   Delay_8_ctx_type Delay_8_ctx_tab[1];
} Sliding_Min_8_ctx_type;

/* Delay_10_ctx */
typedef struct {
   /*INSTANCES*/
   Lustre_pre_ctx_type Lustre_pre_ctx_tab[1];
   Lustre_arrow_ctx_type Lustre_arrow_ctx_tab[1];
   Delay_9_ctx_type Delay_9_ctx_tab[1];
} Delay_10_ctx_type;

/* Sliding_Min_9_ctx */
typedef struct {
   /*INSTANCES*/
   Sliding_Min_8_ctx_type Sliding_Min_8_ctx_tab[1];
   Delay_9_ctx_type Delay_9_ctx_tab[1];
} Sliding_Min_9_ctx_type;

/* Delay_11_ctx */
typedef struct {
   /*INSTANCES*/
   Lustre_pre_ctx_type Lustre_pre_ctx_tab[1];
   Lustre_arrow_ctx_type Lustre_arrow_ctx_tab[1];
   Delay_10_ctx_type Delay_10_ctx_tab[1];
} Delay_11_ctx_type;

/* Sliding_Min_10_ctx */
typedef struct {
   /*INSTANCES*/
   Sliding_Min_9_ctx_type Sliding_Min_9_ctx_tab[1];
   Delay_10_ctx_type Delay_10_ctx_tab[1];
} Sliding_Min_10_ctx_type;

/* Delay_12_ctx */
typedef struct {
   /*INSTANCES*/
   Lustre_pre_ctx_type Lustre_pre_ctx_tab[1];
   Lustre_arrow_ctx_type Lustre_arrow_ctx_tab[1];
   Delay_11_ctx_type Delay_11_ctx_tab[1];
} Delay_12_ctx_type;

/* Sliding_Min_11_ctx */
typedef struct {
   /*INSTANCES*/
   Sliding_Min_10_ctx_type Sliding_Min_10_ctx_tab[1];
   Delay_11_ctx_type Delay_11_ctx_tab[1];
} Sliding_Min_11_ctx_type;

/* Delay_13_ctx */
typedef struct {
   /*INSTANCES*/
   Lustre_pre_ctx_type Lustre_pre_ctx_tab[1];
   Lustre_arrow_ctx_type Lustre_arrow_ctx_tab[1];
   Delay_12_ctx_type Delay_12_ctx_tab[1];
} Delay_13_ctx_type;

/* Sliding_Min_12_ctx */
typedef struct {
   /*INSTANCES*/
   Sliding_Min_11_ctx_type Sliding_Min_11_ctx_tab[1];
   Delay_12_ctx_type Delay_12_ctx_tab[1];
} Sliding_Min_12_ctx_type;

/* Delay_14_ctx */
typedef struct {
   /*INSTANCES*/
   Lustre_pre_ctx_type Lustre_pre_ctx_tab[1];
   Lustre_arrow_ctx_type Lustre_arrow_ctx_tab[1];
   Delay_13_ctx_type Delay_13_ctx_tab[1];
} Delay_14_ctx_type;

/* Sliding_Min_13_ctx */
typedef struct {
   /*INSTANCES*/
   Sliding_Min_12_ctx_type Sliding_Min_12_ctx_tab[1];
   Delay_13_ctx_type Delay_13_ctx_tab[1];
} Sliding_Min_13_ctx_type;

/* Delay_15_ctx */
typedef struct {
   /*INSTANCES*/
   Lustre_pre_ctx_type Lustre_pre_ctx_tab[1];
   Lustre_arrow_ctx_type Lustre_arrow_ctx_tab[1];
   Delay_14_ctx_type Delay_14_ctx_tab[1];
} Delay_15_ctx_type;

/* Sliding_Min_14_ctx */
typedef struct {
   /*INSTANCES*/
   Sliding_Min_13_ctx_type Sliding_Min_13_ctx_tab[1];
   Delay_14_ctx_type Delay_14_ctx_tab[1];
} Sliding_Min_14_ctx_type;

/* Since_Recurse_0_15_15_ctx */
typedef struct {
   /*INSTANCES*/
   Sliding_Min_14_ctx_type Sliding_Min_14_ctx_tab[1];
   Delay_15_ctx_type Delay_15_ctx_tab[1];
} Since_Recurse_0_15_15_ctx_type;

/* Since_Recurse_0_15_14_ctx */
typedef struct {
   /*INSTANCES*/
   Sliding_Min_13_ctx_type Sliding_Min_13_ctx_tab[1];
   Since_Recurse_0_15_15_ctx_type Since_Recurse_0_15_15_ctx_tab[1];
   Delay_14_ctx_type Delay_14_ctx_tab[1];
} Since_Recurse_0_15_14_ctx_type;

/* Since_Recurse_0_15_13_ctx */
typedef struct {
   /*INSTANCES*/
   Sliding_Min_12_ctx_type Sliding_Min_12_ctx_tab[1];
   Since_Recurse_0_15_14_ctx_type Since_Recurse_0_15_14_ctx_tab[1];
   Delay_13_ctx_type Delay_13_ctx_tab[1];
} Since_Recurse_0_15_13_ctx_type;

/* Since_Recurse_0_15_12_ctx */
typedef struct {
   /*INSTANCES*/
   Sliding_Min_11_ctx_type Sliding_Min_11_ctx_tab[1];
   Since_Recurse_0_15_13_ctx_type Since_Recurse_0_15_13_ctx_tab[1];
   Delay_12_ctx_type Delay_12_ctx_tab[1];
} Since_Recurse_0_15_12_ctx_type;

/* Since_Recurse_0_15_11_ctx */
typedef struct {
   /*INSTANCES*/
   Sliding_Min_10_ctx_type Sliding_Min_10_ctx_tab[1];
   Since_Recurse_0_15_12_ctx_type Since_Recurse_0_15_12_ctx_tab[1];
   Delay_11_ctx_type Delay_11_ctx_tab[1];
} Since_Recurse_0_15_11_ctx_type;

/* Since_Recurse_0_15_10_ctx */
typedef struct {
   /*INSTANCES*/
   Sliding_Min_9_ctx_type Sliding_Min_9_ctx_tab[1];
   Since_Recurse_0_15_11_ctx_type Since_Recurse_0_15_11_ctx_tab[1];
   Delay_10_ctx_type Delay_10_ctx_tab[1];
} Since_Recurse_0_15_10_ctx_type;

/* Since_Recurse_0_15_9_ctx */
typedef struct {
   /*INSTANCES*/
   Sliding_Min_8_ctx_type Sliding_Min_8_ctx_tab[1];
   Since_Recurse_0_15_10_ctx_type Since_Recurse_0_15_10_ctx_tab[1];
   Delay_9_ctx_type Delay_9_ctx_tab[1];
} Since_Recurse_0_15_9_ctx_type;

/* Since_Recurse_0_15_8_ctx */
typedef struct {
   /*INSTANCES*/
   Sliding_Min_7_ctx_type Sliding_Min_7_ctx_tab[1];
   Since_Recurse_0_15_9_ctx_type Since_Recurse_0_15_9_ctx_tab[1];
   Delay_8_ctx_type Delay_8_ctx_tab[1];
} Since_Recurse_0_15_8_ctx_type;

/* Since_Recurse_0_15_7_ctx */
typedef struct {
   /*INSTANCES*/
   Sliding_Min_6_ctx_type Sliding_Min_6_ctx_tab[1];
   Since_Recurse_0_15_8_ctx_type Since_Recurse_0_15_8_ctx_tab[1];
   Delay_7_ctx_type Delay_7_ctx_tab[1];
} Since_Recurse_0_15_7_ctx_type;

/* Since_Recurse_0_15_6_ctx */
typedef struct {
   /*INSTANCES*/
   Sliding_Min_5_ctx_type Sliding_Min_5_ctx_tab[1];
   Since_Recurse_0_15_7_ctx_type Since_Recurse_0_15_7_ctx_tab[1];
   Delay_6_ctx_type Delay_6_ctx_tab[1];
} Since_Recurse_0_15_6_ctx_type;

/* Since_Recurse_0_15_5_ctx */
typedef struct {
   /*INSTANCES*/
   Sliding_Min_4_ctx_type Sliding_Min_4_ctx_tab[1];
   Since_Recurse_0_15_6_ctx_type Since_Recurse_0_15_6_ctx_tab[1];
   Delay_5_ctx_type Delay_5_ctx_tab[1];
} Since_Recurse_0_15_5_ctx_type;

/* Since_Recurse_0_15_4_ctx */
typedef struct {
   /*INSTANCES*/
   Sliding_Min_3_ctx_type Sliding_Min_3_ctx_tab[1];
   Since_Recurse_0_15_5_ctx_type Since_Recurse_0_15_5_ctx_tab[1];
   Delay_4_ctx_type Delay_4_ctx_tab[1];
} Since_Recurse_0_15_4_ctx_type;

/* Since_Recurse_0_15_3_ctx */
typedef struct {
   /*INSTANCES*/
   Sliding_Min_2_ctx_type Sliding_Min_2_ctx_tab[1];
   Since_Recurse_0_15_4_ctx_type Since_Recurse_0_15_4_ctx_tab[1];
   Delay_3_ctx_type Delay_3_ctx_tab[1];
} Since_Recurse_0_15_3_ctx_type;

/* Since_Recurse_0_15_2_ctx */
typedef struct {
   /*INSTANCES*/
   Sliding_Min_1_ctx_type Sliding_Min_1_ctx_tab[1];
   Since_Recurse_0_15_3_ctx_type Since_Recurse_0_15_3_ctx_tab[1];
   Delay_2_ctx_type Delay_2_ctx_tab[1];
} Since_Recurse_0_15_2_ctx_type;

/* Since_Recurse_0_15_1_ctx */
typedef struct {
   /*INSTANCES*/
   Since_Recurse_0_15_2_ctx_type Since_Recurse_0_15_2_ctx_tab[1];
   Delay_1_ctx_type Delay_1_ctx_tab[1];
} Since_Recurse_0_15_1_ctx_type;

/* Since_Recurse_0_15_0_ctx */
typedef struct {
   /*INSTANCES*/
   Since_Recurse_0_15_1_ctx_type Since_Recurse_0_15_1_ctx_tab[1];
} Since_Recurse_0_15_0_ctx_type;

/* Since_Interval_0_15_ctx */
typedef struct {
   /*INSTANCES*/
   Since_Recurse_0_15_0_ctx_type Since_Recurse_0_15_0_ctx_tab[1];
} Since_Interval_0_15_ctx_type;

/* Once_Interval_0_15_ctx */
typedef struct {
   /*INSTANCES*/
   Since_Interval_0_15_ctx_type Since_Interval_0_15_ctx_tab[1];
} Once_Interval_0_15_ctx_type;

/* robustSpec_v6_ComputeRho_Phi_ctx */
typedef struct {
   /*INSTANCES*/
   Once_Interval_0_15_ctx_type Once_Interval_0_15_ctx_tab[2];
} robustSpec_v6_ComputeRho_Phi_ctx_type;

/* robustSpec_v6_Main_ctx */
typedef struct {
   /*INSTANCES*/
   robustSpec_v6_ComputeRho_Phi_ctx_type robustSpec_v6_ComputeRho_Phi_ctx_tab[1];
   robustSpec_v6_ComputeRho_AP_ctx_type robustSpec_v6_ComputeRho_AP_ctx_tab[1];
} robustSpec_v6_Main_ctx_type;


// Defining array and extern types assignments 

#ifndef _assign_rp2 
#define _assign_rp2(dest, source, size) memcpy(dest, source, size)
#endif

#ifndef _assign_rp3 
#define _assign_rp3(dest, source, size) memcpy(dest, source, size)
#endif
