/* This file was generated by lv6 version master.737 (2727a7744111c84f7984634d2bd3ad6f7c6c7ff9). */
/*  lv6 -2c -cc -n Main robustSpec_v6.lus */
/* on s27 the 03/04/2020 at 08:27:05 */
#include "lustre_consts.h"