/* This file was generated by lv6 version master.737 (2727a7744111c84f7984634d2bd3ad6f7c6c7ff9). */
/*  lv6 -2c -cc -n Main robustSpec_v6.lus */
/* on s27 the 03/04/2020 at 08:27:05 */

// Constant definitions 
#define robustSpec_v6_AP_size 2
#define robustSpec_v6_Phi_size 3
#define robustSpec_v6_TRUE_r 9999.0
#define robustSpec_v6_n 3
#define robustSpec_v6_set_point 2
#define robustSpec_v6_theta 0
