/* This file was generated by lv6 version master.737 (2727a7744111c84f7984634d2bd3ad6f7c6c7ff9). */
/*  lv6 -2c -cc -n Main robustSpec_v6.lus */
/* on s27 the 03/04/2020 at 08:27:05 */

#include <stdlib.h>
#include <stdio.h>
#include <unistd.h>
#include "robustSpec_v6_Main.h" 
/* Print a promt ? ************************/
static int ISATTY;
/* MACROS DEFINITIONS ****************/
#ifndef TT
#define TT "1"
#endif
#ifndef FF
#define FF "0"
#endif
#ifndef BB
#define BB "bottom"
#endif
#ifdef CKCHECK
/* set this macro for testing output clocks */
#endif

/* Standard Input procedures **************/
_boolean _get_bool(char* n){
   char b[512];
   _boolean r = 0;
   int s = 1;
   char c;
   do {
      if(ISATTY) {
         if((s != 1)||(r == -1)) printf("\a");
         // printf("%s (1,t,T/0,f,F) ? ", n);
      }
      if(scanf("%s", b)==EOF) exit(0);
      if (*b == 'q') exit(0);
      s = sscanf(b, "%c", &c);
      r = -1;
      if((c == '0') || (c == 'f') || (c == 'F')) r = 0;
      if((c == '1') || (c == 't') || (c == 'T')) r = 1;
   } while((s != 1) || (r == -1));
   return r;
}
_integer _get_int(char* n){
   char b[512];
   _integer r;
   int s = 1;
   do {
      if(ISATTY) {
         if(s != 1) printf("\a");
         //printf("%s (integer) ? ", n);
      }
      if(scanf("%s", b)==EOF) exit(0);
      if (*b == 'q') exit(0);
      s = sscanf(b, "%d", &r);
   } while(s != 1);
   return r;
}
#define REALFORMAT ((sizeof(_real)==8)?"%lf":"%f")
_real _get_real(char* n){
   char b[512];
   _real r;
   int s = 1;
   do {
      if(ISATTY) {
         if(s != 1) printf("\a");
         //printf("%s (real) ? ", n);
      }
      if(scanf("%s", b)==EOF) exit(0);
      if (*b == 'q') exit(0);
      s = sscanf(b, REALFORMAT, &r);
   } while(s != 1);
   return r;
}
/* Standard Output procedures **************/
void _put_bottom(char* n){
   if(ISATTY) printf("%s = ", n);
   printf("%s ", BB);
   if(ISATTY) printf("\n");
}
void _put_bool(char* n, _boolean _V){
   if(ISATTY) printf("%s = ", n);
   printf("%s ", (_V)? TT : FF);
   if(ISATTY) printf("\n");
}
void _put_int(char* n, _integer _V){
   if(ISATTY) printf("%s = ", n);
   printf("%d ", _V);
   if(ISATTY) printf("\n");
}
void _put_real(char* n, _real _V){
   if(ISATTY) printf("%s = ", n);
   printf("%f ", _V);
   if(ISATTY) printf("\n");
}
/* Output procedures **********************/
#ifdef CKCHECK
void %s_BOT_n(void* cdata){
   _put_bottom("n");
}
#endif
/* Output procedures **********************/
void robustSpec_v6_Main_O_n(void* cdata, _integer _V) {
   _put_int("n", _V);
}
/* Main procedure *************************/
int main(){
  int _s = 0;
  robustSpec_v6_SamplePoint SP;
  _real Rho[3];
    robustSpec_v6_Main_ctx_type* ctx = robustSpec_v6_Main_ctx_new_ctx(NULL);

  printf("#inputs \"SP_t\":real \"SP_s_0\":real \"SP_s_1\":real \"SP_s_2\":real\n");
  printf("#outputs \"Rho_0\":real \"Rho_1\":real \"Rho_2\":real\n");

  /* Main loop */
  ISATTY = isatty(0);
  while(1){
    if (ISATTY) printf("#step %d \n", _s+1);
    else if(_s) printf("\n");
    fflush(stdout);
    ++_s;
     SP.t = _get_real("SP.t");
     SP.s[0] = _get_real("SP.s[0]");
     SP.s[1] = _get_real("SP.s[1]");
     SP.s[2] = _get_real("SP.s[2]");
    robustSpec_v6_Main_step(SP,Rho,ctx);
    // printf("%f %f %f %f #outs %f %f %f\n",SP.t,SP.s[0],SP.s[1],SP.s[2],Rho[0],Rho[1],Rho[2]);
    printf("%f %f %f\n",Rho[0],Rho[1],Rho[2]);
  }
  return 1;
   
}
