/* This file was generated by lv6 version 6.101.17. */
/*  lv6 -2c -cc -n Main robustSpec_v6.lus */
/* on s27 the 01/04/2020 at 12:32:34 */

#include <stdlib.h>
#include <stdio.h>
#include <unistd.h>
#include "robustSpec_v6_Main.h" 
/* Print a promt ? ************************/
static int ISATTY;
/* MACROS DEFINITIONS ****************/
#ifndef TT
#define TT "1"
#endif
#ifndef FF
#define FF "0"
#endif
#ifndef BB
#define BB "bottom"
#endif
#ifdef CKCHECK
/* set this macro for testing output clocks */
#endif

void _read_pragma(robustSpec_v6_Main_ctx_type* ctx,char b[]) {
   int s = 1;

   if (!strcmp(b,"#quit")) exit(0);
   if (!strcmp(b,"#q")) exit(0);
   if (!strcmp(b,"#reset")) robustSpec_v6_Main_ctx_reset(ctx);
   return;
}

/* Standard Input procedures **************/
_boolean _get_bool(robustSpec_v6_Main_ctx_type* ctx,char* n){
   char b[512];
   char c;
   _boolean r = 0;
   int s = 1;
   do {
      if(ISATTY) {
         if((s != 1)||(r == -1)) printf("\a");
         // printf("%s (1,t,T/0,f,F) ? ", n);
      }
      if(scanf("%s", b)==EOF) exit(0);
      r = -1;
      c=b[0];
      if(c == 'q') exit(0);
      if(c == '#') _read_pragma(ctx,b);
      if((c == '0') || (c == 'f') || (c == 'F')) r = 0;
      if((c == '1') || (c == 't') || (c == 'T')) r = 1;
   } while((s != 1) || (r == -1));
   return r;
}
_integer _get_int(robustSpec_v6_Main_ctx_type* ctx,char* n){
   char b[512];
   _integer r;
   int s = 1;
   do {
      if(ISATTY) {
         if(s != 1) printf("\a");
         //printf("%s (integer) ? ", n);
      }
      if(scanf("%s", b)==EOF) exit(0);
      if(*b == 'q') exit(0);
      if(*b == '#') {
         _read_pragma(ctx,b);
      } else {
        s = sscanf(b, "%d", &r);
      }
   } while(s != 1);
   return r;
}
#define REALFORMAT ((sizeof(_real)==8)?"%lf":"%f")
_real _get_real(robustSpec_v6_Main_ctx_type* ctx,char* n){
   char b[512];
   _real r;
   int s = 1;
   do {
      if(ISATTY) {
         if(s != 1) printf("\a");
         //printf("%s (real) ? ", n);
      }
      if(scanf("%s", b)==EOF) exit(0);
      if(*b == 'q') exit(0);
      if(*b == '#') {
         _read_pragma(ctx,b);
      } else {
         s = sscanf(b, REALFORMAT, &r);
      }
   } while(s != 1);
   return r;
}
char* _get_string(robustSpec_v6_Main_ctx_type* ctx,char* n){
   char b[512];
   char* r;
   int s = 1;
   do {
      if(ISATTY) {
         if(s != 1) printf("\a");
         //printf("%s (real) ? ", n);
      }
      if(scanf("%s", b)==EOF) exit(0);
      if(*b == '#') {
         _read_pragma(ctx,b);
      }
   } while(s != 1);
   r =  b;
   return r;
}
/* Standard Output procedures **************/
void _put_bottom(char* n){
   if(ISATTY) printf("%s = ", n);
   printf("%s ", BB);
   if(ISATTY) printf("\n");
}
void _put_bool(char* n, _boolean _V){
   if(ISATTY) printf("%s = ", n);
   printf("%s ", (_V)? TT : FF);
   if(ISATTY) printf("\n");
}
void _put_int(char* n, _integer _V){
   if(ISATTY) printf("%s = ", n);
   printf("%d ", _V);
   if(ISATTY) printf("\n");
}
void _put_real(char* n, _real _V){
   if(ISATTY) printf("%s = ", n);
   printf("%f ", _V);
   if(ISATTY) printf("\n");
}
void _put_string(char* n, char* _V){
   if(ISATTY) printf("%s = ", n);
   printf("%s ", _V);
   if(ISATTY) printf("\n");
}

/* Output procedures **********************/
#ifdef CKCHECK
void %s_BOT_n(void* cdata){
   _put_bottom("n");
}
#endif

/* Main procedure *************************/
int main(){
  int _s = 0;
  robustSpec_v6_SamplePoint SP;
  _real Rho[3];
    robustSpec_v6_Main_ctx_type* ctx = robustSpec_v6_Main_ctx_new_ctx(NULL);

  printf("#inputs \"SP_t\":real \"SP_s_0\":real \"SP_s_1\":real \"SP_s_2\":real\n");
  printf("#outputs \"Rho_0\":real \"Rho_1\":real \"Rho_2\":real\n");

  /* Main loop */
  ISATTY = isatty(0);
  while(1){
    if (ISATTY) printf("#step %d \n", _s+1);
    else if(_s) printf("\n");
    fflush(stdout);
    ++_s;
    SP.t = _get_real(ctx,"SP.t");
    SP.s[0] = _get_real(ctx,"SP.s[0]");
    SP.s[1] = _get_real(ctx,"SP.s[1]");
    SP.s[2] = _get_real(ctx,"SP.s[2]");
    robustSpec_v6_Main_step(SP,Rho,ctx);
    // printf("%f %f %f %f #outs %f %f %f\n",SP.t,SP.s[0],SP.s[1],SP.s[2],Rho[0],Rho[1],Rho[2]);
    printf("%f %f %f\n",Rho[0],Rho[1],Rho[2]);
  }
  return 1;
   
}
