/* This file was generated by lv6 version 6.101.17. */
/*  lv6 -2c -cc -n Main robustSpec_v6.lus */
/* on s27 the 01/04/2020 at 12:32:34 */
#include "robustSpec_v6_Main.h"
//// Defining step functions
// Step function(s) for Delay_0_ctx
void Delay_0_step(_real x,_real *z){

  *z = x;

} // End of Delay_0_step

// Memory initialisation for Delay_1_ctx
void Delay_1_ctx_reset(Delay_1_ctx_type* ctx){
  int _i;

    Lustre_pre_ctx_reset(&ctx->Lustre_pre_ctx_tab[0]);
    Lustre_arrow_ctx_reset(&ctx->Lustre_arrow_ctx_tab[0]);
}
// Memory allocation for Delay_1_ctx
Delay_1_ctx_type* Delay_1_ctx_new_ctx(){

   Delay_1_ctx_type* ctx = (Delay_1_ctx_type*)calloc(1, sizeof(Delay_1_ctx_type));
   // ctx->client_data = cdata;
   Delay_1_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Delay_1_ctx
void Delay_1_step(_real x,_real *z,Delay_1_ctx_type* ctx){   _real _split_6;
   _real _split_5;

  Lustre_pre_get(&_split_6,&ctx->Lustre_pre_ctx_tab[0]); 
  Delay_0_step(x,&_split_5); 
  Lustre_pre_set(_split_5,&ctx->Lustre_pre_ctx_tab[0]); 
  Lustre_arrow_step(x,_split_6,z,&ctx->Lustre_arrow_ctx_tab[0]); 

} // End of Delay_1_step

// Memory initialisation for Delay_10_ctx
void Delay_10_ctx_reset(Delay_10_ctx_type* ctx){
  int _i;

    Lustre_pre_ctx_reset(&ctx->Lustre_pre_ctx_tab[0]);
    Lustre_arrow_ctx_reset(&ctx->Lustre_arrow_ctx_tab[0]);
    Delay_9_ctx_reset(&ctx->Delay_9_ctx_tab[0]);
}
// Memory allocation for Delay_10_ctx
Delay_10_ctx_type* Delay_10_ctx_new_ctx(){

   Delay_10_ctx_type* ctx = (Delay_10_ctx_type*)calloc(1, sizeof(Delay_10_ctx_type));
   // ctx->client_data = cdata;
   Delay_10_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Delay_10_ctx
void Delay_10_step(_real x,_real *z,Delay_10_ctx_type* ctx){   _real _split_8;
   _real _split_7;

  Lustre_pre_get(&_split_8,&ctx->Lustre_pre_ctx_tab[0]); 
  Delay_9_step(x,&_split_7,&ctx->Delay_9_ctx_tab[0]); 
  Lustre_pre_set(_split_7,&ctx->Lustre_pre_ctx_tab[0]); 
  Lustre_arrow_step(x,_split_8,z,&ctx->Lustre_arrow_ctx_tab[0]); 

} // End of Delay_10_step

// Memory initialisation for Delay_11_ctx
void Delay_11_ctx_reset(Delay_11_ctx_type* ctx){
  int _i;

    Lustre_pre_ctx_reset(&ctx->Lustre_pre_ctx_tab[0]);
    Lustre_arrow_ctx_reset(&ctx->Lustre_arrow_ctx_tab[0]);
    Delay_10_ctx_reset(&ctx->Delay_10_ctx_tab[0]);
}
// Memory allocation for Delay_11_ctx
Delay_11_ctx_type* Delay_11_ctx_new_ctx(){

   Delay_11_ctx_type* ctx = (Delay_11_ctx_type*)calloc(1, sizeof(Delay_11_ctx_type));
   // ctx->client_data = cdata;
   Delay_11_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Delay_11_ctx
void Delay_11_step(_real x,_real *z,Delay_11_ctx_type* ctx){   _real _split_10;
   _real _split_9;

  Lustre_pre_get(&_split_10,&ctx->Lustre_pre_ctx_tab[0]); 
  Delay_10_step(x,&_split_9,&ctx->Delay_10_ctx_tab[0]); 
  Lustre_pre_set(_split_9,&ctx->Lustre_pre_ctx_tab[0]); 
  Lustre_arrow_step(x,_split_10,z,&ctx->Lustre_arrow_ctx_tab[0]); 

} // End of Delay_11_step

// Memory initialisation for Delay_12_ctx
void Delay_12_ctx_reset(Delay_12_ctx_type* ctx){
  int _i;

    Lustre_pre_ctx_reset(&ctx->Lustre_pre_ctx_tab[0]);
    Lustre_arrow_ctx_reset(&ctx->Lustre_arrow_ctx_tab[0]);
    Delay_11_ctx_reset(&ctx->Delay_11_ctx_tab[0]);
}
// Memory allocation for Delay_12_ctx
Delay_12_ctx_type* Delay_12_ctx_new_ctx(){

   Delay_12_ctx_type* ctx = (Delay_12_ctx_type*)calloc(1, sizeof(Delay_12_ctx_type));
   // ctx->client_data = cdata;
   Delay_12_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Delay_12_ctx
void Delay_12_step(_real x,_real *z,Delay_12_ctx_type* ctx){   _real _split_12;
   _real _split_11;

  Lustre_pre_get(&_split_12,&ctx->Lustre_pre_ctx_tab[0]); 
  Delay_11_step(x,&_split_11,&ctx->Delay_11_ctx_tab[0]); 
  Lustre_pre_set(_split_11,&ctx->Lustre_pre_ctx_tab[0]); 
  Lustre_arrow_step(x,_split_12,z,&ctx->Lustre_arrow_ctx_tab[0]); 

} // End of Delay_12_step

// Memory initialisation for Delay_13_ctx
void Delay_13_ctx_reset(Delay_13_ctx_type* ctx){
  int _i;

    Lustre_pre_ctx_reset(&ctx->Lustre_pre_ctx_tab[0]);
    Lustre_arrow_ctx_reset(&ctx->Lustre_arrow_ctx_tab[0]);
    Delay_12_ctx_reset(&ctx->Delay_12_ctx_tab[0]);
}
// Memory allocation for Delay_13_ctx
Delay_13_ctx_type* Delay_13_ctx_new_ctx(){

   Delay_13_ctx_type* ctx = (Delay_13_ctx_type*)calloc(1, sizeof(Delay_13_ctx_type));
   // ctx->client_data = cdata;
   Delay_13_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Delay_13_ctx
void Delay_13_step(_real x,_real *z,Delay_13_ctx_type* ctx){   _real _split_14;
   _real _split_13;

  Lustre_pre_get(&_split_14,&ctx->Lustre_pre_ctx_tab[0]); 
  Delay_12_step(x,&_split_13,&ctx->Delay_12_ctx_tab[0]); 
  Lustre_pre_set(_split_13,&ctx->Lustre_pre_ctx_tab[0]); 
  Lustre_arrow_step(x,_split_14,z,&ctx->Lustre_arrow_ctx_tab[0]); 

} // End of Delay_13_step

// Memory initialisation for Delay_14_ctx
void Delay_14_ctx_reset(Delay_14_ctx_type* ctx){
  int _i;

    Lustre_pre_ctx_reset(&ctx->Lustre_pre_ctx_tab[0]);
    Lustre_arrow_ctx_reset(&ctx->Lustre_arrow_ctx_tab[0]);
    Delay_13_ctx_reset(&ctx->Delay_13_ctx_tab[0]);
}
// Memory allocation for Delay_14_ctx
Delay_14_ctx_type* Delay_14_ctx_new_ctx(){

   Delay_14_ctx_type* ctx = (Delay_14_ctx_type*)calloc(1, sizeof(Delay_14_ctx_type));
   // ctx->client_data = cdata;
   Delay_14_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Delay_14_ctx
void Delay_14_step(_real x,_real *z,Delay_14_ctx_type* ctx){   _real _split_16;
   _real _split_15;

  Lustre_pre_get(&_split_16,&ctx->Lustre_pre_ctx_tab[0]); 
  Delay_13_step(x,&_split_15,&ctx->Delay_13_ctx_tab[0]); 
  Lustre_pre_set(_split_15,&ctx->Lustre_pre_ctx_tab[0]); 
  Lustre_arrow_step(x,_split_16,z,&ctx->Lustre_arrow_ctx_tab[0]); 

} // End of Delay_14_step

// Memory initialisation for Delay_15_ctx
void Delay_15_ctx_reset(Delay_15_ctx_type* ctx){
  int _i;

    Lustre_pre_ctx_reset(&ctx->Lustre_pre_ctx_tab[0]);
    Lustre_arrow_ctx_reset(&ctx->Lustre_arrow_ctx_tab[0]);
    Delay_14_ctx_reset(&ctx->Delay_14_ctx_tab[0]);
}
// Memory allocation for Delay_15_ctx
Delay_15_ctx_type* Delay_15_ctx_new_ctx(){

   Delay_15_ctx_type* ctx = (Delay_15_ctx_type*)calloc(1, sizeof(Delay_15_ctx_type));
   // ctx->client_data = cdata;
   Delay_15_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Delay_15_ctx
void Delay_15_step(_real x,_real *z,Delay_15_ctx_type* ctx){   _real _split_18;
   _real _split_17;

  Lustre_pre_get(&_split_18,&ctx->Lustre_pre_ctx_tab[0]); 
  Delay_14_step(x,&_split_17,&ctx->Delay_14_ctx_tab[0]); 
  Lustre_pre_set(_split_17,&ctx->Lustre_pre_ctx_tab[0]); 
  Lustre_arrow_step(x,_split_18,z,&ctx->Lustre_arrow_ctx_tab[0]); 

} // End of Delay_15_step

// Memory initialisation for Delay_2_ctx
void Delay_2_ctx_reset(Delay_2_ctx_type* ctx){
  int _i;

    Lustre_pre_ctx_reset(&ctx->Lustre_pre_ctx_tab[0]);
    Lustre_arrow_ctx_reset(&ctx->Lustre_arrow_ctx_tab[0]);
    Delay_1_ctx_reset(&ctx->Delay_1_ctx_tab[0]);
}
// Memory allocation for Delay_2_ctx
Delay_2_ctx_type* Delay_2_ctx_new_ctx(){

   Delay_2_ctx_type* ctx = (Delay_2_ctx_type*)calloc(1, sizeof(Delay_2_ctx_type));
   // ctx->client_data = cdata;
   Delay_2_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Delay_2_ctx
void Delay_2_step(_real x,_real *z,Delay_2_ctx_type* ctx){   _real _split_20;
   _real _split_19;

  Lustre_pre_get(&_split_20,&ctx->Lustre_pre_ctx_tab[0]); 
  Delay_1_step(x,&_split_19,&ctx->Delay_1_ctx_tab[0]); 
  Lustre_pre_set(_split_19,&ctx->Lustre_pre_ctx_tab[0]); 
  Lustre_arrow_step(x,_split_20,z,&ctx->Lustre_arrow_ctx_tab[0]); 

} // End of Delay_2_step

// Memory initialisation for Delay_3_ctx
void Delay_3_ctx_reset(Delay_3_ctx_type* ctx){
  int _i;

    Lustre_pre_ctx_reset(&ctx->Lustre_pre_ctx_tab[0]);
    Lustre_arrow_ctx_reset(&ctx->Lustre_arrow_ctx_tab[0]);
    Delay_2_ctx_reset(&ctx->Delay_2_ctx_tab[0]);
}
// Memory allocation for Delay_3_ctx
Delay_3_ctx_type* Delay_3_ctx_new_ctx(){

   Delay_3_ctx_type* ctx = (Delay_3_ctx_type*)calloc(1, sizeof(Delay_3_ctx_type));
   // ctx->client_data = cdata;
   Delay_3_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Delay_3_ctx
void Delay_3_step(_real x,_real *z,Delay_3_ctx_type* ctx){   _real _split_22;
   _real _split_21;

  Lustre_pre_get(&_split_22,&ctx->Lustre_pre_ctx_tab[0]); 
  Delay_2_step(x,&_split_21,&ctx->Delay_2_ctx_tab[0]); 
  Lustre_pre_set(_split_21,&ctx->Lustre_pre_ctx_tab[0]); 
  Lustre_arrow_step(x,_split_22,z,&ctx->Lustre_arrow_ctx_tab[0]); 

} // End of Delay_3_step

// Memory initialisation for Delay_4_ctx
void Delay_4_ctx_reset(Delay_4_ctx_type* ctx){
  int _i;

    Lustre_pre_ctx_reset(&ctx->Lustre_pre_ctx_tab[0]);
    Lustre_arrow_ctx_reset(&ctx->Lustre_arrow_ctx_tab[0]);
    Delay_3_ctx_reset(&ctx->Delay_3_ctx_tab[0]);
}
// Memory allocation for Delay_4_ctx
Delay_4_ctx_type* Delay_4_ctx_new_ctx(){

   Delay_4_ctx_type* ctx = (Delay_4_ctx_type*)calloc(1, sizeof(Delay_4_ctx_type));
   // ctx->client_data = cdata;
   Delay_4_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Delay_4_ctx
void Delay_4_step(_real x,_real *z,Delay_4_ctx_type* ctx){   _real _split_24;
   _real _split_23;

  Lustre_pre_get(&_split_24,&ctx->Lustre_pre_ctx_tab[0]); 
  Delay_3_step(x,&_split_23,&ctx->Delay_3_ctx_tab[0]); 
  Lustre_pre_set(_split_23,&ctx->Lustre_pre_ctx_tab[0]); 
  Lustre_arrow_step(x,_split_24,z,&ctx->Lustre_arrow_ctx_tab[0]); 

} // End of Delay_4_step

// Memory initialisation for Delay_5_ctx
void Delay_5_ctx_reset(Delay_5_ctx_type* ctx){
  int _i;

    Lustre_pre_ctx_reset(&ctx->Lustre_pre_ctx_tab[0]);
    Lustre_arrow_ctx_reset(&ctx->Lustre_arrow_ctx_tab[0]);
    Delay_4_ctx_reset(&ctx->Delay_4_ctx_tab[0]);
}
// Memory allocation for Delay_5_ctx
Delay_5_ctx_type* Delay_5_ctx_new_ctx(){

   Delay_5_ctx_type* ctx = (Delay_5_ctx_type*)calloc(1, sizeof(Delay_5_ctx_type));
   // ctx->client_data = cdata;
   Delay_5_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Delay_5_ctx
void Delay_5_step(_real x,_real *z,Delay_5_ctx_type* ctx){   _real _split_26;
   _real _split_25;

  Lustre_pre_get(&_split_26,&ctx->Lustre_pre_ctx_tab[0]); 
  Delay_4_step(x,&_split_25,&ctx->Delay_4_ctx_tab[0]); 
  Lustre_pre_set(_split_25,&ctx->Lustre_pre_ctx_tab[0]); 
  Lustre_arrow_step(x,_split_26,z,&ctx->Lustre_arrow_ctx_tab[0]); 

} // End of Delay_5_step

// Memory initialisation for Delay_6_ctx
void Delay_6_ctx_reset(Delay_6_ctx_type* ctx){
  int _i;

    Lustre_pre_ctx_reset(&ctx->Lustre_pre_ctx_tab[0]);
    Lustre_arrow_ctx_reset(&ctx->Lustre_arrow_ctx_tab[0]);
    Delay_5_ctx_reset(&ctx->Delay_5_ctx_tab[0]);
}
// Memory allocation for Delay_6_ctx
Delay_6_ctx_type* Delay_6_ctx_new_ctx(){

   Delay_6_ctx_type* ctx = (Delay_6_ctx_type*)calloc(1, sizeof(Delay_6_ctx_type));
   // ctx->client_data = cdata;
   Delay_6_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Delay_6_ctx
void Delay_6_step(_real x,_real *z,Delay_6_ctx_type* ctx){   _real _split_28;
   _real _split_27;

  Lustre_pre_get(&_split_28,&ctx->Lustre_pre_ctx_tab[0]); 
  Delay_5_step(x,&_split_27,&ctx->Delay_5_ctx_tab[0]); 
  Lustre_pre_set(_split_27,&ctx->Lustre_pre_ctx_tab[0]); 
  Lustre_arrow_step(x,_split_28,z,&ctx->Lustre_arrow_ctx_tab[0]); 

} // End of Delay_6_step

// Memory initialisation for Delay_7_ctx
void Delay_7_ctx_reset(Delay_7_ctx_type* ctx){
  int _i;

    Lustre_pre_ctx_reset(&ctx->Lustre_pre_ctx_tab[0]);
    Lustre_arrow_ctx_reset(&ctx->Lustre_arrow_ctx_tab[0]);
    Delay_6_ctx_reset(&ctx->Delay_6_ctx_tab[0]);
}
// Memory allocation for Delay_7_ctx
Delay_7_ctx_type* Delay_7_ctx_new_ctx(){

   Delay_7_ctx_type* ctx = (Delay_7_ctx_type*)calloc(1, sizeof(Delay_7_ctx_type));
   // ctx->client_data = cdata;
   Delay_7_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Delay_7_ctx
void Delay_7_step(_real x,_real *z,Delay_7_ctx_type* ctx){   _real _split_30;
   _real _split_29;

  Lustre_pre_get(&_split_30,&ctx->Lustre_pre_ctx_tab[0]); 
  Delay_6_step(x,&_split_29,&ctx->Delay_6_ctx_tab[0]); 
  Lustre_pre_set(_split_29,&ctx->Lustre_pre_ctx_tab[0]); 
  Lustre_arrow_step(x,_split_30,z,&ctx->Lustre_arrow_ctx_tab[0]); 

} // End of Delay_7_step

// Memory initialisation for Delay_8_ctx
void Delay_8_ctx_reset(Delay_8_ctx_type* ctx){
  int _i;

    Lustre_pre_ctx_reset(&ctx->Lustre_pre_ctx_tab[0]);
    Lustre_arrow_ctx_reset(&ctx->Lustre_arrow_ctx_tab[0]);
    Delay_7_ctx_reset(&ctx->Delay_7_ctx_tab[0]);
}
// Memory allocation for Delay_8_ctx
Delay_8_ctx_type* Delay_8_ctx_new_ctx(){

   Delay_8_ctx_type* ctx = (Delay_8_ctx_type*)calloc(1, sizeof(Delay_8_ctx_type));
   // ctx->client_data = cdata;
   Delay_8_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Delay_8_ctx
void Delay_8_step(_real x,_real *z,Delay_8_ctx_type* ctx){   _real _split_32;
   _real _split_31;

  Lustre_pre_get(&_split_32,&ctx->Lustre_pre_ctx_tab[0]); 
  Delay_7_step(x,&_split_31,&ctx->Delay_7_ctx_tab[0]); 
  Lustre_pre_set(_split_31,&ctx->Lustre_pre_ctx_tab[0]); 
  Lustre_arrow_step(x,_split_32,z,&ctx->Lustre_arrow_ctx_tab[0]); 

} // End of Delay_8_step

// Memory initialisation for Delay_9_ctx
void Delay_9_ctx_reset(Delay_9_ctx_type* ctx){
  int _i;

    Lustre_pre_ctx_reset(&ctx->Lustre_pre_ctx_tab[0]);
    Lustre_arrow_ctx_reset(&ctx->Lustre_arrow_ctx_tab[0]);
    Delay_8_ctx_reset(&ctx->Delay_8_ctx_tab[0]);
}
// Memory allocation for Delay_9_ctx
Delay_9_ctx_type* Delay_9_ctx_new_ctx(){

   Delay_9_ctx_type* ctx = (Delay_9_ctx_type*)calloc(1, sizeof(Delay_9_ctx_type));
   // ctx->client_data = cdata;
   Delay_9_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Delay_9_ctx
void Delay_9_step(_real x,_real *z,Delay_9_ctx_type* ctx){   _real _split_34;
   _real _split_33;

  Lustre_pre_get(&_split_34,&ctx->Lustre_pre_ctx_tab[0]); 
  Delay_8_step(x,&_split_33,&ctx->Delay_8_ctx_tab[0]); 
  Lustre_pre_set(_split_33,&ctx->Lustre_pre_ctx_tab[0]); 
  Lustre_arrow_step(x,_split_34,z,&ctx->Lustre_arrow_ctx_tab[0]); 

} // End of Delay_9_step

// Step function(s) for Delay_m1_ctx
void Delay_m1_step(_real x,_real *z){

  *z = x;

} // End of Delay_m1_step

// Memory initialisation for Lustre_arrow_ctx
void Lustre_arrow_ctx_reset(Lustre_arrow_ctx_type* ctx){  ctx->_memory = _true;
}
// Memory allocation for Lustre_arrow_ctx
Lustre_arrow_ctx_type* Lustre_arrow_ctx_new_ctx(){

   Lustre_arrow_ctx_type* ctx = (Lustre_arrow_ctx_type*)calloc(1, sizeof(Lustre_arrow_ctx_type));
   // ctx->client_data = cdata;
   Lustre_arrow_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Lustre_arrow_ctx
void Lustre_arrow_step(_real i1,_real i2,_real *out,Lustre_arrow_ctx_type* ctx){  *out = ((ctx->_memory)? i1 : i2);
  ctx->_memory = _false;

} // End of Lustre_arrow_step

// Memory initialisation for Lustre_pre_ctx
void Lustre_pre_ctx_reset(Lustre_pre_ctx_type* ctx){
}
// Memory allocation for Lustre_pre_ctx
Lustre_pre_ctx_type* Lustre_pre_ctx_new_ctx(){

   Lustre_pre_ctx_type* ctx = (Lustre_pre_ctx_type*)calloc(1, sizeof(Lustre_pre_ctx_type));
   // ctx->client_data = cdata;
   Lustre_pre_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Lustre_pre_ctx
void Lustre_pre_get(_real *out,Lustre_pre_ctx_type* ctx){
  *out = ctx->_memory;

} // End of Lustre_pre_get

void Lustre_pre_set(_real i1,Lustre_pre_ctx_type* ctx){
  ctx->_memory = i1;

} // End of Lustre_pre_set

// Memory initialisation for Once_Interval_0_15_ctx
void Once_Interval_0_15_ctx_reset(Once_Interval_0_15_ctx_type* ctx){
  int _i;

    Since_Interval_0_15_ctx_reset(&ctx->Since_Interval_0_15_ctx_tab[0]);
}
// Memory allocation for Once_Interval_0_15_ctx
Once_Interval_0_15_ctx_type* Once_Interval_0_15_ctx_new_ctx(){

   Once_Interval_0_15_ctx_type* ctx = (Once_Interval_0_15_ctx_type*)calloc(1, sizeof(Once_Interval_0_15_ctx_type));
   // ctx->client_data = cdata;
   Once_Interval_0_15_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Once_Interval_0_15_ctx
void Once_Interval_0_15_step(_real x,_real *z,Once_Interval_0_15_ctx_type* ctx){
  Since_Interval_0_15_step(x,9999.0,z,&ctx->Since_Interval_0_15_ctx_tab[0]); 

} // End of Once_Interval_0_15_step

// Memory initialisation for Since_Interval_0_15_ctx
void Since_Interval_0_15_ctx_reset(Since_Interval_0_15_ctx_type* ctx){
  int _i;

    Since_Recurse_0_15_0_ctx_reset(&ctx->Since_Recurse_0_15_0_ctx_tab[0]);
}
// Memory allocation for Since_Interval_0_15_ctx
Since_Interval_0_15_ctx_type* Since_Interval_0_15_ctx_new_ctx(){

   Since_Interval_0_15_ctx_type* ctx = (Since_Interval_0_15_ctx_type*)calloc(1, sizeof(Since_Interval_0_15_ctx_type));
   // ctx->client_data = cdata;
   Since_Interval_0_15_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Since_Interval_0_15_ctx
void Since_Interval_0_15_step(_real x,_real y,_real *z,Since_Interval_0_15_ctx_type* ctx){   _boolean _split_38;
   _boolean _split_39;

  _split_39 = 15 > 0;
  _split_38 = 0 >= 0;
  Since_Recurse_0_15_0_step(x,y,z,&ctx->Since_Recurse_0_15_0_ctx_tab[0]); 

} // End of Since_Interval_0_15_step

// Memory initialisation for Since_Interval_1_1_ctx
void Since_Interval_1_1_ctx_reset(Since_Interval_1_1_ctx_type* ctx){
  int _i;

    Since_Recurse_1_1_0_ctx_reset(&ctx->Since_Recurse_1_1_0_ctx_tab[0]);
}
// Memory allocation for Since_Interval_1_1_ctx
Since_Interval_1_1_ctx_type* Since_Interval_1_1_ctx_new_ctx(){

   Since_Interval_1_1_ctx_type* ctx = (Since_Interval_1_1_ctx_type*)calloc(1, sizeof(Since_Interval_1_1_ctx_type));
   // ctx->client_data = cdata;
   Since_Interval_1_1_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Since_Interval_1_1_ctx
void Since_Interval_1_1_step(_real x,_real y,_real *z,Since_Interval_1_1_ctx_type* ctx){   _boolean _split_40;
   _boolean _split_41;

  _split_41 = 1 > 0;
  _split_40 = 1 >= 0;
  Since_Recurse_1_1_0_step(x,y,z,&ctx->Since_Recurse_1_1_0_ctx_tab[0]); 

} // End of Since_Interval_1_1_step

// Memory initialisation for Since_Recurse_0_15_0_ctx
void Since_Recurse_0_15_0_ctx_reset(Since_Recurse_0_15_0_ctx_type* ctx){
  int _i;

    Since_Recurse_0_15_1_ctx_reset(&ctx->Since_Recurse_0_15_1_ctx_tab[0]);
}
// Memory allocation for Since_Recurse_0_15_0_ctx
Since_Recurse_0_15_0_ctx_type* Since_Recurse_0_15_0_ctx_new_ctx(){

   Since_Recurse_0_15_0_ctx_type* ctx = (Since_Recurse_0_15_0_ctx_type*)calloc(1, sizeof(Since_Recurse_0_15_0_ctx_type));
   // ctx->client_data = cdata;
   Since_Recurse_0_15_0_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Since_Recurse_0_15_0_ctx
void Since_Recurse_0_15_0_step(_real x,_real y,_real *z,Since_Recurse_0_15_0_ctx_type* ctx){   _real _split_42;
   _real x_n;
   _real min_m;
   _real min_n;
   _integer _split_43;
   _boolean _split_44;

  _split_43 = 15 - 0;
  _split_44 = _split_43 >= 0;
  Delay_0_step(x,&x_n); 
  Sliding_Min_m1_step(y,&min_m); 
  robustSpec_v6_Min_2_step(x_n,min_m,&min_n); 
  Since_Recurse_0_15_1_step(x,y,&_split_42,&ctx->Since_Recurse_0_15_1_ctx_tab[0]); 
  robustSpec_v6_Max_2_step(min_n,_split_42,z); 

} // End of Since_Recurse_0_15_0_step

// Memory initialisation for Since_Recurse_0_15_1_ctx
void Since_Recurse_0_15_1_ctx_reset(Since_Recurse_0_15_1_ctx_type* ctx){
  int _i;

    Since_Recurse_0_15_2_ctx_reset(&ctx->Since_Recurse_0_15_2_ctx_tab[0]);
    Delay_1_ctx_reset(&ctx->Delay_1_ctx_tab[0]);
}
// Memory allocation for Since_Recurse_0_15_1_ctx
Since_Recurse_0_15_1_ctx_type* Since_Recurse_0_15_1_ctx_new_ctx(){

   Since_Recurse_0_15_1_ctx_type* ctx = (Since_Recurse_0_15_1_ctx_type*)calloc(1, sizeof(Since_Recurse_0_15_1_ctx_type));
   // ctx->client_data = cdata;
   Since_Recurse_0_15_1_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Since_Recurse_0_15_1_ctx
void Since_Recurse_0_15_1_step(_real x,_real y,_real *z,Since_Recurse_0_15_1_ctx_type* ctx){   _real _split_45;
   _real x_n;
   _real min_m;
   _real min_n;
   _integer _split_46;
   _boolean _split_47;

  _split_46 = 15 - 0;
  _split_47 = _split_46 >= 0;
  Delay_1_step(x,&x_n,&ctx->Delay_1_ctx_tab[0]); 
  Sliding_Min_0_step(y,&min_m); 
  robustSpec_v6_Min_2_step(x_n,min_m,&min_n); 
  Since_Recurse_0_15_2_step(x,y,&_split_45,&ctx->Since_Recurse_0_15_2_ctx_tab[0]); 
  robustSpec_v6_Max_2_step(min_n,_split_45,z); 

} // End of Since_Recurse_0_15_1_step

// Memory initialisation for Since_Recurse_0_15_10_ctx
void Since_Recurse_0_15_10_ctx_reset(Since_Recurse_0_15_10_ctx_type* ctx){
  int _i;

    Sliding_Min_9_ctx_reset(&ctx->Sliding_Min_9_ctx_tab[0]);
    Since_Recurse_0_15_11_ctx_reset(&ctx->Since_Recurse_0_15_11_ctx_tab[0]);
    Delay_10_ctx_reset(&ctx->Delay_10_ctx_tab[0]);
}
// Memory allocation for Since_Recurse_0_15_10_ctx
Since_Recurse_0_15_10_ctx_type* Since_Recurse_0_15_10_ctx_new_ctx(){

   Since_Recurse_0_15_10_ctx_type* ctx = (Since_Recurse_0_15_10_ctx_type*)calloc(1, sizeof(Since_Recurse_0_15_10_ctx_type));
   // ctx->client_data = cdata;
   Since_Recurse_0_15_10_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Since_Recurse_0_15_10_ctx
void Since_Recurse_0_15_10_step(_real x,_real y,_real *z,Since_Recurse_0_15_10_ctx_type* ctx){   _real _split_48;
   _real x_n;
   _real min_m;
   _real min_n;
   _integer _split_49;
   _boolean _split_50;

  _split_49 = 15 - 0;
  _split_50 = _split_49 >= 0;
  Delay_10_step(x,&x_n,&ctx->Delay_10_ctx_tab[0]); 
  Sliding_Min_9_step(y,&min_m,&ctx->Sliding_Min_9_ctx_tab[0]); 
  robustSpec_v6_Min_2_step(x_n,min_m,&min_n); 
  Since_Recurse_0_15_11_step(x,y,&_split_48,&ctx->Since_Recurse_0_15_11_ctx_tab[0]); 
  robustSpec_v6_Max_2_step(min_n,_split_48,z); 

} // End of Since_Recurse_0_15_10_step

// Memory initialisation for Since_Recurse_0_15_11_ctx
void Since_Recurse_0_15_11_ctx_reset(Since_Recurse_0_15_11_ctx_type* ctx){
  int _i;

    Sliding_Min_10_ctx_reset(&ctx->Sliding_Min_10_ctx_tab[0]);
    Since_Recurse_0_15_12_ctx_reset(&ctx->Since_Recurse_0_15_12_ctx_tab[0]);
    Delay_11_ctx_reset(&ctx->Delay_11_ctx_tab[0]);
}
// Memory allocation for Since_Recurse_0_15_11_ctx
Since_Recurse_0_15_11_ctx_type* Since_Recurse_0_15_11_ctx_new_ctx(){

   Since_Recurse_0_15_11_ctx_type* ctx = (Since_Recurse_0_15_11_ctx_type*)calloc(1, sizeof(Since_Recurse_0_15_11_ctx_type));
   // ctx->client_data = cdata;
   Since_Recurse_0_15_11_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Since_Recurse_0_15_11_ctx
void Since_Recurse_0_15_11_step(_real x,_real y,_real *z,Since_Recurse_0_15_11_ctx_type* ctx){   _real _split_51;
   _real x_n;
   _real min_m;
   _real min_n;
   _integer _split_52;
   _boolean _split_53;

  _split_52 = 15 - 0;
  _split_53 = _split_52 >= 0;
  Delay_11_step(x,&x_n,&ctx->Delay_11_ctx_tab[0]); 
  Sliding_Min_10_step(y,&min_m,&ctx->Sliding_Min_10_ctx_tab[0]); 
  robustSpec_v6_Min_2_step(x_n,min_m,&min_n); 
  Since_Recurse_0_15_12_step(x,y,&_split_51,&ctx->Since_Recurse_0_15_12_ctx_tab[0]); 
  robustSpec_v6_Max_2_step(min_n,_split_51,z); 

} // End of Since_Recurse_0_15_11_step

// Memory initialisation for Since_Recurse_0_15_12_ctx
void Since_Recurse_0_15_12_ctx_reset(Since_Recurse_0_15_12_ctx_type* ctx){
  int _i;

    Sliding_Min_11_ctx_reset(&ctx->Sliding_Min_11_ctx_tab[0]);
    Since_Recurse_0_15_13_ctx_reset(&ctx->Since_Recurse_0_15_13_ctx_tab[0]);
    Delay_12_ctx_reset(&ctx->Delay_12_ctx_tab[0]);
}
// Memory allocation for Since_Recurse_0_15_12_ctx
Since_Recurse_0_15_12_ctx_type* Since_Recurse_0_15_12_ctx_new_ctx(){

   Since_Recurse_0_15_12_ctx_type* ctx = (Since_Recurse_0_15_12_ctx_type*)calloc(1, sizeof(Since_Recurse_0_15_12_ctx_type));
   // ctx->client_data = cdata;
   Since_Recurse_0_15_12_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Since_Recurse_0_15_12_ctx
void Since_Recurse_0_15_12_step(_real x,_real y,_real *z,Since_Recurse_0_15_12_ctx_type* ctx){   _real _split_54;
   _real x_n;
   _real min_m;
   _real min_n;
   _integer _split_55;
   _boolean _split_56;

  _split_55 = 15 - 0;
  _split_56 = _split_55 >= 0;
  Delay_12_step(x,&x_n,&ctx->Delay_12_ctx_tab[0]); 
  Sliding_Min_11_step(y,&min_m,&ctx->Sliding_Min_11_ctx_tab[0]); 
  robustSpec_v6_Min_2_step(x_n,min_m,&min_n); 
  Since_Recurse_0_15_13_step(x,y,&_split_54,&ctx->Since_Recurse_0_15_13_ctx_tab[0]); 
  robustSpec_v6_Max_2_step(min_n,_split_54,z); 

} // End of Since_Recurse_0_15_12_step

// Memory initialisation for Since_Recurse_0_15_13_ctx
void Since_Recurse_0_15_13_ctx_reset(Since_Recurse_0_15_13_ctx_type* ctx){
  int _i;

    Sliding_Min_12_ctx_reset(&ctx->Sliding_Min_12_ctx_tab[0]);
    Since_Recurse_0_15_14_ctx_reset(&ctx->Since_Recurse_0_15_14_ctx_tab[0]);
    Delay_13_ctx_reset(&ctx->Delay_13_ctx_tab[0]);
}
// Memory allocation for Since_Recurse_0_15_13_ctx
Since_Recurse_0_15_13_ctx_type* Since_Recurse_0_15_13_ctx_new_ctx(){

   Since_Recurse_0_15_13_ctx_type* ctx = (Since_Recurse_0_15_13_ctx_type*)calloc(1, sizeof(Since_Recurse_0_15_13_ctx_type));
   // ctx->client_data = cdata;
   Since_Recurse_0_15_13_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Since_Recurse_0_15_13_ctx
void Since_Recurse_0_15_13_step(_real x,_real y,_real *z,Since_Recurse_0_15_13_ctx_type* ctx){   _real _split_57;
   _real x_n;
   _real min_m;
   _real min_n;
   _integer _split_58;
   _boolean _split_59;

  _split_58 = 15 - 0;
  _split_59 = _split_58 >= 0;
  Delay_13_step(x,&x_n,&ctx->Delay_13_ctx_tab[0]); 
  Sliding_Min_12_step(y,&min_m,&ctx->Sliding_Min_12_ctx_tab[0]); 
  robustSpec_v6_Min_2_step(x_n,min_m,&min_n); 
  Since_Recurse_0_15_14_step(x,y,&_split_57,&ctx->Since_Recurse_0_15_14_ctx_tab[0]); 
  robustSpec_v6_Max_2_step(min_n,_split_57,z); 

} // End of Since_Recurse_0_15_13_step

// Memory initialisation for Since_Recurse_0_15_14_ctx
void Since_Recurse_0_15_14_ctx_reset(Since_Recurse_0_15_14_ctx_type* ctx){
  int _i;

    Sliding_Min_13_ctx_reset(&ctx->Sliding_Min_13_ctx_tab[0]);
    Since_Recurse_0_15_15_ctx_reset(&ctx->Since_Recurse_0_15_15_ctx_tab[0]);
    Delay_14_ctx_reset(&ctx->Delay_14_ctx_tab[0]);
}
// Memory allocation for Since_Recurse_0_15_14_ctx
Since_Recurse_0_15_14_ctx_type* Since_Recurse_0_15_14_ctx_new_ctx(){

   Since_Recurse_0_15_14_ctx_type* ctx = (Since_Recurse_0_15_14_ctx_type*)calloc(1, sizeof(Since_Recurse_0_15_14_ctx_type));
   // ctx->client_data = cdata;
   Since_Recurse_0_15_14_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Since_Recurse_0_15_14_ctx
void Since_Recurse_0_15_14_step(_real x,_real y,_real *z,Since_Recurse_0_15_14_ctx_type* ctx){   _real _split_60;
   _real x_n;
   _real min_m;
   _real min_n;
   _integer _split_61;
   _boolean _split_62;

  _split_61 = 15 - 0;
  _split_62 = _split_61 >= 0;
  Delay_14_step(x,&x_n,&ctx->Delay_14_ctx_tab[0]); 
  Sliding_Min_13_step(y,&min_m,&ctx->Sliding_Min_13_ctx_tab[0]); 
  robustSpec_v6_Min_2_step(x_n,min_m,&min_n); 
  Since_Recurse_0_15_15_step(x,y,&_split_60,&ctx->Since_Recurse_0_15_15_ctx_tab[0]); 
  robustSpec_v6_Max_2_step(min_n,_split_60,z); 

} // End of Since_Recurse_0_15_14_step

// Memory initialisation for Since_Recurse_0_15_15_ctx
void Since_Recurse_0_15_15_ctx_reset(Since_Recurse_0_15_15_ctx_type* ctx){
  int _i;

    Sliding_Min_14_ctx_reset(&ctx->Sliding_Min_14_ctx_tab[0]);
    Delay_15_ctx_reset(&ctx->Delay_15_ctx_tab[0]);
}
// Memory allocation for Since_Recurse_0_15_15_ctx
Since_Recurse_0_15_15_ctx_type* Since_Recurse_0_15_15_ctx_new_ctx(){

   Since_Recurse_0_15_15_ctx_type* ctx = (Since_Recurse_0_15_15_ctx_type*)calloc(1, sizeof(Since_Recurse_0_15_15_ctx_type));
   // ctx->client_data = cdata;
   Since_Recurse_0_15_15_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Since_Recurse_0_15_15_ctx
void Since_Recurse_0_15_15_step(_real x,_real y,_real *z,Since_Recurse_0_15_15_ctx_type* ctx){   _real x_n;
   _real min_m;
   _real min_n;
   _integer _split_63;
   _boolean _split_64;

  _split_63 = 15 - 0;
  _split_64 = _split_63 >= 0;
  Delay_15_step(x,&x_n,&ctx->Delay_15_ctx_tab[0]); 
  Sliding_Min_14_step(y,&min_m,&ctx->Sliding_Min_14_ctx_tab[0]); 
  robustSpec_v6_Min_2_step(x_n,min_m,&min_n); 
  *z = min_n;

} // End of Since_Recurse_0_15_15_step

// Memory initialisation for Since_Recurse_0_15_2_ctx
void Since_Recurse_0_15_2_ctx_reset(Since_Recurse_0_15_2_ctx_type* ctx){
  int _i;

    Sliding_Min_1_ctx_reset(&ctx->Sliding_Min_1_ctx_tab[0]);
    Since_Recurse_0_15_3_ctx_reset(&ctx->Since_Recurse_0_15_3_ctx_tab[0]);
    Delay_2_ctx_reset(&ctx->Delay_2_ctx_tab[0]);
}
// Memory allocation for Since_Recurse_0_15_2_ctx
Since_Recurse_0_15_2_ctx_type* Since_Recurse_0_15_2_ctx_new_ctx(){

   Since_Recurse_0_15_2_ctx_type* ctx = (Since_Recurse_0_15_2_ctx_type*)calloc(1, sizeof(Since_Recurse_0_15_2_ctx_type));
   // ctx->client_data = cdata;
   Since_Recurse_0_15_2_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Since_Recurse_0_15_2_ctx
void Since_Recurse_0_15_2_step(_real x,_real y,_real *z,Since_Recurse_0_15_2_ctx_type* ctx){   _real _split_65;
   _real x_n;
   _real min_m;
   _real min_n;
   _integer _split_66;
   _boolean _split_67;

  _split_66 = 15 - 0;
  _split_67 = _split_66 >= 0;
  Delay_2_step(x,&x_n,&ctx->Delay_2_ctx_tab[0]); 
  Sliding_Min_1_step(y,&min_m,&ctx->Sliding_Min_1_ctx_tab[0]); 
  robustSpec_v6_Min_2_step(x_n,min_m,&min_n); 
  Since_Recurse_0_15_3_step(x,y,&_split_65,&ctx->Since_Recurse_0_15_3_ctx_tab[0]); 
  robustSpec_v6_Max_2_step(min_n,_split_65,z); 

} // End of Since_Recurse_0_15_2_step

// Memory initialisation for Since_Recurse_0_15_3_ctx
void Since_Recurse_0_15_3_ctx_reset(Since_Recurse_0_15_3_ctx_type* ctx){
  int _i;

    Sliding_Min_2_ctx_reset(&ctx->Sliding_Min_2_ctx_tab[0]);
    Since_Recurse_0_15_4_ctx_reset(&ctx->Since_Recurse_0_15_4_ctx_tab[0]);
    Delay_3_ctx_reset(&ctx->Delay_3_ctx_tab[0]);
}
// Memory allocation for Since_Recurse_0_15_3_ctx
Since_Recurse_0_15_3_ctx_type* Since_Recurse_0_15_3_ctx_new_ctx(){

   Since_Recurse_0_15_3_ctx_type* ctx = (Since_Recurse_0_15_3_ctx_type*)calloc(1, sizeof(Since_Recurse_0_15_3_ctx_type));
   // ctx->client_data = cdata;
   Since_Recurse_0_15_3_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Since_Recurse_0_15_3_ctx
void Since_Recurse_0_15_3_step(_real x,_real y,_real *z,Since_Recurse_0_15_3_ctx_type* ctx){   _real _split_68;
   _real x_n;
   _real min_m;
   _real min_n;
   _integer _split_69;
   _boolean _split_70;

  _split_69 = 15 - 0;
  _split_70 = _split_69 >= 0;
  Delay_3_step(x,&x_n,&ctx->Delay_3_ctx_tab[0]); 
  Sliding_Min_2_step(y,&min_m,&ctx->Sliding_Min_2_ctx_tab[0]); 
  robustSpec_v6_Min_2_step(x_n,min_m,&min_n); 
  Since_Recurse_0_15_4_step(x,y,&_split_68,&ctx->Since_Recurse_0_15_4_ctx_tab[0]); 
  robustSpec_v6_Max_2_step(min_n,_split_68,z); 

} // End of Since_Recurse_0_15_3_step

// Memory initialisation for Since_Recurse_0_15_4_ctx
void Since_Recurse_0_15_4_ctx_reset(Since_Recurse_0_15_4_ctx_type* ctx){
  int _i;

    Sliding_Min_3_ctx_reset(&ctx->Sliding_Min_3_ctx_tab[0]);
    Since_Recurse_0_15_5_ctx_reset(&ctx->Since_Recurse_0_15_5_ctx_tab[0]);
    Delay_4_ctx_reset(&ctx->Delay_4_ctx_tab[0]);
}
// Memory allocation for Since_Recurse_0_15_4_ctx
Since_Recurse_0_15_4_ctx_type* Since_Recurse_0_15_4_ctx_new_ctx(){

   Since_Recurse_0_15_4_ctx_type* ctx = (Since_Recurse_0_15_4_ctx_type*)calloc(1, sizeof(Since_Recurse_0_15_4_ctx_type));
   // ctx->client_data = cdata;
   Since_Recurse_0_15_4_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Since_Recurse_0_15_4_ctx
void Since_Recurse_0_15_4_step(_real x,_real y,_real *z,Since_Recurse_0_15_4_ctx_type* ctx){   _real _split_71;
   _real x_n;
   _real min_m;
   _real min_n;
   _integer _split_72;
   _boolean _split_73;

  _split_72 = 15 - 0;
  _split_73 = _split_72 >= 0;
  Delay_4_step(x,&x_n,&ctx->Delay_4_ctx_tab[0]); 
  Sliding_Min_3_step(y,&min_m,&ctx->Sliding_Min_3_ctx_tab[0]); 
  robustSpec_v6_Min_2_step(x_n,min_m,&min_n); 
  Since_Recurse_0_15_5_step(x,y,&_split_71,&ctx->Since_Recurse_0_15_5_ctx_tab[0]); 
  robustSpec_v6_Max_2_step(min_n,_split_71,z); 

} // End of Since_Recurse_0_15_4_step

// Memory initialisation for Since_Recurse_0_15_5_ctx
void Since_Recurse_0_15_5_ctx_reset(Since_Recurse_0_15_5_ctx_type* ctx){
  int _i;

    Sliding_Min_4_ctx_reset(&ctx->Sliding_Min_4_ctx_tab[0]);
    Since_Recurse_0_15_6_ctx_reset(&ctx->Since_Recurse_0_15_6_ctx_tab[0]);
    Delay_5_ctx_reset(&ctx->Delay_5_ctx_tab[0]);
}
// Memory allocation for Since_Recurse_0_15_5_ctx
Since_Recurse_0_15_5_ctx_type* Since_Recurse_0_15_5_ctx_new_ctx(){

   Since_Recurse_0_15_5_ctx_type* ctx = (Since_Recurse_0_15_5_ctx_type*)calloc(1, sizeof(Since_Recurse_0_15_5_ctx_type));
   // ctx->client_data = cdata;
   Since_Recurse_0_15_5_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Since_Recurse_0_15_5_ctx
void Since_Recurse_0_15_5_step(_real x,_real y,_real *z,Since_Recurse_0_15_5_ctx_type* ctx){   _real _split_74;
   _real x_n;
   _real min_m;
   _real min_n;
   _integer _split_75;
   _boolean _split_76;

  _split_75 = 15 - 0;
  _split_76 = _split_75 >= 0;
  Delay_5_step(x,&x_n,&ctx->Delay_5_ctx_tab[0]); 
  Sliding_Min_4_step(y,&min_m,&ctx->Sliding_Min_4_ctx_tab[0]); 
  robustSpec_v6_Min_2_step(x_n,min_m,&min_n); 
  Since_Recurse_0_15_6_step(x,y,&_split_74,&ctx->Since_Recurse_0_15_6_ctx_tab[0]); 
  robustSpec_v6_Max_2_step(min_n,_split_74,z); 

} // End of Since_Recurse_0_15_5_step

// Memory initialisation for Since_Recurse_0_15_6_ctx
void Since_Recurse_0_15_6_ctx_reset(Since_Recurse_0_15_6_ctx_type* ctx){
  int _i;

    Sliding_Min_5_ctx_reset(&ctx->Sliding_Min_5_ctx_tab[0]);
    Since_Recurse_0_15_7_ctx_reset(&ctx->Since_Recurse_0_15_7_ctx_tab[0]);
    Delay_6_ctx_reset(&ctx->Delay_6_ctx_tab[0]);
}
// Memory allocation for Since_Recurse_0_15_6_ctx
Since_Recurse_0_15_6_ctx_type* Since_Recurse_0_15_6_ctx_new_ctx(){

   Since_Recurse_0_15_6_ctx_type* ctx = (Since_Recurse_0_15_6_ctx_type*)calloc(1, sizeof(Since_Recurse_0_15_6_ctx_type));
   // ctx->client_data = cdata;
   Since_Recurse_0_15_6_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Since_Recurse_0_15_6_ctx
void Since_Recurse_0_15_6_step(_real x,_real y,_real *z,Since_Recurse_0_15_6_ctx_type* ctx){   _real _split_77;
   _real x_n;
   _real min_m;
   _real min_n;
   _integer _split_78;
   _boolean _split_79;

  _split_78 = 15 - 0;
  _split_79 = _split_78 >= 0;
  Delay_6_step(x,&x_n,&ctx->Delay_6_ctx_tab[0]); 
  Sliding_Min_5_step(y,&min_m,&ctx->Sliding_Min_5_ctx_tab[0]); 
  robustSpec_v6_Min_2_step(x_n,min_m,&min_n); 
  Since_Recurse_0_15_7_step(x,y,&_split_77,&ctx->Since_Recurse_0_15_7_ctx_tab[0]); 
  robustSpec_v6_Max_2_step(min_n,_split_77,z); 

} // End of Since_Recurse_0_15_6_step

// Memory initialisation for Since_Recurse_0_15_7_ctx
void Since_Recurse_0_15_7_ctx_reset(Since_Recurse_0_15_7_ctx_type* ctx){
  int _i;

    Sliding_Min_6_ctx_reset(&ctx->Sliding_Min_6_ctx_tab[0]);
    Since_Recurse_0_15_8_ctx_reset(&ctx->Since_Recurse_0_15_8_ctx_tab[0]);
    Delay_7_ctx_reset(&ctx->Delay_7_ctx_tab[0]);
}
// Memory allocation for Since_Recurse_0_15_7_ctx
Since_Recurse_0_15_7_ctx_type* Since_Recurse_0_15_7_ctx_new_ctx(){

   Since_Recurse_0_15_7_ctx_type* ctx = (Since_Recurse_0_15_7_ctx_type*)calloc(1, sizeof(Since_Recurse_0_15_7_ctx_type));
   // ctx->client_data = cdata;
   Since_Recurse_0_15_7_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Since_Recurse_0_15_7_ctx
void Since_Recurse_0_15_7_step(_real x,_real y,_real *z,Since_Recurse_0_15_7_ctx_type* ctx){   _real _split_80;
   _real x_n;
   _real min_m;
   _real min_n;
   _integer _split_81;
   _boolean _split_82;

  _split_81 = 15 - 0;
  _split_82 = _split_81 >= 0;
  Delay_7_step(x,&x_n,&ctx->Delay_7_ctx_tab[0]); 
  Sliding_Min_6_step(y,&min_m,&ctx->Sliding_Min_6_ctx_tab[0]); 
  robustSpec_v6_Min_2_step(x_n,min_m,&min_n); 
  Since_Recurse_0_15_8_step(x,y,&_split_80,&ctx->Since_Recurse_0_15_8_ctx_tab[0]); 
  robustSpec_v6_Max_2_step(min_n,_split_80,z); 

} // End of Since_Recurse_0_15_7_step

// Memory initialisation for Since_Recurse_0_15_8_ctx
void Since_Recurse_0_15_8_ctx_reset(Since_Recurse_0_15_8_ctx_type* ctx){
  int _i;

    Sliding_Min_7_ctx_reset(&ctx->Sliding_Min_7_ctx_tab[0]);
    Since_Recurse_0_15_9_ctx_reset(&ctx->Since_Recurse_0_15_9_ctx_tab[0]);
    Delay_8_ctx_reset(&ctx->Delay_8_ctx_tab[0]);
}
// Memory allocation for Since_Recurse_0_15_8_ctx
Since_Recurse_0_15_8_ctx_type* Since_Recurse_0_15_8_ctx_new_ctx(){

   Since_Recurse_0_15_8_ctx_type* ctx = (Since_Recurse_0_15_8_ctx_type*)calloc(1, sizeof(Since_Recurse_0_15_8_ctx_type));
   // ctx->client_data = cdata;
   Since_Recurse_0_15_8_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Since_Recurse_0_15_8_ctx
void Since_Recurse_0_15_8_step(_real x,_real y,_real *z,Since_Recurse_0_15_8_ctx_type* ctx){   _real _split_83;
   _real x_n;
   _real min_m;
   _real min_n;
   _integer _split_84;
   _boolean _split_85;

  _split_84 = 15 - 0;
  _split_85 = _split_84 >= 0;
  Delay_8_step(x,&x_n,&ctx->Delay_8_ctx_tab[0]); 
  Sliding_Min_7_step(y,&min_m,&ctx->Sliding_Min_7_ctx_tab[0]); 
  robustSpec_v6_Min_2_step(x_n,min_m,&min_n); 
  Since_Recurse_0_15_9_step(x,y,&_split_83,&ctx->Since_Recurse_0_15_9_ctx_tab[0]); 
  robustSpec_v6_Max_2_step(min_n,_split_83,z); 

} // End of Since_Recurse_0_15_8_step

// Memory initialisation for Since_Recurse_0_15_9_ctx
void Since_Recurse_0_15_9_ctx_reset(Since_Recurse_0_15_9_ctx_type* ctx){
  int _i;

    Sliding_Min_8_ctx_reset(&ctx->Sliding_Min_8_ctx_tab[0]);
    Since_Recurse_0_15_10_ctx_reset(&ctx->Since_Recurse_0_15_10_ctx_tab[0]);
    Delay_9_ctx_reset(&ctx->Delay_9_ctx_tab[0]);
}
// Memory allocation for Since_Recurse_0_15_9_ctx
Since_Recurse_0_15_9_ctx_type* Since_Recurse_0_15_9_ctx_new_ctx(){

   Since_Recurse_0_15_9_ctx_type* ctx = (Since_Recurse_0_15_9_ctx_type*)calloc(1, sizeof(Since_Recurse_0_15_9_ctx_type));
   // ctx->client_data = cdata;
   Since_Recurse_0_15_9_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Since_Recurse_0_15_9_ctx
void Since_Recurse_0_15_9_step(_real x,_real y,_real *z,Since_Recurse_0_15_9_ctx_type* ctx){   _real _split_86;
   _real x_n;
   _real min_m;
   _real min_n;
   _integer _split_87;
   _boolean _split_88;

  _split_87 = 15 - 0;
  _split_88 = _split_87 >= 0;
  Delay_9_step(x,&x_n,&ctx->Delay_9_ctx_tab[0]); 
  Sliding_Min_8_step(y,&min_m,&ctx->Sliding_Min_8_ctx_tab[0]); 
  robustSpec_v6_Min_2_step(x_n,min_m,&min_n); 
  Since_Recurse_0_15_10_step(x,y,&_split_86,&ctx->Since_Recurse_0_15_10_ctx_tab[0]); 
  robustSpec_v6_Max_2_step(min_n,_split_86,z); 

} // End of Since_Recurse_0_15_9_step

// Memory initialisation for Since_Recurse_1_1_0_ctx
void Since_Recurse_1_1_0_ctx_reset(Since_Recurse_1_1_0_ctx_type* ctx){
  int _i;

    Delay_1_ctx_reset(&ctx->Delay_1_ctx_tab[0]);
}
// Memory allocation for Since_Recurse_1_1_0_ctx
Since_Recurse_1_1_0_ctx_type* Since_Recurse_1_1_0_ctx_new_ctx(){

   Since_Recurse_1_1_0_ctx_type* ctx = (Since_Recurse_1_1_0_ctx_type*)calloc(1, sizeof(Since_Recurse_1_1_0_ctx_type));
   // ctx->client_data = cdata;
   Since_Recurse_1_1_0_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Since_Recurse_1_1_0_ctx
void Since_Recurse_1_1_0_step(_real x,_real y,_real *z,Since_Recurse_1_1_0_ctx_type* ctx){   _real x_n;
   _real min_m;
   _real min_n;
   _integer _split_89;
   _boolean _split_90;

  _split_89 = 1 - 1;
  _split_90 = _split_89 >= 0;
  Delay_1_step(x,&x_n,&ctx->Delay_1_ctx_tab[0]); 
  Sliding_Min_0_step(y,&min_m); 
  robustSpec_v6_Min_2_step(x_n,min_m,&min_n); 
  *z = min_n;

} // End of Since_Recurse_1_1_0_step

// Step function(s) for Sliding_Min_0_ctx
void Sliding_Min_0_step(_real x,_real *z){
   _real x_n;

  Delay_0_step(x,&x_n); 
  *z = x_n;

} // End of Sliding_Min_0_step

// Memory initialisation for Sliding_Min_1_ctx
void Sliding_Min_1_ctx_reset(Sliding_Min_1_ctx_type* ctx){
  int _i;

    Delay_1_ctx_reset(&ctx->Delay_1_ctx_tab[0]);
}
// Memory allocation for Sliding_Min_1_ctx
Sliding_Min_1_ctx_type* Sliding_Min_1_ctx_new_ctx(){

   Sliding_Min_1_ctx_type* ctx = (Sliding_Min_1_ctx_type*)calloc(1, sizeof(Sliding_Min_1_ctx_type));
   // ctx->client_data = cdata;
   Sliding_Min_1_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Sliding_Min_1_ctx
void Sliding_Min_1_step(_real x,_real *z,Sliding_Min_1_ctx_type* ctx){   _real _split_91;
   _real x_n;

  Delay_1_step(x,&x_n,&ctx->Delay_1_ctx_tab[0]); 
  Sliding_Min_0_step(x,&_split_91); 
  robustSpec_v6_Min_2_step(x_n,_split_91,z); 

} // End of Sliding_Min_1_step

// Memory initialisation for Sliding_Min_10_ctx
void Sliding_Min_10_ctx_reset(Sliding_Min_10_ctx_type* ctx){
  int _i;

    Sliding_Min_9_ctx_reset(&ctx->Sliding_Min_9_ctx_tab[0]);
    Delay_10_ctx_reset(&ctx->Delay_10_ctx_tab[0]);
}
// Memory allocation for Sliding_Min_10_ctx
Sliding_Min_10_ctx_type* Sliding_Min_10_ctx_new_ctx(){

   Sliding_Min_10_ctx_type* ctx = (Sliding_Min_10_ctx_type*)calloc(1, sizeof(Sliding_Min_10_ctx_type));
   // ctx->client_data = cdata;
   Sliding_Min_10_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Sliding_Min_10_ctx
void Sliding_Min_10_step(_real x,_real *z,Sliding_Min_10_ctx_type* ctx){   _real _split_92;
   _real x_n;

  Delay_10_step(x,&x_n,&ctx->Delay_10_ctx_tab[0]); 
  Sliding_Min_9_step(x,&_split_92,&ctx->Sliding_Min_9_ctx_tab[0]); 
  robustSpec_v6_Min_2_step(x_n,_split_92,z); 

} // End of Sliding_Min_10_step

// Memory initialisation for Sliding_Min_11_ctx
void Sliding_Min_11_ctx_reset(Sliding_Min_11_ctx_type* ctx){
  int _i;

    Sliding_Min_10_ctx_reset(&ctx->Sliding_Min_10_ctx_tab[0]);
    Delay_11_ctx_reset(&ctx->Delay_11_ctx_tab[0]);
}
// Memory allocation for Sliding_Min_11_ctx
Sliding_Min_11_ctx_type* Sliding_Min_11_ctx_new_ctx(){

   Sliding_Min_11_ctx_type* ctx = (Sliding_Min_11_ctx_type*)calloc(1, sizeof(Sliding_Min_11_ctx_type));
   // ctx->client_data = cdata;
   Sliding_Min_11_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Sliding_Min_11_ctx
void Sliding_Min_11_step(_real x,_real *z,Sliding_Min_11_ctx_type* ctx){   _real _split_93;
   _real x_n;

  Delay_11_step(x,&x_n,&ctx->Delay_11_ctx_tab[0]); 
  Sliding_Min_10_step(x,&_split_93,&ctx->Sliding_Min_10_ctx_tab[0]); 
  robustSpec_v6_Min_2_step(x_n,_split_93,z); 

} // End of Sliding_Min_11_step

// Memory initialisation for Sliding_Min_12_ctx
void Sliding_Min_12_ctx_reset(Sliding_Min_12_ctx_type* ctx){
  int _i;

    Sliding_Min_11_ctx_reset(&ctx->Sliding_Min_11_ctx_tab[0]);
    Delay_12_ctx_reset(&ctx->Delay_12_ctx_tab[0]);
}
// Memory allocation for Sliding_Min_12_ctx
Sliding_Min_12_ctx_type* Sliding_Min_12_ctx_new_ctx(){

   Sliding_Min_12_ctx_type* ctx = (Sliding_Min_12_ctx_type*)calloc(1, sizeof(Sliding_Min_12_ctx_type));
   // ctx->client_data = cdata;
   Sliding_Min_12_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Sliding_Min_12_ctx
void Sliding_Min_12_step(_real x,_real *z,Sliding_Min_12_ctx_type* ctx){   _real _split_94;
   _real x_n;

  Delay_12_step(x,&x_n,&ctx->Delay_12_ctx_tab[0]); 
  Sliding_Min_11_step(x,&_split_94,&ctx->Sliding_Min_11_ctx_tab[0]); 
  robustSpec_v6_Min_2_step(x_n,_split_94,z); 

} // End of Sliding_Min_12_step

// Memory initialisation for Sliding_Min_13_ctx
void Sliding_Min_13_ctx_reset(Sliding_Min_13_ctx_type* ctx){
  int _i;

    Sliding_Min_12_ctx_reset(&ctx->Sliding_Min_12_ctx_tab[0]);
    Delay_13_ctx_reset(&ctx->Delay_13_ctx_tab[0]);
}
// Memory allocation for Sliding_Min_13_ctx
Sliding_Min_13_ctx_type* Sliding_Min_13_ctx_new_ctx(){

   Sliding_Min_13_ctx_type* ctx = (Sliding_Min_13_ctx_type*)calloc(1, sizeof(Sliding_Min_13_ctx_type));
   // ctx->client_data = cdata;
   Sliding_Min_13_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Sliding_Min_13_ctx
void Sliding_Min_13_step(_real x,_real *z,Sliding_Min_13_ctx_type* ctx){   _real _split_95;
   _real x_n;

  Delay_13_step(x,&x_n,&ctx->Delay_13_ctx_tab[0]); 
  Sliding_Min_12_step(x,&_split_95,&ctx->Sliding_Min_12_ctx_tab[0]); 
  robustSpec_v6_Min_2_step(x_n,_split_95,z); 

} // End of Sliding_Min_13_step

// Memory initialisation for Sliding_Min_14_ctx
void Sliding_Min_14_ctx_reset(Sliding_Min_14_ctx_type* ctx){
  int _i;

    Sliding_Min_13_ctx_reset(&ctx->Sliding_Min_13_ctx_tab[0]);
    Delay_14_ctx_reset(&ctx->Delay_14_ctx_tab[0]);
}
// Memory allocation for Sliding_Min_14_ctx
Sliding_Min_14_ctx_type* Sliding_Min_14_ctx_new_ctx(){

   Sliding_Min_14_ctx_type* ctx = (Sliding_Min_14_ctx_type*)calloc(1, sizeof(Sliding_Min_14_ctx_type));
   // ctx->client_data = cdata;
   Sliding_Min_14_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Sliding_Min_14_ctx
void Sliding_Min_14_step(_real x,_real *z,Sliding_Min_14_ctx_type* ctx){   _real _split_96;
   _real x_n;

  Delay_14_step(x,&x_n,&ctx->Delay_14_ctx_tab[0]); 
  Sliding_Min_13_step(x,&_split_96,&ctx->Sliding_Min_13_ctx_tab[0]); 
  robustSpec_v6_Min_2_step(x_n,_split_96,z); 

} // End of Sliding_Min_14_step

// Memory initialisation for Sliding_Min_2_ctx
void Sliding_Min_2_ctx_reset(Sliding_Min_2_ctx_type* ctx){
  int _i;

    Sliding_Min_1_ctx_reset(&ctx->Sliding_Min_1_ctx_tab[0]);
    Delay_2_ctx_reset(&ctx->Delay_2_ctx_tab[0]);
}
// Memory allocation for Sliding_Min_2_ctx
Sliding_Min_2_ctx_type* Sliding_Min_2_ctx_new_ctx(){

   Sliding_Min_2_ctx_type* ctx = (Sliding_Min_2_ctx_type*)calloc(1, sizeof(Sliding_Min_2_ctx_type));
   // ctx->client_data = cdata;
   Sliding_Min_2_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Sliding_Min_2_ctx
void Sliding_Min_2_step(_real x,_real *z,Sliding_Min_2_ctx_type* ctx){   _real _split_97;
   _real x_n;

  Delay_2_step(x,&x_n,&ctx->Delay_2_ctx_tab[0]); 
  Sliding_Min_1_step(x,&_split_97,&ctx->Sliding_Min_1_ctx_tab[0]); 
  robustSpec_v6_Min_2_step(x_n,_split_97,z); 

} // End of Sliding_Min_2_step

// Memory initialisation for Sliding_Min_3_ctx
void Sliding_Min_3_ctx_reset(Sliding_Min_3_ctx_type* ctx){
  int _i;

    Sliding_Min_2_ctx_reset(&ctx->Sliding_Min_2_ctx_tab[0]);
    Delay_3_ctx_reset(&ctx->Delay_3_ctx_tab[0]);
}
// Memory allocation for Sliding_Min_3_ctx
Sliding_Min_3_ctx_type* Sliding_Min_3_ctx_new_ctx(){

   Sliding_Min_3_ctx_type* ctx = (Sliding_Min_3_ctx_type*)calloc(1, sizeof(Sliding_Min_3_ctx_type));
   // ctx->client_data = cdata;
   Sliding_Min_3_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Sliding_Min_3_ctx
void Sliding_Min_3_step(_real x,_real *z,Sliding_Min_3_ctx_type* ctx){   _real _split_98;
   _real x_n;

  Delay_3_step(x,&x_n,&ctx->Delay_3_ctx_tab[0]); 
  Sliding_Min_2_step(x,&_split_98,&ctx->Sliding_Min_2_ctx_tab[0]); 
  robustSpec_v6_Min_2_step(x_n,_split_98,z); 

} // End of Sliding_Min_3_step

// Memory initialisation for Sliding_Min_4_ctx
void Sliding_Min_4_ctx_reset(Sliding_Min_4_ctx_type* ctx){
  int _i;

    Sliding_Min_3_ctx_reset(&ctx->Sliding_Min_3_ctx_tab[0]);
    Delay_4_ctx_reset(&ctx->Delay_4_ctx_tab[0]);
}
// Memory allocation for Sliding_Min_4_ctx
Sliding_Min_4_ctx_type* Sliding_Min_4_ctx_new_ctx(){

   Sliding_Min_4_ctx_type* ctx = (Sliding_Min_4_ctx_type*)calloc(1, sizeof(Sliding_Min_4_ctx_type));
   // ctx->client_data = cdata;
   Sliding_Min_4_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Sliding_Min_4_ctx
void Sliding_Min_4_step(_real x,_real *z,Sliding_Min_4_ctx_type* ctx){   _real _split_99;
   _real x_n;

  Delay_4_step(x,&x_n,&ctx->Delay_4_ctx_tab[0]); 
  Sliding_Min_3_step(x,&_split_99,&ctx->Sliding_Min_3_ctx_tab[0]); 
  robustSpec_v6_Min_2_step(x_n,_split_99,z); 

} // End of Sliding_Min_4_step

// Memory initialisation for Sliding_Min_5_ctx
void Sliding_Min_5_ctx_reset(Sliding_Min_5_ctx_type* ctx){
  int _i;

    Sliding_Min_4_ctx_reset(&ctx->Sliding_Min_4_ctx_tab[0]);
    Delay_5_ctx_reset(&ctx->Delay_5_ctx_tab[0]);
}
// Memory allocation for Sliding_Min_5_ctx
Sliding_Min_5_ctx_type* Sliding_Min_5_ctx_new_ctx(){

   Sliding_Min_5_ctx_type* ctx = (Sliding_Min_5_ctx_type*)calloc(1, sizeof(Sliding_Min_5_ctx_type));
   // ctx->client_data = cdata;
   Sliding_Min_5_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Sliding_Min_5_ctx
void Sliding_Min_5_step(_real x,_real *z,Sliding_Min_5_ctx_type* ctx){   _real _split_100;
   _real x_n;

  Delay_5_step(x,&x_n,&ctx->Delay_5_ctx_tab[0]); 
  Sliding_Min_4_step(x,&_split_100,&ctx->Sliding_Min_4_ctx_tab[0]); 
  robustSpec_v6_Min_2_step(x_n,_split_100,z); 

} // End of Sliding_Min_5_step

// Memory initialisation for Sliding_Min_6_ctx
void Sliding_Min_6_ctx_reset(Sliding_Min_6_ctx_type* ctx){
  int _i;

    Sliding_Min_5_ctx_reset(&ctx->Sliding_Min_5_ctx_tab[0]);
    Delay_6_ctx_reset(&ctx->Delay_6_ctx_tab[0]);
}
// Memory allocation for Sliding_Min_6_ctx
Sliding_Min_6_ctx_type* Sliding_Min_6_ctx_new_ctx(){

   Sliding_Min_6_ctx_type* ctx = (Sliding_Min_6_ctx_type*)calloc(1, sizeof(Sliding_Min_6_ctx_type));
   // ctx->client_data = cdata;
   Sliding_Min_6_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Sliding_Min_6_ctx
void Sliding_Min_6_step(_real x,_real *z,Sliding_Min_6_ctx_type* ctx){   _real _split_101;
   _real x_n;

  Delay_6_step(x,&x_n,&ctx->Delay_6_ctx_tab[0]); 
  Sliding_Min_5_step(x,&_split_101,&ctx->Sliding_Min_5_ctx_tab[0]); 
  robustSpec_v6_Min_2_step(x_n,_split_101,z); 

} // End of Sliding_Min_6_step

// Memory initialisation for Sliding_Min_7_ctx
void Sliding_Min_7_ctx_reset(Sliding_Min_7_ctx_type* ctx){
  int _i;

    Sliding_Min_6_ctx_reset(&ctx->Sliding_Min_6_ctx_tab[0]);
    Delay_7_ctx_reset(&ctx->Delay_7_ctx_tab[0]);
}
// Memory allocation for Sliding_Min_7_ctx
Sliding_Min_7_ctx_type* Sliding_Min_7_ctx_new_ctx(){

   Sliding_Min_7_ctx_type* ctx = (Sliding_Min_7_ctx_type*)calloc(1, sizeof(Sliding_Min_7_ctx_type));
   // ctx->client_data = cdata;
   Sliding_Min_7_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Sliding_Min_7_ctx
void Sliding_Min_7_step(_real x,_real *z,Sliding_Min_7_ctx_type* ctx){   _real _split_102;
   _real x_n;

  Delay_7_step(x,&x_n,&ctx->Delay_7_ctx_tab[0]); 
  Sliding_Min_6_step(x,&_split_102,&ctx->Sliding_Min_6_ctx_tab[0]); 
  robustSpec_v6_Min_2_step(x_n,_split_102,z); 

} // End of Sliding_Min_7_step

// Memory initialisation for Sliding_Min_8_ctx
void Sliding_Min_8_ctx_reset(Sliding_Min_8_ctx_type* ctx){
  int _i;

    Sliding_Min_7_ctx_reset(&ctx->Sliding_Min_7_ctx_tab[0]);
    Delay_8_ctx_reset(&ctx->Delay_8_ctx_tab[0]);
}
// Memory allocation for Sliding_Min_8_ctx
Sliding_Min_8_ctx_type* Sliding_Min_8_ctx_new_ctx(){

   Sliding_Min_8_ctx_type* ctx = (Sliding_Min_8_ctx_type*)calloc(1, sizeof(Sliding_Min_8_ctx_type));
   // ctx->client_data = cdata;
   Sliding_Min_8_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Sliding_Min_8_ctx
void Sliding_Min_8_step(_real x,_real *z,Sliding_Min_8_ctx_type* ctx){   _real _split_103;
   _real x_n;

  Delay_8_step(x,&x_n,&ctx->Delay_8_ctx_tab[0]); 
  Sliding_Min_7_step(x,&_split_103,&ctx->Sliding_Min_7_ctx_tab[0]); 
  robustSpec_v6_Min_2_step(x_n,_split_103,z); 

} // End of Sliding_Min_8_step

// Memory initialisation for Sliding_Min_9_ctx
void Sliding_Min_9_ctx_reset(Sliding_Min_9_ctx_type* ctx){
  int _i;

    Sliding_Min_8_ctx_reset(&ctx->Sliding_Min_8_ctx_tab[0]);
    Delay_9_ctx_reset(&ctx->Delay_9_ctx_tab[0]);
}
// Memory allocation for Sliding_Min_9_ctx
Sliding_Min_9_ctx_type* Sliding_Min_9_ctx_new_ctx(){

   Sliding_Min_9_ctx_type* ctx = (Sliding_Min_9_ctx_type*)calloc(1, sizeof(Sliding_Min_9_ctx_type));
   // ctx->client_data = cdata;
   Sliding_Min_9_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Sliding_Min_9_ctx
void Sliding_Min_9_step(_real x,_real *z,Sliding_Min_9_ctx_type* ctx){   _real _split_104;
   _real x_n;

  Delay_9_step(x,&x_n,&ctx->Delay_9_ctx_tab[0]); 
  Sliding_Min_8_step(x,&_split_104,&ctx->Sliding_Min_8_ctx_tab[0]); 
  robustSpec_v6_Min_2_step(x_n,_split_104,z); 

} // End of Sliding_Min_9_step

// Step function(s) for Sliding_Min_m1_ctx
void Sliding_Min_m1_step(_real x,_real *z){
   _real x_n;

  Delay_m1_step(x,&x_n); 
  *z = x_n;

} // End of Sliding_Min_m1_step

// Step function(s) for robustSpec_v6_Abs_ctx
void robustSpec_v6_Abs_step(_real x,_real *abs_x){
   _real _split_2;
   _boolean _split_1;

  _split_2 = - x;
  _split_1 = x > 0.0;
   if (_split_1 == _true) {
     *abs_x = x;
   } else {
     *abs_x = _split_2;
   }

} // End of robustSpec_v6_Abs_step

// Memory initialisation for robustSpec_v6_ComputeRho_AP_ctx
void robustSpec_v6_ComputeRho_AP_ctx_reset(robustSpec_v6_ComputeRho_AP_ctx_type* ctx){
  int _i;

    robustSpec_v6_f_AP_0_ctx_reset(&ctx->robustSpec_v6_f_AP_0_ctx_tab[0]);
}
// Memory allocation for robustSpec_v6_ComputeRho_AP_ctx
robustSpec_v6_ComputeRho_AP_ctx_type* robustSpec_v6_ComputeRho_AP_ctx_new_ctx(){

   robustSpec_v6_ComputeRho_AP_ctx_type* ctx = (robustSpec_v6_ComputeRho_AP_ctx_type*)calloc(1, sizeof(robustSpec_v6_ComputeRho_AP_ctx_type));
   // ctx->client_data = cdata;
   robustSpec_v6_ComputeRho_AP_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for robustSpec_v6_ComputeRho_AP_ctx
void robustSpec_v6_ComputeRho_AP_step(robustSpec_v6_SamplePoint SP,_real Rho_AP[2]/*out*/,robustSpec_v6_ComputeRho_AP_ctx_type* ctx){
  robustSpec_v6_f_AP_0_step(SP,&Rho_AP[0],&ctx->robustSpec_v6_f_AP_0_ctx_tab[0]); 
  robustSpec_v6_f_AP_1_step(SP,&Rho_AP[1]); 

} // End of robustSpec_v6_ComputeRho_AP_step

// Memory initialisation for robustSpec_v6_ComputeRho_Phi_ctx
void robustSpec_v6_ComputeRho_Phi_ctx_reset(robustSpec_v6_ComputeRho_Phi_ctx_type* ctx){
  int _i;

    Once_Interval_0_15_ctx_reset(&ctx->Once_Interval_0_15_ctx_tab[0]);
    Once_Interval_0_15_ctx_reset(&ctx->Once_Interval_0_15_ctx_tab[1]);
}
// Memory allocation for robustSpec_v6_ComputeRho_Phi_ctx
robustSpec_v6_ComputeRho_Phi_ctx_type* robustSpec_v6_ComputeRho_Phi_ctx_new_ctx(){

   robustSpec_v6_ComputeRho_Phi_ctx_type* ctx = (robustSpec_v6_ComputeRho_Phi_ctx_type*)calloc(1, sizeof(robustSpec_v6_ComputeRho_Phi_ctx_type));
   // ctx->client_data = cdata;
   robustSpec_v6_ComputeRho_Phi_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for robustSpec_v6_ComputeRho_Phi_ctx
void robustSpec_v6_ComputeRho_Phi_step(_real Rho_AP[2],_real Rho[3]/*out*/,robustSpec_v6_ComputeRho_Phi_ctx_type* ctx){   _real _split_4;
   _real _split_3;

  Rho[0] = Rho_AP[0];
  Rho[1] = Rho_AP[1];
  Once_Interval_0_15_step(Rho_AP[1],&_split_4,&ctx->Once_Interval_0_15_ctx_tab[0]); 
  Once_Interval_0_15_step(Rho_AP[0],&_split_3,&ctx->Once_Interval_0_15_ctx_tab[1]); 
  robustSpec_v6_Implies_step(_split_3,_split_4,&Rho[2]); 

} // End of robustSpec_v6_ComputeRho_Phi_step

// Step function(s) for robustSpec_v6_Implies_ctx
void robustSpec_v6_Implies_step(_real x,_real y,_real *z){
   _real _split_35;

  robustSpec_v6_Not_step(x,&_split_35); 
  robustSpec_v6_Or_step(_split_35,y,z); 

} // End of robustSpec_v6_Implies_step

// Memory initialisation for robustSpec_v6_Main_ctx
void robustSpec_v6_Main_ctx_reset(robustSpec_v6_Main_ctx_type* ctx){
  int _i;

    robustSpec_v6_ComputeRho_Phi_ctx_reset(&ctx->robustSpec_v6_ComputeRho_Phi_ctx_tab[0]);
    robustSpec_v6_ComputeRho_AP_ctx_reset(&ctx->robustSpec_v6_ComputeRho_AP_ctx_tab[0]);
}
// Memory allocation for robustSpec_v6_Main_ctx
robustSpec_v6_Main_ctx_type* robustSpec_v6_Main_ctx_new_ctx(){

   robustSpec_v6_Main_ctx_type* ctx = (robustSpec_v6_Main_ctx_type*)calloc(1, sizeof(robustSpec_v6_Main_ctx_type));
   // ctx->client_data = cdata;
   robustSpec_v6_Main_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for robustSpec_v6_Main_ctx
void robustSpec_v6_Main_step(robustSpec_v6_SamplePoint SP,_real Rho[3]/*out*/,robustSpec_v6_Main_ctx_type* ctx){   _real Rho_AP[2];

  robustSpec_v6_ComputeRho_AP_step(SP,Rho_AP,&ctx->robustSpec_v6_ComputeRho_AP_ctx_tab[0]); 
  robustSpec_v6_ComputeRho_Phi_step(Rho_AP,Rho,&ctx->robustSpec_v6_ComputeRho_Phi_ctx_tab[0]); 

} // End of robustSpec_v6_Main_step

// Step function(s) for robustSpec_v6_Max_2_ctx
void robustSpec_v6_Max_2_step(_real x,_real y,_real *max){
   _boolean _split_36;

  _split_36 = x > y;
   if (_split_36 == _true) {
     *max = x;
   } else {
     *max = y;
   }

} // End of robustSpec_v6_Max_2_step

// Step function(s) for robustSpec_v6_Min_2_ctx
void robustSpec_v6_Min_2_step(_real x,_real y,_real *min){
   _boolean _split_37;

  _split_37 = x > y;
   if (_split_37 == _true) {
     *min = y;
   } else {
     *min = x;
   }

} // End of robustSpec_v6_Min_2_step

// Step function(s) for robustSpec_v6_Not_ctx
void robustSpec_v6_Not_step(_real x,_real *not_x){

  *not_x = - x;

} // End of robustSpec_v6_Not_step

// Step function(s) for robustSpec_v6_Or_ctx
void robustSpec_v6_Or_step(_real x,_real y,_real *z){

  robustSpec_v6_Max_2_step(x,y,z); 

} // End of robustSpec_v6_Or_step

// Memory initialisation for robustSpec_v6_Previous_ctx
void robustSpec_v6_Previous_ctx_reset(robustSpec_v6_Previous_ctx_type* ctx){
  int _i;

    Since_Interval_1_1_ctx_reset(&ctx->Since_Interval_1_1_ctx_tab[0]);
}
// Memory allocation for robustSpec_v6_Previous_ctx
robustSpec_v6_Previous_ctx_type* robustSpec_v6_Previous_ctx_new_ctx(){

   robustSpec_v6_Previous_ctx_type* ctx = (robustSpec_v6_Previous_ctx_type*)calloc(1, sizeof(robustSpec_v6_Previous_ctx_type));
   // ctx->client_data = cdata;
   robustSpec_v6_Previous_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for robustSpec_v6_Previous_ctx
void robustSpec_v6_Previous_step(_real x,_real *z,robustSpec_v6_Previous_ctx_type* ctx){
  Since_Interval_1_1_step(x,99.0,z,&ctx->Since_Interval_1_1_ctx_tab[0]); 

} // End of robustSpec_v6_Previous_step

// Memory initialisation for robustSpec_v6_f_AP_0_ctx
void robustSpec_v6_f_AP_0_ctx_reset(robustSpec_v6_f_AP_0_ctx_type* ctx){
  int _i;

    robustSpec_v6_Previous_ctx_reset(&ctx->robustSpec_v6_Previous_ctx_tab[0]);
}
// Memory allocation for robustSpec_v6_f_AP_0_ctx
robustSpec_v6_f_AP_0_ctx_type* robustSpec_v6_f_AP_0_ctx_new_ctx(){

   robustSpec_v6_f_AP_0_ctx_type* ctx = (robustSpec_v6_f_AP_0_ctx_type*)calloc(1, sizeof(robustSpec_v6_f_AP_0_ctx_type));
   // ctx->client_data = cdata;
   robustSpec_v6_f_AP_0_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for robustSpec_v6_f_AP_0_ctx
void robustSpec_v6_f_AP_0_step(robustSpec_v6_SamplePoint SP,_real *mu,robustSpec_v6_f_AP_0_ctx_type* ctx){   _real _split_107;
   _real _split_106;
   _real _split_105;

  robustSpec_v6_Previous_step(SP.s[2],&_split_105,&ctx->robustSpec_v6_Previous_ctx_tab[0]); 
  _split_106 = SP.s[2] - _split_105;
  robustSpec_v6_Abs_step(_split_106,&_split_107); 
  *mu = 0.1 - _split_107;

} // End of robustSpec_v6_f_AP_0_step

// Step function(s) for robustSpec_v6_f_AP_1_ctx
void robustSpec_v6_f_AP_1_step(robustSpec_v6_SamplePoint SP,_real *mu){
   _real _split_110;
   _real _split_109;
   _real _split_108;

  _split_108 = SP.s[0] - SP.s[2];
  robustSpec_v6_Abs_step(_split_108,&_split_109); 
  _split_110 = _split_109 / SP.s[2];
  *mu = 0.1 - _split_110;

} // End of robustSpec_v6_f_AP_1_step

