/* This file was generated by lv6 version master.737 (2727a7744111c84f7984634d2bd3ad6f7c6c7ff9). */
/*  lv6 -2c -cc -n Main robustSpec_v6.lus */
/* on s27 the 03/04/2020 at 08:27:05 */

#include <stdlib.h>
#include <string.h>

#include "lustre_types.h"
#include "lustre_consts.h"

#ifndef _robustSpec_v6_Main_H_FILE
#define _robustSpec_v6_Main_H_FILE
void Delay_0_step(_real ,_real *);

void Delay_1_ctx_reset(Delay_1_ctx_type* ctx);
Delay_1_ctx_type* Delay_1_ctx_new_ctx();
void Delay_1_step(_real ,_real *,Delay_1_ctx_type*);

void Delay_2_ctx_reset(Delay_2_ctx_type* ctx);
Delay_2_ctx_type* Delay_2_ctx_new_ctx();
void Delay_2_step(_real ,_real *,Delay_2_ctx_type*);

void Delay_3_ctx_reset(Delay_3_ctx_type* ctx);
Delay_3_ctx_type* Delay_3_ctx_new_ctx();
void Delay_3_step(_real ,_real *,Delay_3_ctx_type*);

void Delay_4_ctx_reset(Delay_4_ctx_type* ctx);
Delay_4_ctx_type* Delay_4_ctx_new_ctx();
void Delay_4_step(_real ,_real *,Delay_4_ctx_type*);

void Delay_5_ctx_reset(Delay_5_ctx_type* ctx);
Delay_5_ctx_type* Delay_5_ctx_new_ctx();
void Delay_5_step(_real ,_real *,Delay_5_ctx_type*);

void Delay_m1_step(_real ,_real *);

void Lustre_arrow_ctx_reset(Lustre_arrow_ctx_type* ctx);
Lustre_arrow_ctx_type* Lustre_arrow_ctx_new_ctx();
void Lustre_arrow_step(_real ,_real ,_real *,Lustre_arrow_ctx_type*);

void Lustre_pre_ctx_reset(Lustre_pre_ctx_type* ctx);
Lustre_pre_ctx_type* Lustre_pre_ctx_new_ctx();
void Lustre_pre_get(_real *,Lustre_pre_ctx_type*);

void Lustre_pre_set(_real ,Lustre_pre_ctx_type*);

void Lustre_slash_step(_real ,_real ,_real *);

void Once_Interval_0_5_ctx_reset(Once_Interval_0_5_ctx_type* ctx);
Once_Interval_0_5_ctx_type* Once_Interval_0_5_ctx_new_ctx();
void Once_Interval_0_5_step(_real ,_real *,Once_Interval_0_5_ctx_type*);

void Since_Interval_0_5_ctx_reset(Since_Interval_0_5_ctx_type* ctx);
Since_Interval_0_5_ctx_type* Since_Interval_0_5_ctx_new_ctx();
void Since_Interval_0_5_step(_real ,_real ,_real *,Since_Interval_0_5_ctx_type*);

void Since_Interval_1_1_ctx_reset(Since_Interval_1_1_ctx_type* ctx);
Since_Interval_1_1_ctx_type* Since_Interval_1_1_ctx_new_ctx();
void Since_Interval_1_1_step(_real ,_real ,_real *,Since_Interval_1_1_ctx_type*);

void Since_Recurse_0_5_0_ctx_reset(Since_Recurse_0_5_0_ctx_type* ctx);
Since_Recurse_0_5_0_ctx_type* Since_Recurse_0_5_0_ctx_new_ctx();
void Since_Recurse_0_5_0_step(_real ,_real ,_real *,Since_Recurse_0_5_0_ctx_type*);

void Since_Recurse_0_5_1_ctx_reset(Since_Recurse_0_5_1_ctx_type* ctx);
Since_Recurse_0_5_1_ctx_type* Since_Recurse_0_5_1_ctx_new_ctx();
void Since_Recurse_0_5_1_step(_real ,_real ,_real *,Since_Recurse_0_5_1_ctx_type*);

void Since_Recurse_0_5_2_ctx_reset(Since_Recurse_0_5_2_ctx_type* ctx);
Since_Recurse_0_5_2_ctx_type* Since_Recurse_0_5_2_ctx_new_ctx();
void Since_Recurse_0_5_2_step(_real ,_real ,_real *,Since_Recurse_0_5_2_ctx_type*);

void Since_Recurse_0_5_3_ctx_reset(Since_Recurse_0_5_3_ctx_type* ctx);
Since_Recurse_0_5_3_ctx_type* Since_Recurse_0_5_3_ctx_new_ctx();
void Since_Recurse_0_5_3_step(_real ,_real ,_real *,Since_Recurse_0_5_3_ctx_type*);

void Since_Recurse_0_5_4_ctx_reset(Since_Recurse_0_5_4_ctx_type* ctx);
Since_Recurse_0_5_4_ctx_type* Since_Recurse_0_5_4_ctx_new_ctx();
void Since_Recurse_0_5_4_step(_real ,_real ,_real *,Since_Recurse_0_5_4_ctx_type*);

void Since_Recurse_0_5_5_ctx_reset(Since_Recurse_0_5_5_ctx_type* ctx);
Since_Recurse_0_5_5_ctx_type* Since_Recurse_0_5_5_ctx_new_ctx();
void Since_Recurse_0_5_5_step(_real ,_real ,_real *,Since_Recurse_0_5_5_ctx_type*);

void Since_Recurse_1_1_0_ctx_reset(Since_Recurse_1_1_0_ctx_type* ctx);
Since_Recurse_1_1_0_ctx_type* Since_Recurse_1_1_0_ctx_new_ctx();
void Since_Recurse_1_1_0_step(_real ,_real ,_real *,Since_Recurse_1_1_0_ctx_type*);

void Sliding_Min_0_step(_real ,_real *);

void Sliding_Min_1_ctx_reset(Sliding_Min_1_ctx_type* ctx);
Sliding_Min_1_ctx_type* Sliding_Min_1_ctx_new_ctx();
void Sliding_Min_1_step(_real ,_real *,Sliding_Min_1_ctx_type*);

void Sliding_Min_2_ctx_reset(Sliding_Min_2_ctx_type* ctx);
Sliding_Min_2_ctx_type* Sliding_Min_2_ctx_new_ctx();
void Sliding_Min_2_step(_real ,_real *,Sliding_Min_2_ctx_type*);

void Sliding_Min_3_ctx_reset(Sliding_Min_3_ctx_type* ctx);
Sliding_Min_3_ctx_type* Sliding_Min_3_ctx_new_ctx();
void Sliding_Min_3_step(_real ,_real *,Sliding_Min_3_ctx_type*);

void Sliding_Min_4_ctx_reset(Sliding_Min_4_ctx_type* ctx);
Sliding_Min_4_ctx_type* Sliding_Min_4_ctx_new_ctx();
void Sliding_Min_4_step(_real ,_real *,Sliding_Min_4_ctx_type*);

void Sliding_Min_m1_step(_real ,_real *);

void robustSpec_v6_Abs_step(_real ,_real *);

void robustSpec_v6_ComputeRho_AP_ctx_reset(robustSpec_v6_ComputeRho_AP_ctx_type* ctx);
robustSpec_v6_ComputeRho_AP_ctx_type* robustSpec_v6_ComputeRho_AP_ctx_new_ctx();
void robustSpec_v6_ComputeRho_AP_step(robustSpec_v6_SamplePoint ,_real [2]/*out*/,robustSpec_v6_ComputeRho_AP_ctx_type*);

void robustSpec_v6_ComputeRho_Phi_ctx_reset(robustSpec_v6_ComputeRho_Phi_ctx_type* ctx);
robustSpec_v6_ComputeRho_Phi_ctx_type* robustSpec_v6_ComputeRho_Phi_ctx_new_ctx();
void robustSpec_v6_ComputeRho_Phi_step(_real [2],_real [3]/*out*/,robustSpec_v6_ComputeRho_Phi_ctx_type*);

void robustSpec_v6_Main_ctx_reset(robustSpec_v6_Main_ctx_type* ctx);
robustSpec_v6_Main_ctx_type* robustSpec_v6_Main_ctx_new_ctx();
void robustSpec_v6_Main_step(robustSpec_v6_SamplePoint ,_real [3]/*out*/,robustSpec_v6_Main_ctx_type*);

void robustSpec_v6_Max_2_step(_real ,_real ,_real *);

void robustSpec_v6_Min_2_step(_real ,_real ,_real *);

void robustSpec_v6_Previous_ctx_reset(robustSpec_v6_Previous_ctx_type* ctx);
robustSpec_v6_Previous_ctx_type* robustSpec_v6_Previous_ctx_new_ctx();
void robustSpec_v6_Previous_step(_real ,_real *,robustSpec_v6_Previous_ctx_type*);

void robustSpec_v6_f_AP_0_ctx_reset(robustSpec_v6_f_AP_0_ctx_type* ctx);
robustSpec_v6_f_AP_0_ctx_type* robustSpec_v6_f_AP_0_ctx_new_ctx();
void robustSpec_v6_f_AP_0_step(robustSpec_v6_SamplePoint ,_real *,robustSpec_v6_f_AP_0_ctx_type*);

void robustSpec_v6_f_AP_1_step(robustSpec_v6_SamplePoint ,_real *);

/////////////////////////////////////////////////
#endif
