/* This file was generated by lv6 version 6.101.17. */
/*  lv6 -2c -cc -n Main robustSpec_v6.lus */
/* on s27 the 01/04/2020 at 12:32:34 */

#include <stdlib.h>
#include <string.h>

#include "lustre_consts.h"

#ifndef _robustSpec_v6_Main_H_FILE
#define _robustSpec_v6_Main_H_FILE
void Delay_0_step(_real ,_real *);

void Delay_1_ctx_reset(Delay_1_ctx_type* ctx);
Delay_1_ctx_type* Delay_1_ctx_new_ctx();
void Delay_1_step(_real ,_real *,Delay_1_ctx_type*);

void Delay_10_ctx_reset(Delay_10_ctx_type* ctx);
Delay_10_ctx_type* Delay_10_ctx_new_ctx();
void Delay_10_step(_real ,_real *,Delay_10_ctx_type*);

void Delay_11_ctx_reset(Delay_11_ctx_type* ctx);
Delay_11_ctx_type* Delay_11_ctx_new_ctx();
void Delay_11_step(_real ,_real *,Delay_11_ctx_type*);

void Delay_12_ctx_reset(Delay_12_ctx_type* ctx);
Delay_12_ctx_type* Delay_12_ctx_new_ctx();
void Delay_12_step(_real ,_real *,Delay_12_ctx_type*);

void Delay_13_ctx_reset(Delay_13_ctx_type* ctx);
Delay_13_ctx_type* Delay_13_ctx_new_ctx();
void Delay_13_step(_real ,_real *,Delay_13_ctx_type*);

void Delay_14_ctx_reset(Delay_14_ctx_type* ctx);
Delay_14_ctx_type* Delay_14_ctx_new_ctx();
void Delay_14_step(_real ,_real *,Delay_14_ctx_type*);

void Delay_15_ctx_reset(Delay_15_ctx_type* ctx);
Delay_15_ctx_type* Delay_15_ctx_new_ctx();
void Delay_15_step(_real ,_real *,Delay_15_ctx_type*);

void Delay_2_ctx_reset(Delay_2_ctx_type* ctx);
Delay_2_ctx_type* Delay_2_ctx_new_ctx();
void Delay_2_step(_real ,_real *,Delay_2_ctx_type*);

void Delay_3_ctx_reset(Delay_3_ctx_type* ctx);
Delay_3_ctx_type* Delay_3_ctx_new_ctx();
void Delay_3_step(_real ,_real *,Delay_3_ctx_type*);

void Delay_4_ctx_reset(Delay_4_ctx_type* ctx);
Delay_4_ctx_type* Delay_4_ctx_new_ctx();
void Delay_4_step(_real ,_real *,Delay_4_ctx_type*);

void Delay_5_ctx_reset(Delay_5_ctx_type* ctx);
Delay_5_ctx_type* Delay_5_ctx_new_ctx();
void Delay_5_step(_real ,_real *,Delay_5_ctx_type*);

void Delay_6_ctx_reset(Delay_6_ctx_type* ctx);
Delay_6_ctx_type* Delay_6_ctx_new_ctx();
void Delay_6_step(_real ,_real *,Delay_6_ctx_type*);

void Delay_7_ctx_reset(Delay_7_ctx_type* ctx);
Delay_7_ctx_type* Delay_7_ctx_new_ctx();
void Delay_7_step(_real ,_real *,Delay_7_ctx_type*);

void Delay_8_ctx_reset(Delay_8_ctx_type* ctx);
Delay_8_ctx_type* Delay_8_ctx_new_ctx();
void Delay_8_step(_real ,_real *,Delay_8_ctx_type*);

void Delay_9_ctx_reset(Delay_9_ctx_type* ctx);
Delay_9_ctx_type* Delay_9_ctx_new_ctx();
void Delay_9_step(_real ,_real *,Delay_9_ctx_type*);

void Delay_m1_step(_real ,_real *);

void Lustre_arrow_ctx_reset(Lustre_arrow_ctx_type* ctx);
Lustre_arrow_ctx_type* Lustre_arrow_ctx_new_ctx();
void Lustre_arrow_step(_real ,_real ,_real *,Lustre_arrow_ctx_type*);

void Lustre_pre_ctx_reset(Lustre_pre_ctx_type* ctx);
Lustre_pre_ctx_type* Lustre_pre_ctx_new_ctx();
void Lustre_pre_get(_real *,Lustre_pre_ctx_type*);

void Lustre_pre_set(_real ,Lustre_pre_ctx_type*);

void Once_Interval_0_15_ctx_reset(Once_Interval_0_15_ctx_type* ctx);
Once_Interval_0_15_ctx_type* Once_Interval_0_15_ctx_new_ctx();
void Once_Interval_0_15_step(_real ,_real *,Once_Interval_0_15_ctx_type*);

void Since_Interval_0_15_ctx_reset(Since_Interval_0_15_ctx_type* ctx);
Since_Interval_0_15_ctx_type* Since_Interval_0_15_ctx_new_ctx();
void Since_Interval_0_15_step(_real ,_real ,_real *,Since_Interval_0_15_ctx_type*);

void Since_Interval_1_1_ctx_reset(Since_Interval_1_1_ctx_type* ctx);
Since_Interval_1_1_ctx_type* Since_Interval_1_1_ctx_new_ctx();
void Since_Interval_1_1_step(_real ,_real ,_real *,Since_Interval_1_1_ctx_type*);

void Since_Recurse_0_15_0_ctx_reset(Since_Recurse_0_15_0_ctx_type* ctx);
Since_Recurse_0_15_0_ctx_type* Since_Recurse_0_15_0_ctx_new_ctx();
void Since_Recurse_0_15_0_step(_real ,_real ,_real *,Since_Recurse_0_15_0_ctx_type*);

void Since_Recurse_0_15_1_ctx_reset(Since_Recurse_0_15_1_ctx_type* ctx);
Since_Recurse_0_15_1_ctx_type* Since_Recurse_0_15_1_ctx_new_ctx();
void Since_Recurse_0_15_1_step(_real ,_real ,_real *,Since_Recurse_0_15_1_ctx_type*);

void Since_Recurse_0_15_10_ctx_reset(Since_Recurse_0_15_10_ctx_type* ctx);
Since_Recurse_0_15_10_ctx_type* Since_Recurse_0_15_10_ctx_new_ctx();
void Since_Recurse_0_15_10_step(_real ,_real ,_real *,Since_Recurse_0_15_10_ctx_type*);

void Since_Recurse_0_15_11_ctx_reset(Since_Recurse_0_15_11_ctx_type* ctx);
Since_Recurse_0_15_11_ctx_type* Since_Recurse_0_15_11_ctx_new_ctx();
void Since_Recurse_0_15_11_step(_real ,_real ,_real *,Since_Recurse_0_15_11_ctx_type*);

void Since_Recurse_0_15_12_ctx_reset(Since_Recurse_0_15_12_ctx_type* ctx);
Since_Recurse_0_15_12_ctx_type* Since_Recurse_0_15_12_ctx_new_ctx();
void Since_Recurse_0_15_12_step(_real ,_real ,_real *,Since_Recurse_0_15_12_ctx_type*);

void Since_Recurse_0_15_13_ctx_reset(Since_Recurse_0_15_13_ctx_type* ctx);
Since_Recurse_0_15_13_ctx_type* Since_Recurse_0_15_13_ctx_new_ctx();
void Since_Recurse_0_15_13_step(_real ,_real ,_real *,Since_Recurse_0_15_13_ctx_type*);

void Since_Recurse_0_15_14_ctx_reset(Since_Recurse_0_15_14_ctx_type* ctx);
Since_Recurse_0_15_14_ctx_type* Since_Recurse_0_15_14_ctx_new_ctx();
void Since_Recurse_0_15_14_step(_real ,_real ,_real *,Since_Recurse_0_15_14_ctx_type*);

void Since_Recurse_0_15_15_ctx_reset(Since_Recurse_0_15_15_ctx_type* ctx);
Since_Recurse_0_15_15_ctx_type* Since_Recurse_0_15_15_ctx_new_ctx();
void Since_Recurse_0_15_15_step(_real ,_real ,_real *,Since_Recurse_0_15_15_ctx_type*);

void Since_Recurse_0_15_2_ctx_reset(Since_Recurse_0_15_2_ctx_type* ctx);
Since_Recurse_0_15_2_ctx_type* Since_Recurse_0_15_2_ctx_new_ctx();
void Since_Recurse_0_15_2_step(_real ,_real ,_real *,Since_Recurse_0_15_2_ctx_type*);

void Since_Recurse_0_15_3_ctx_reset(Since_Recurse_0_15_3_ctx_type* ctx);
Since_Recurse_0_15_3_ctx_type* Since_Recurse_0_15_3_ctx_new_ctx();
void Since_Recurse_0_15_3_step(_real ,_real ,_real *,Since_Recurse_0_15_3_ctx_type*);

void Since_Recurse_0_15_4_ctx_reset(Since_Recurse_0_15_4_ctx_type* ctx);
Since_Recurse_0_15_4_ctx_type* Since_Recurse_0_15_4_ctx_new_ctx();
void Since_Recurse_0_15_4_step(_real ,_real ,_real *,Since_Recurse_0_15_4_ctx_type*);

void Since_Recurse_0_15_5_ctx_reset(Since_Recurse_0_15_5_ctx_type* ctx);
Since_Recurse_0_15_5_ctx_type* Since_Recurse_0_15_5_ctx_new_ctx();
void Since_Recurse_0_15_5_step(_real ,_real ,_real *,Since_Recurse_0_15_5_ctx_type*);

void Since_Recurse_0_15_6_ctx_reset(Since_Recurse_0_15_6_ctx_type* ctx);
Since_Recurse_0_15_6_ctx_type* Since_Recurse_0_15_6_ctx_new_ctx();
void Since_Recurse_0_15_6_step(_real ,_real ,_real *,Since_Recurse_0_15_6_ctx_type*);

void Since_Recurse_0_15_7_ctx_reset(Since_Recurse_0_15_7_ctx_type* ctx);
Since_Recurse_0_15_7_ctx_type* Since_Recurse_0_15_7_ctx_new_ctx();
void Since_Recurse_0_15_7_step(_real ,_real ,_real *,Since_Recurse_0_15_7_ctx_type*);

void Since_Recurse_0_15_8_ctx_reset(Since_Recurse_0_15_8_ctx_type* ctx);
Since_Recurse_0_15_8_ctx_type* Since_Recurse_0_15_8_ctx_new_ctx();
void Since_Recurse_0_15_8_step(_real ,_real ,_real *,Since_Recurse_0_15_8_ctx_type*);

void Since_Recurse_0_15_9_ctx_reset(Since_Recurse_0_15_9_ctx_type* ctx);
Since_Recurse_0_15_9_ctx_type* Since_Recurse_0_15_9_ctx_new_ctx();
void Since_Recurse_0_15_9_step(_real ,_real ,_real *,Since_Recurse_0_15_9_ctx_type*);

void Since_Recurse_1_1_0_ctx_reset(Since_Recurse_1_1_0_ctx_type* ctx);
Since_Recurse_1_1_0_ctx_type* Since_Recurse_1_1_0_ctx_new_ctx();
void Since_Recurse_1_1_0_step(_real ,_real ,_real *,Since_Recurse_1_1_0_ctx_type*);

void Sliding_Min_0_step(_real ,_real *);

void Sliding_Min_1_ctx_reset(Sliding_Min_1_ctx_type* ctx);
Sliding_Min_1_ctx_type* Sliding_Min_1_ctx_new_ctx();
void Sliding_Min_1_step(_real ,_real *,Sliding_Min_1_ctx_type*);

void Sliding_Min_10_ctx_reset(Sliding_Min_10_ctx_type* ctx);
Sliding_Min_10_ctx_type* Sliding_Min_10_ctx_new_ctx();
void Sliding_Min_10_step(_real ,_real *,Sliding_Min_10_ctx_type*);

void Sliding_Min_11_ctx_reset(Sliding_Min_11_ctx_type* ctx);
Sliding_Min_11_ctx_type* Sliding_Min_11_ctx_new_ctx();
void Sliding_Min_11_step(_real ,_real *,Sliding_Min_11_ctx_type*);

void Sliding_Min_12_ctx_reset(Sliding_Min_12_ctx_type* ctx);
Sliding_Min_12_ctx_type* Sliding_Min_12_ctx_new_ctx();
void Sliding_Min_12_step(_real ,_real *,Sliding_Min_12_ctx_type*);

void Sliding_Min_13_ctx_reset(Sliding_Min_13_ctx_type* ctx);
Sliding_Min_13_ctx_type* Sliding_Min_13_ctx_new_ctx();
void Sliding_Min_13_step(_real ,_real *,Sliding_Min_13_ctx_type*);

void Sliding_Min_14_ctx_reset(Sliding_Min_14_ctx_type* ctx);
Sliding_Min_14_ctx_type* Sliding_Min_14_ctx_new_ctx();
void Sliding_Min_14_step(_real ,_real *,Sliding_Min_14_ctx_type*);

void Sliding_Min_2_ctx_reset(Sliding_Min_2_ctx_type* ctx);
Sliding_Min_2_ctx_type* Sliding_Min_2_ctx_new_ctx();
void Sliding_Min_2_step(_real ,_real *,Sliding_Min_2_ctx_type*);

void Sliding_Min_3_ctx_reset(Sliding_Min_3_ctx_type* ctx);
Sliding_Min_3_ctx_type* Sliding_Min_3_ctx_new_ctx();
void Sliding_Min_3_step(_real ,_real *,Sliding_Min_3_ctx_type*);

void Sliding_Min_4_ctx_reset(Sliding_Min_4_ctx_type* ctx);
Sliding_Min_4_ctx_type* Sliding_Min_4_ctx_new_ctx();
void Sliding_Min_4_step(_real ,_real *,Sliding_Min_4_ctx_type*);

void Sliding_Min_5_ctx_reset(Sliding_Min_5_ctx_type* ctx);
Sliding_Min_5_ctx_type* Sliding_Min_5_ctx_new_ctx();
void Sliding_Min_5_step(_real ,_real *,Sliding_Min_5_ctx_type*);

void Sliding_Min_6_ctx_reset(Sliding_Min_6_ctx_type* ctx);
Sliding_Min_6_ctx_type* Sliding_Min_6_ctx_new_ctx();
void Sliding_Min_6_step(_real ,_real *,Sliding_Min_6_ctx_type*);

void Sliding_Min_7_ctx_reset(Sliding_Min_7_ctx_type* ctx);
Sliding_Min_7_ctx_type* Sliding_Min_7_ctx_new_ctx();
void Sliding_Min_7_step(_real ,_real *,Sliding_Min_7_ctx_type*);

void Sliding_Min_8_ctx_reset(Sliding_Min_8_ctx_type* ctx);
Sliding_Min_8_ctx_type* Sliding_Min_8_ctx_new_ctx();
void Sliding_Min_8_step(_real ,_real *,Sliding_Min_8_ctx_type*);

void Sliding_Min_9_ctx_reset(Sliding_Min_9_ctx_type* ctx);
Sliding_Min_9_ctx_type* Sliding_Min_9_ctx_new_ctx();
void Sliding_Min_9_step(_real ,_real *,Sliding_Min_9_ctx_type*);

void Sliding_Min_m1_step(_real ,_real *);

void robustSpec_v6_Abs_step(_real ,_real *);

void robustSpec_v6_ComputeRho_AP_ctx_reset(robustSpec_v6_ComputeRho_AP_ctx_type* ctx);
robustSpec_v6_ComputeRho_AP_ctx_type* robustSpec_v6_ComputeRho_AP_ctx_new_ctx();
void robustSpec_v6_ComputeRho_AP_step(robustSpec_v6_SamplePoint ,_real [2]/*out*/,robustSpec_v6_ComputeRho_AP_ctx_type*);

void robustSpec_v6_ComputeRho_Phi_ctx_reset(robustSpec_v6_ComputeRho_Phi_ctx_type* ctx);
robustSpec_v6_ComputeRho_Phi_ctx_type* robustSpec_v6_ComputeRho_Phi_ctx_new_ctx();
void robustSpec_v6_ComputeRho_Phi_step(_real [2],_real [3]/*out*/,robustSpec_v6_ComputeRho_Phi_ctx_type*);

void robustSpec_v6_Implies_step(_real ,_real ,_real *);

void robustSpec_v6_Main_ctx_reset(robustSpec_v6_Main_ctx_type* ctx);
robustSpec_v6_Main_ctx_type* robustSpec_v6_Main_ctx_new_ctx();
void robustSpec_v6_Main_step(robustSpec_v6_SamplePoint ,_real [3]/*out*/,robustSpec_v6_Main_ctx_type*);

void robustSpec_v6_Max_2_step(_real ,_real ,_real *);

void robustSpec_v6_Min_2_step(_real ,_real ,_real *);

void robustSpec_v6_Not_step(_real ,_real *);

void robustSpec_v6_Or_step(_real ,_real ,_real *);

void robustSpec_v6_Previous_ctx_reset(robustSpec_v6_Previous_ctx_type* ctx);
robustSpec_v6_Previous_ctx_type* robustSpec_v6_Previous_ctx_new_ctx();
void robustSpec_v6_Previous_step(_real ,_real *,robustSpec_v6_Previous_ctx_type*);

void robustSpec_v6_f_AP_0_ctx_reset(robustSpec_v6_f_AP_0_ctx_type* ctx);
robustSpec_v6_f_AP_0_ctx_type* robustSpec_v6_f_AP_0_ctx_new_ctx();
void robustSpec_v6_f_AP_0_step(robustSpec_v6_SamplePoint ,_real *,robustSpec_v6_f_AP_0_ctx_type*);

void robustSpec_v6_f_AP_1_step(robustSpec_v6_SamplePoint ,_real *);

/////////////////////////////////////////////////
#endif
