/* This file was generated by lv6 version master.737 (2727a7744111c84f7984634d2bd3ad6f7c6c7ff9). */
/*  lv6 -2c -cc -n Main robustSpec_v6.lus */
/* on s27 the 03/04/2020 at 08:27:05 */
#include "robustSpec_v6_Main.h"
//// Defining step functions
// Step function(s) for Delay_0_ctx
void Delay_0_step(_real x,_real *z){

  *z = x;

} // End of Delay_0_step

// Memory initialisation for Delay_1_ctx
void Delay_1_ctx_reset(Delay_1_ctx_type* ctx){
  int _i;

    Lustre_pre_ctx_reset(&ctx->Lustre_pre_ctx_tab[0]);
    Lustre_arrow_ctx_reset(&ctx->Lustre_arrow_ctx_tab[0]);
}
// Memory allocation for Delay_1_ctx
Delay_1_ctx_type* Delay_1_ctx_new_ctx(){

   Delay_1_ctx_type* ctx = (Delay_1_ctx_type*)calloc(1, sizeof(Delay_1_ctx_type));
   // ctx->client_data = cdata;
   Delay_1_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Delay_1_ctx
void Delay_1_step(_real x,_real *z,Delay_1_ctx_type* ctx){   _real _split_4;
   _real _split_3;

  Lustre_pre_get(&_split_4,&ctx->Lustre_pre_ctx_tab[0]); 
  Delay_0_step(x,&_split_3); 
  Lustre_pre_set(_split_3,&ctx->Lustre_pre_ctx_tab[0]); 
  Lustre_arrow_step(x,_split_4,z,&ctx->Lustre_arrow_ctx_tab[0]); 

} // End of Delay_1_step

// Memory initialisation for Delay_2_ctx
void Delay_2_ctx_reset(Delay_2_ctx_type* ctx){
  int _i;

    Lustre_pre_ctx_reset(&ctx->Lustre_pre_ctx_tab[0]);
    Lustre_arrow_ctx_reset(&ctx->Lustre_arrow_ctx_tab[0]);
    Delay_1_ctx_reset(&ctx->Delay_1_ctx_tab[0]);
}
// Memory allocation for Delay_2_ctx
Delay_2_ctx_type* Delay_2_ctx_new_ctx(){

   Delay_2_ctx_type* ctx = (Delay_2_ctx_type*)calloc(1, sizeof(Delay_2_ctx_type));
   // ctx->client_data = cdata;
   Delay_2_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Delay_2_ctx
void Delay_2_step(_real x,_real *z,Delay_2_ctx_type* ctx){   _real _split_6;
   _real _split_5;

  Lustre_pre_get(&_split_6,&ctx->Lustre_pre_ctx_tab[0]); 
  Delay_1_step(x,&_split_5,&ctx->Delay_1_ctx_tab[0]); 
  Lustre_pre_set(_split_5,&ctx->Lustre_pre_ctx_tab[0]); 
  Lustre_arrow_step(x,_split_6,z,&ctx->Lustre_arrow_ctx_tab[0]); 

} // End of Delay_2_step

// Memory initialisation for Delay_3_ctx
void Delay_3_ctx_reset(Delay_3_ctx_type* ctx){
  int _i;

    Lustre_pre_ctx_reset(&ctx->Lustre_pre_ctx_tab[0]);
    Lustre_arrow_ctx_reset(&ctx->Lustre_arrow_ctx_tab[0]);
    Delay_2_ctx_reset(&ctx->Delay_2_ctx_tab[0]);
}
// Memory allocation for Delay_3_ctx
Delay_3_ctx_type* Delay_3_ctx_new_ctx(){

   Delay_3_ctx_type* ctx = (Delay_3_ctx_type*)calloc(1, sizeof(Delay_3_ctx_type));
   // ctx->client_data = cdata;
   Delay_3_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Delay_3_ctx
void Delay_3_step(_real x,_real *z,Delay_3_ctx_type* ctx){   _real _split_8;
   _real _split_7;

  Lustre_pre_get(&_split_8,&ctx->Lustre_pre_ctx_tab[0]); 
  Delay_2_step(x,&_split_7,&ctx->Delay_2_ctx_tab[0]); 
  Lustre_pre_set(_split_7,&ctx->Lustre_pre_ctx_tab[0]); 
  Lustre_arrow_step(x,_split_8,z,&ctx->Lustre_arrow_ctx_tab[0]); 

} // End of Delay_3_step

// Memory initialisation for Delay_4_ctx
void Delay_4_ctx_reset(Delay_4_ctx_type* ctx){
  int _i;

    Lustre_pre_ctx_reset(&ctx->Lustre_pre_ctx_tab[0]);
    Lustre_arrow_ctx_reset(&ctx->Lustre_arrow_ctx_tab[0]);
    Delay_3_ctx_reset(&ctx->Delay_3_ctx_tab[0]);
}
// Memory allocation for Delay_4_ctx
Delay_4_ctx_type* Delay_4_ctx_new_ctx(){

   Delay_4_ctx_type* ctx = (Delay_4_ctx_type*)calloc(1, sizeof(Delay_4_ctx_type));
   // ctx->client_data = cdata;
   Delay_4_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Delay_4_ctx
void Delay_4_step(_real x,_real *z,Delay_4_ctx_type* ctx){   _real _split_10;
   _real _split_9;

  Lustre_pre_get(&_split_10,&ctx->Lustre_pre_ctx_tab[0]); 
  Delay_3_step(x,&_split_9,&ctx->Delay_3_ctx_tab[0]); 
  Lustre_pre_set(_split_9,&ctx->Lustre_pre_ctx_tab[0]); 
  Lustre_arrow_step(x,_split_10,z,&ctx->Lustre_arrow_ctx_tab[0]); 

} // End of Delay_4_step

// Memory initialisation for Delay_5_ctx
void Delay_5_ctx_reset(Delay_5_ctx_type* ctx){
  int _i;

    Lustre_pre_ctx_reset(&ctx->Lustre_pre_ctx_tab[0]);
    Lustre_arrow_ctx_reset(&ctx->Lustre_arrow_ctx_tab[0]);
    Delay_4_ctx_reset(&ctx->Delay_4_ctx_tab[0]);
}
// Memory allocation for Delay_5_ctx
Delay_5_ctx_type* Delay_5_ctx_new_ctx(){

   Delay_5_ctx_type* ctx = (Delay_5_ctx_type*)calloc(1, sizeof(Delay_5_ctx_type));
   // ctx->client_data = cdata;
   Delay_5_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Delay_5_ctx
void Delay_5_step(_real x,_real *z,Delay_5_ctx_type* ctx){   _real _split_12;
   _real _split_11;

  Lustre_pre_get(&_split_12,&ctx->Lustre_pre_ctx_tab[0]); 
  Delay_4_step(x,&_split_11,&ctx->Delay_4_ctx_tab[0]); 
  Lustre_pre_set(_split_11,&ctx->Lustre_pre_ctx_tab[0]); 
  Lustre_arrow_step(x,_split_12,z,&ctx->Lustre_arrow_ctx_tab[0]); 

} // End of Delay_5_step

// Step function(s) for Delay_m1_ctx
void Delay_m1_step(_real x,_real *z){

  *z = x;

} // End of Delay_m1_step

// Memory initialisation for Lustre_arrow_ctx
void Lustre_arrow_ctx_reset(Lustre_arrow_ctx_type* ctx){
  int _i;
  ctx->_memory = _true;
}
// Memory allocation for Lustre_arrow_ctx
Lustre_arrow_ctx_type* Lustre_arrow_ctx_new_ctx(){

   Lustre_arrow_ctx_type* ctx = (Lustre_arrow_ctx_type*)calloc(1, sizeof(Lustre_arrow_ctx_type));
   // ctx->client_data = cdata;
   Lustre_arrow_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Lustre_arrow_ctx
void Lustre_arrow_step(_real i1,_real i2,_real *out,Lustre_arrow_ctx_type* ctx){  *out = ((ctx->_memory)? i1 : i2);
  ctx->_memory = _false;

} // End of Lustre_arrow_step

// Memory initialisation for Lustre_pre_ctx
void Lustre_pre_ctx_reset(Lustre_pre_ctx_type* ctx){
  int _i;

}
// Memory allocation for Lustre_pre_ctx
Lustre_pre_ctx_type* Lustre_pre_ctx_new_ctx(){

   Lustre_pre_ctx_type* ctx = (Lustre_pre_ctx_type*)calloc(1, sizeof(Lustre_pre_ctx_type));
   // ctx->client_data = cdata;
   Lustre_pre_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Lustre_pre_ctx
void Lustre_pre_get(_real *out,Lustre_pre_ctx_type* ctx){
  *out = ctx->_memory;

} // End of Lustre_pre_get

void Lustre_pre_set(_real i1,Lustre_pre_ctx_type* ctx){
  ctx->_memory = i1;

} // End of Lustre_pre_set

// Step function(s) for Lustre_slash_ctx
void Lustre_slash_step(_real i1,_real i2,_real *out){
  *out = (i1 / i2);

} // End of Lustre_slash_step

// Memory initialisation for Once_Interval_0_5_ctx
void Once_Interval_0_5_ctx_reset(Once_Interval_0_5_ctx_type* ctx){
  int _i;

    Since_Interval_0_5_ctx_reset(&ctx->Since_Interval_0_5_ctx_tab[0]);
}
// Memory allocation for Once_Interval_0_5_ctx
Once_Interval_0_5_ctx_type* Once_Interval_0_5_ctx_new_ctx(){

   Once_Interval_0_5_ctx_type* ctx = (Once_Interval_0_5_ctx_type*)calloc(1, sizeof(Once_Interval_0_5_ctx_type));
   // ctx->client_data = cdata;
   Once_Interval_0_5_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Once_Interval_0_5_ctx
void Once_Interval_0_5_step(_real x,_real *z,Once_Interval_0_5_ctx_type* ctx){
  Since_Interval_0_5_step(x,9999.0,z,&ctx->Since_Interval_0_5_ctx_tab[0]); 

} // End of Once_Interval_0_5_step

// Memory initialisation for Since_Interval_0_5_ctx
void Since_Interval_0_5_ctx_reset(Since_Interval_0_5_ctx_type* ctx){
  int _i;

    Since_Recurse_0_5_0_ctx_reset(&ctx->Since_Recurse_0_5_0_ctx_tab[0]);
}
// Memory allocation for Since_Interval_0_5_ctx
Since_Interval_0_5_ctx_type* Since_Interval_0_5_ctx_new_ctx(){

   Since_Interval_0_5_ctx_type* ctx = (Since_Interval_0_5_ctx_type*)calloc(1, sizeof(Since_Interval_0_5_ctx_type));
   // ctx->client_data = cdata;
   Since_Interval_0_5_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Since_Interval_0_5_ctx
void Since_Interval_0_5_step(_real x,_real y,_real *z,Since_Interval_0_5_ctx_type* ctx){   _boolean _split_15;
   _boolean _split_16;

  _split_16 = 5 > 0;
  _split_15 = 0 >= 0;
  Since_Recurse_0_5_0_step(x,y,z,&ctx->Since_Recurse_0_5_0_ctx_tab[0]); 

} // End of Since_Interval_0_5_step

// Memory initialisation for Since_Interval_1_1_ctx
void Since_Interval_1_1_ctx_reset(Since_Interval_1_1_ctx_type* ctx){
  int _i;

    Since_Recurse_1_1_0_ctx_reset(&ctx->Since_Recurse_1_1_0_ctx_tab[0]);
}
// Memory allocation for Since_Interval_1_1_ctx
Since_Interval_1_1_ctx_type* Since_Interval_1_1_ctx_new_ctx(){

   Since_Interval_1_1_ctx_type* ctx = (Since_Interval_1_1_ctx_type*)calloc(1, sizeof(Since_Interval_1_1_ctx_type));
   // ctx->client_data = cdata;
   Since_Interval_1_1_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Since_Interval_1_1_ctx
void Since_Interval_1_1_step(_real x,_real y,_real *z,Since_Interval_1_1_ctx_type* ctx){   _boolean _split_17;
   _boolean _split_18;

  _split_18 = 1 > 0;
  _split_17 = 1 >= 0;
  Since_Recurse_1_1_0_step(x,y,z,&ctx->Since_Recurse_1_1_0_ctx_tab[0]); 

} // End of Since_Interval_1_1_step

// Memory initialisation for Since_Recurse_0_5_0_ctx
void Since_Recurse_0_5_0_ctx_reset(Since_Recurse_0_5_0_ctx_type* ctx){
  int _i;

    Since_Recurse_0_5_1_ctx_reset(&ctx->Since_Recurse_0_5_1_ctx_tab[0]);
}
// Memory allocation for Since_Recurse_0_5_0_ctx
Since_Recurse_0_5_0_ctx_type* Since_Recurse_0_5_0_ctx_new_ctx(){

   Since_Recurse_0_5_0_ctx_type* ctx = (Since_Recurse_0_5_0_ctx_type*)calloc(1, sizeof(Since_Recurse_0_5_0_ctx_type));
   // ctx->client_data = cdata;
   Since_Recurse_0_5_0_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Since_Recurse_0_5_0_ctx
void Since_Recurse_0_5_0_step(_real x,_real y,_real *z,Since_Recurse_0_5_0_ctx_type* ctx){   _real _split_19;
   _real x_n;
   _real min_m;
   _real min_n;
   _integer _split_20;
   _boolean _split_21;

  _split_20 = 5 - 0;
  _split_21 = _split_20 >= 0;
  Delay_0_step(x,&x_n); 
  Sliding_Min_m1_step(y,&min_m); 
  robustSpec_v6_Min_2_step(x_n,min_m,&min_n); 
  Since_Recurse_0_5_1_step(x,y,&_split_19,&ctx->Since_Recurse_0_5_1_ctx_tab[0]); 
  robustSpec_v6_Max_2_step(min_n,_split_19,z); 

} // End of Since_Recurse_0_5_0_step

// Memory initialisation for Since_Recurse_0_5_1_ctx
void Since_Recurse_0_5_1_ctx_reset(Since_Recurse_0_5_1_ctx_type* ctx){
  int _i;

    Since_Recurse_0_5_2_ctx_reset(&ctx->Since_Recurse_0_5_2_ctx_tab[0]);
    Delay_1_ctx_reset(&ctx->Delay_1_ctx_tab[0]);
}
// Memory allocation for Since_Recurse_0_5_1_ctx
Since_Recurse_0_5_1_ctx_type* Since_Recurse_0_5_1_ctx_new_ctx(){

   Since_Recurse_0_5_1_ctx_type* ctx = (Since_Recurse_0_5_1_ctx_type*)calloc(1, sizeof(Since_Recurse_0_5_1_ctx_type));
   // ctx->client_data = cdata;
   Since_Recurse_0_5_1_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Since_Recurse_0_5_1_ctx
void Since_Recurse_0_5_1_step(_real x,_real y,_real *z,Since_Recurse_0_5_1_ctx_type* ctx){   _real _split_22;
   _real x_n;
   _real min_m;
   _real min_n;
   _integer _split_23;
   _boolean _split_24;

  _split_23 = 5 - 0;
  _split_24 = _split_23 >= 0;
  Delay_1_step(x,&x_n,&ctx->Delay_1_ctx_tab[0]); 
  Sliding_Min_0_step(y,&min_m); 
  robustSpec_v6_Min_2_step(x_n,min_m,&min_n); 
  Since_Recurse_0_5_2_step(x,y,&_split_22,&ctx->Since_Recurse_0_5_2_ctx_tab[0]); 
  robustSpec_v6_Max_2_step(min_n,_split_22,z); 

} // End of Since_Recurse_0_5_1_step

// Memory initialisation for Since_Recurse_0_5_2_ctx
void Since_Recurse_0_5_2_ctx_reset(Since_Recurse_0_5_2_ctx_type* ctx){
  int _i;

    Sliding_Min_1_ctx_reset(&ctx->Sliding_Min_1_ctx_tab[0]);
    Since_Recurse_0_5_3_ctx_reset(&ctx->Since_Recurse_0_5_3_ctx_tab[0]);
    Delay_2_ctx_reset(&ctx->Delay_2_ctx_tab[0]);
}
// Memory allocation for Since_Recurse_0_5_2_ctx
Since_Recurse_0_5_2_ctx_type* Since_Recurse_0_5_2_ctx_new_ctx(){

   Since_Recurse_0_5_2_ctx_type* ctx = (Since_Recurse_0_5_2_ctx_type*)calloc(1, sizeof(Since_Recurse_0_5_2_ctx_type));
   // ctx->client_data = cdata;
   Since_Recurse_0_5_2_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Since_Recurse_0_5_2_ctx
void Since_Recurse_0_5_2_step(_real x,_real y,_real *z,Since_Recurse_0_5_2_ctx_type* ctx){   _real _split_25;
   _real x_n;
   _real min_m;
   _real min_n;
   _integer _split_26;
   _boolean _split_27;

  _split_26 = 5 - 0;
  _split_27 = _split_26 >= 0;
  Delay_2_step(x,&x_n,&ctx->Delay_2_ctx_tab[0]); 
  Sliding_Min_1_step(y,&min_m,&ctx->Sliding_Min_1_ctx_tab[0]); 
  robustSpec_v6_Min_2_step(x_n,min_m,&min_n); 
  Since_Recurse_0_5_3_step(x,y,&_split_25,&ctx->Since_Recurse_0_5_3_ctx_tab[0]); 
  robustSpec_v6_Max_2_step(min_n,_split_25,z); 

} // End of Since_Recurse_0_5_2_step

// Memory initialisation for Since_Recurse_0_5_3_ctx
void Since_Recurse_0_5_3_ctx_reset(Since_Recurse_0_5_3_ctx_type* ctx){
  int _i;

    Sliding_Min_2_ctx_reset(&ctx->Sliding_Min_2_ctx_tab[0]);
    Since_Recurse_0_5_4_ctx_reset(&ctx->Since_Recurse_0_5_4_ctx_tab[0]);
    Delay_3_ctx_reset(&ctx->Delay_3_ctx_tab[0]);
}
// Memory allocation for Since_Recurse_0_5_3_ctx
Since_Recurse_0_5_3_ctx_type* Since_Recurse_0_5_3_ctx_new_ctx(){

   Since_Recurse_0_5_3_ctx_type* ctx = (Since_Recurse_0_5_3_ctx_type*)calloc(1, sizeof(Since_Recurse_0_5_3_ctx_type));
   // ctx->client_data = cdata;
   Since_Recurse_0_5_3_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Since_Recurse_0_5_3_ctx
void Since_Recurse_0_5_3_step(_real x,_real y,_real *z,Since_Recurse_0_5_3_ctx_type* ctx){   _real _split_28;
   _real x_n;
   _real min_m;
   _real min_n;
   _integer _split_29;
   _boolean _split_30;

  _split_29 = 5 - 0;
  _split_30 = _split_29 >= 0;
  Delay_3_step(x,&x_n,&ctx->Delay_3_ctx_tab[0]); 
  Sliding_Min_2_step(y,&min_m,&ctx->Sliding_Min_2_ctx_tab[0]); 
  robustSpec_v6_Min_2_step(x_n,min_m,&min_n); 
  Since_Recurse_0_5_4_step(x,y,&_split_28,&ctx->Since_Recurse_0_5_4_ctx_tab[0]); 
  robustSpec_v6_Max_2_step(min_n,_split_28,z); 

} // End of Since_Recurse_0_5_3_step

// Memory initialisation for Since_Recurse_0_5_4_ctx
void Since_Recurse_0_5_4_ctx_reset(Since_Recurse_0_5_4_ctx_type* ctx){
  int _i;

    Sliding_Min_3_ctx_reset(&ctx->Sliding_Min_3_ctx_tab[0]);
    Since_Recurse_0_5_5_ctx_reset(&ctx->Since_Recurse_0_5_5_ctx_tab[0]);
    Delay_4_ctx_reset(&ctx->Delay_4_ctx_tab[0]);
}
// Memory allocation for Since_Recurse_0_5_4_ctx
Since_Recurse_0_5_4_ctx_type* Since_Recurse_0_5_4_ctx_new_ctx(){

   Since_Recurse_0_5_4_ctx_type* ctx = (Since_Recurse_0_5_4_ctx_type*)calloc(1, sizeof(Since_Recurse_0_5_4_ctx_type));
   // ctx->client_data = cdata;
   Since_Recurse_0_5_4_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Since_Recurse_0_5_4_ctx
void Since_Recurse_0_5_4_step(_real x,_real y,_real *z,Since_Recurse_0_5_4_ctx_type* ctx){   _real _split_31;
   _real x_n;
   _real min_m;
   _real min_n;
   _integer _split_32;
   _boolean _split_33;

  _split_32 = 5 - 0;
  _split_33 = _split_32 >= 0;
  Delay_4_step(x,&x_n,&ctx->Delay_4_ctx_tab[0]); 
  Sliding_Min_3_step(y,&min_m,&ctx->Sliding_Min_3_ctx_tab[0]); 
  robustSpec_v6_Min_2_step(x_n,min_m,&min_n); 
  Since_Recurse_0_5_5_step(x,y,&_split_31,&ctx->Since_Recurse_0_5_5_ctx_tab[0]); 
  robustSpec_v6_Max_2_step(min_n,_split_31,z); 

} // End of Since_Recurse_0_5_4_step

// Memory initialisation for Since_Recurse_0_5_5_ctx
void Since_Recurse_0_5_5_ctx_reset(Since_Recurse_0_5_5_ctx_type* ctx){
  int _i;

    Sliding_Min_4_ctx_reset(&ctx->Sliding_Min_4_ctx_tab[0]);
    Delay_5_ctx_reset(&ctx->Delay_5_ctx_tab[0]);
}
// Memory allocation for Since_Recurse_0_5_5_ctx
Since_Recurse_0_5_5_ctx_type* Since_Recurse_0_5_5_ctx_new_ctx(){

   Since_Recurse_0_5_5_ctx_type* ctx = (Since_Recurse_0_5_5_ctx_type*)calloc(1, sizeof(Since_Recurse_0_5_5_ctx_type));
   // ctx->client_data = cdata;
   Since_Recurse_0_5_5_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Since_Recurse_0_5_5_ctx
void Since_Recurse_0_5_5_step(_real x,_real y,_real *z,Since_Recurse_0_5_5_ctx_type* ctx){   _real x_n;
   _real min_m;
   _real min_n;
   _integer _split_34;
   _boolean _split_35;

  _split_34 = 5 - 0;
  _split_35 = _split_34 >= 0;
  Delay_5_step(x,&x_n,&ctx->Delay_5_ctx_tab[0]); 
  Sliding_Min_4_step(y,&min_m,&ctx->Sliding_Min_4_ctx_tab[0]); 
  robustSpec_v6_Min_2_step(x_n,min_m,&min_n); 
  *z = min_n;

} // End of Since_Recurse_0_5_5_step

// Memory initialisation for Since_Recurse_1_1_0_ctx
void Since_Recurse_1_1_0_ctx_reset(Since_Recurse_1_1_0_ctx_type* ctx){
  int _i;

    Delay_1_ctx_reset(&ctx->Delay_1_ctx_tab[0]);
}
// Memory allocation for Since_Recurse_1_1_0_ctx
Since_Recurse_1_1_0_ctx_type* Since_Recurse_1_1_0_ctx_new_ctx(){

   Since_Recurse_1_1_0_ctx_type* ctx = (Since_Recurse_1_1_0_ctx_type*)calloc(1, sizeof(Since_Recurse_1_1_0_ctx_type));
   // ctx->client_data = cdata;
   Since_Recurse_1_1_0_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Since_Recurse_1_1_0_ctx
void Since_Recurse_1_1_0_step(_real x,_real y,_real *z,Since_Recurse_1_1_0_ctx_type* ctx){   _real x_n;
   _real min_m;
   _real min_n;
   _integer _split_36;
   _boolean _split_37;

  _split_36 = 1 - 1;
  _split_37 = _split_36 >= 0;
  Delay_1_step(x,&x_n,&ctx->Delay_1_ctx_tab[0]); 
  Sliding_Min_0_step(y,&min_m); 
  robustSpec_v6_Min_2_step(x_n,min_m,&min_n); 
  *z = min_n;

} // End of Since_Recurse_1_1_0_step

// Step function(s) for Sliding_Min_0_ctx
void Sliding_Min_0_step(_real x,_real *z){
   _real x_n;

  Delay_0_step(x,&x_n); 
  *z = x_n;

} // End of Sliding_Min_0_step

// Memory initialisation for Sliding_Min_1_ctx
void Sliding_Min_1_ctx_reset(Sliding_Min_1_ctx_type* ctx){
  int _i;

    Delay_1_ctx_reset(&ctx->Delay_1_ctx_tab[0]);
}
// Memory allocation for Sliding_Min_1_ctx
Sliding_Min_1_ctx_type* Sliding_Min_1_ctx_new_ctx(){

   Sliding_Min_1_ctx_type* ctx = (Sliding_Min_1_ctx_type*)calloc(1, sizeof(Sliding_Min_1_ctx_type));
   // ctx->client_data = cdata;
   Sliding_Min_1_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Sliding_Min_1_ctx
void Sliding_Min_1_step(_real x,_real *z,Sliding_Min_1_ctx_type* ctx){   _real _split_38;
   _real x_n;

  Delay_1_step(x,&x_n,&ctx->Delay_1_ctx_tab[0]); 
  Sliding_Min_0_step(x,&_split_38); 
  robustSpec_v6_Min_2_step(x_n,_split_38,z); 

} // End of Sliding_Min_1_step

// Memory initialisation for Sliding_Min_2_ctx
void Sliding_Min_2_ctx_reset(Sliding_Min_2_ctx_type* ctx){
  int _i;

    Sliding_Min_1_ctx_reset(&ctx->Sliding_Min_1_ctx_tab[0]);
    Delay_2_ctx_reset(&ctx->Delay_2_ctx_tab[0]);
}
// Memory allocation for Sliding_Min_2_ctx
Sliding_Min_2_ctx_type* Sliding_Min_2_ctx_new_ctx(){

   Sliding_Min_2_ctx_type* ctx = (Sliding_Min_2_ctx_type*)calloc(1, sizeof(Sliding_Min_2_ctx_type));
   // ctx->client_data = cdata;
   Sliding_Min_2_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Sliding_Min_2_ctx
void Sliding_Min_2_step(_real x,_real *z,Sliding_Min_2_ctx_type* ctx){   _real _split_39;
   _real x_n;

  Delay_2_step(x,&x_n,&ctx->Delay_2_ctx_tab[0]); 
  Sliding_Min_1_step(x,&_split_39,&ctx->Sliding_Min_1_ctx_tab[0]); 
  robustSpec_v6_Min_2_step(x_n,_split_39,z); 

} // End of Sliding_Min_2_step

// Memory initialisation for Sliding_Min_3_ctx
void Sliding_Min_3_ctx_reset(Sliding_Min_3_ctx_type* ctx){
  int _i;

    Sliding_Min_2_ctx_reset(&ctx->Sliding_Min_2_ctx_tab[0]);
    Delay_3_ctx_reset(&ctx->Delay_3_ctx_tab[0]);
}
// Memory allocation for Sliding_Min_3_ctx
Sliding_Min_3_ctx_type* Sliding_Min_3_ctx_new_ctx(){

   Sliding_Min_3_ctx_type* ctx = (Sliding_Min_3_ctx_type*)calloc(1, sizeof(Sliding_Min_3_ctx_type));
   // ctx->client_data = cdata;
   Sliding_Min_3_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Sliding_Min_3_ctx
void Sliding_Min_3_step(_real x,_real *z,Sliding_Min_3_ctx_type* ctx){   _real _split_40;
   _real x_n;

  Delay_3_step(x,&x_n,&ctx->Delay_3_ctx_tab[0]); 
  Sliding_Min_2_step(x,&_split_40,&ctx->Sliding_Min_2_ctx_tab[0]); 
  robustSpec_v6_Min_2_step(x_n,_split_40,z); 

} // End of Sliding_Min_3_step

// Memory initialisation for Sliding_Min_4_ctx
void Sliding_Min_4_ctx_reset(Sliding_Min_4_ctx_type* ctx){
  int _i;

    Sliding_Min_3_ctx_reset(&ctx->Sliding_Min_3_ctx_tab[0]);
    Delay_4_ctx_reset(&ctx->Delay_4_ctx_tab[0]);
}
// Memory allocation for Sliding_Min_4_ctx
Sliding_Min_4_ctx_type* Sliding_Min_4_ctx_new_ctx(){

   Sliding_Min_4_ctx_type* ctx = (Sliding_Min_4_ctx_type*)calloc(1, sizeof(Sliding_Min_4_ctx_type));
   // ctx->client_data = cdata;
   Sliding_Min_4_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for Sliding_Min_4_ctx
void Sliding_Min_4_step(_real x,_real *z,Sliding_Min_4_ctx_type* ctx){   _real _split_41;
   _real x_n;

  Delay_4_step(x,&x_n,&ctx->Delay_4_ctx_tab[0]); 
  Sliding_Min_3_step(x,&_split_41,&ctx->Sliding_Min_3_ctx_tab[0]); 
  robustSpec_v6_Min_2_step(x_n,_split_41,z); 

} // End of Sliding_Min_4_step

// Step function(s) for Sliding_Min_m1_ctx
void Sliding_Min_m1_step(_real x,_real *z){
   _real x_n;

  Delay_m1_step(x,&x_n); 
  *z = x_n;

} // End of Sliding_Min_m1_step

// Step function(s) for robustSpec_v6_Abs_ctx
void robustSpec_v6_Abs_step(_real x,_real *abs_x){
   _real _split_2;
   _boolean _split_1;

  _split_2 = - x;
  _split_1 = x > 0.0;
   if (_split_1 == _true) {
     *abs_x = x;
   } else {
     *abs_x = _split_2;
   }

} // End of robustSpec_v6_Abs_step

// Memory initialisation for robustSpec_v6_ComputeRho_AP_ctx
void robustSpec_v6_ComputeRho_AP_ctx_reset(robustSpec_v6_ComputeRho_AP_ctx_type* ctx){
  int _i;

    robustSpec_v6_f_AP_0_ctx_reset(&ctx->robustSpec_v6_f_AP_0_ctx_tab[0]);
}
// Memory allocation for robustSpec_v6_ComputeRho_AP_ctx
robustSpec_v6_ComputeRho_AP_ctx_type* robustSpec_v6_ComputeRho_AP_ctx_new_ctx(){

   robustSpec_v6_ComputeRho_AP_ctx_type* ctx = (robustSpec_v6_ComputeRho_AP_ctx_type*)calloc(1, sizeof(robustSpec_v6_ComputeRho_AP_ctx_type));
   // ctx->client_data = cdata;
   robustSpec_v6_ComputeRho_AP_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for robustSpec_v6_ComputeRho_AP_ctx
void robustSpec_v6_ComputeRho_AP_step(robustSpec_v6_SamplePoint SP,_real Rho_AP[2]/*out*/,robustSpec_v6_ComputeRho_AP_ctx_type* ctx){
  robustSpec_v6_f_AP_0_step(SP,&Rho_AP[0],&ctx->robustSpec_v6_f_AP_0_ctx_tab[0]); 
  robustSpec_v6_f_AP_1_step(SP,&Rho_AP[1]); 

} // End of robustSpec_v6_ComputeRho_AP_step

// Memory initialisation for robustSpec_v6_ComputeRho_Phi_ctx
void robustSpec_v6_ComputeRho_Phi_ctx_reset(robustSpec_v6_ComputeRho_Phi_ctx_type* ctx){
  int _i;

    Once_Interval_0_5_ctx_reset(&ctx->Once_Interval_0_5_ctx_tab[0]);
}
// Memory allocation for robustSpec_v6_ComputeRho_Phi_ctx
robustSpec_v6_ComputeRho_Phi_ctx_type* robustSpec_v6_ComputeRho_Phi_ctx_new_ctx(){

   robustSpec_v6_ComputeRho_Phi_ctx_type* ctx = (robustSpec_v6_ComputeRho_Phi_ctx_type*)calloc(1, sizeof(robustSpec_v6_ComputeRho_Phi_ctx_type));
   // ctx->client_data = cdata;
   robustSpec_v6_ComputeRho_Phi_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for robustSpec_v6_ComputeRho_Phi_ctx
void robustSpec_v6_ComputeRho_Phi_step(_real Rho_AP[2],_real Rho[3]/*out*/,robustSpec_v6_ComputeRho_Phi_ctx_type* ctx){
  Rho[0] = Rho_AP[0];
  Rho[1] = Rho_AP[1];
  Once_Interval_0_5_step(Rho[1],&Rho[2],&ctx->Once_Interval_0_5_ctx_tab[0]); 

} // End of robustSpec_v6_ComputeRho_Phi_step

// Memory initialisation for robustSpec_v6_Main_ctx
void robustSpec_v6_Main_ctx_reset(robustSpec_v6_Main_ctx_type* ctx){
  int _i;

    robustSpec_v6_ComputeRho_Phi_ctx_reset(&ctx->robustSpec_v6_ComputeRho_Phi_ctx_tab[0]);
    robustSpec_v6_ComputeRho_AP_ctx_reset(&ctx->robustSpec_v6_ComputeRho_AP_ctx_tab[0]);
}
// Memory allocation for robustSpec_v6_Main_ctx
robustSpec_v6_Main_ctx_type* robustSpec_v6_Main_ctx_new_ctx(){

   robustSpec_v6_Main_ctx_type* ctx = (robustSpec_v6_Main_ctx_type*)calloc(1, sizeof(robustSpec_v6_Main_ctx_type));
   // ctx->client_data = cdata;
   robustSpec_v6_Main_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for robustSpec_v6_Main_ctx
void robustSpec_v6_Main_step(robustSpec_v6_SamplePoint SP,_real Rho[3]/*out*/,robustSpec_v6_Main_ctx_type* ctx){   _real Rho_AP[2];

  robustSpec_v6_ComputeRho_AP_step(SP,Rho_AP,&ctx->robustSpec_v6_ComputeRho_AP_ctx_tab[0]); 
  robustSpec_v6_ComputeRho_Phi_step(Rho_AP,Rho,&ctx->robustSpec_v6_ComputeRho_Phi_ctx_tab[0]); 

} // End of robustSpec_v6_Main_step

// Step function(s) for robustSpec_v6_Max_2_ctx
void robustSpec_v6_Max_2_step(_real x,_real y,_real *max){
   _boolean _split_13;

  _split_13 = x > y;
   if (_split_13 == _true) {
     *max = x;
   } else {
     *max = y;
   }

} // End of robustSpec_v6_Max_2_step

// Step function(s) for robustSpec_v6_Min_2_ctx
void robustSpec_v6_Min_2_step(_real x,_real y,_real *min){
   _boolean _split_14;

  _split_14 = x > y;
   if (_split_14 == _true) {
     *min = y;
   } else {
     *min = x;
   }

} // End of robustSpec_v6_Min_2_step

// Memory initialisation for robustSpec_v6_Previous_ctx
void robustSpec_v6_Previous_ctx_reset(robustSpec_v6_Previous_ctx_type* ctx){
  int _i;

    Since_Interval_1_1_ctx_reset(&ctx->Since_Interval_1_1_ctx_tab[0]);
}
// Memory allocation for robustSpec_v6_Previous_ctx
robustSpec_v6_Previous_ctx_type* robustSpec_v6_Previous_ctx_new_ctx(){

   robustSpec_v6_Previous_ctx_type* ctx = (robustSpec_v6_Previous_ctx_type*)calloc(1, sizeof(robustSpec_v6_Previous_ctx_type));
   // ctx->client_data = cdata;
   robustSpec_v6_Previous_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for robustSpec_v6_Previous_ctx
void robustSpec_v6_Previous_step(_real x,_real *z,robustSpec_v6_Previous_ctx_type* ctx){
  Since_Interval_1_1_step(x,99.0,z,&ctx->Since_Interval_1_1_ctx_tab[0]); 

} // End of robustSpec_v6_Previous_step

// Memory initialisation for robustSpec_v6_f_AP_0_ctx
void robustSpec_v6_f_AP_0_ctx_reset(robustSpec_v6_f_AP_0_ctx_type* ctx){
  int _i;

    robustSpec_v6_Previous_ctx_reset(&ctx->robustSpec_v6_Previous_ctx_tab[0]);
}
// Memory allocation for robustSpec_v6_f_AP_0_ctx
robustSpec_v6_f_AP_0_ctx_type* robustSpec_v6_f_AP_0_ctx_new_ctx(){

   robustSpec_v6_f_AP_0_ctx_type* ctx = (robustSpec_v6_f_AP_0_ctx_type*)calloc(1, sizeof(robustSpec_v6_f_AP_0_ctx_type));
   // ctx->client_data = cdata;
   robustSpec_v6_f_AP_0_ctx_reset(ctx);
  return ctx;
}
// Step function(s) for robustSpec_v6_f_AP_0_ctx
void robustSpec_v6_f_AP_0_step(robustSpec_v6_SamplePoint SP,_real *mu,robustSpec_v6_f_AP_0_ctx_type* ctx){   _real _split_44;
   _real _split_43;
   _real _split_42;

  robustSpec_v6_Previous_step(SP.s[2],&_split_42,&ctx->robustSpec_v6_Previous_ctx_tab[0]); 
  _split_43 = SP.s[2] - _split_42;
  robustSpec_v6_Abs_step(_split_43,&_split_44); 
  *mu = _split_44 - 0.1;

} // End of robustSpec_v6_f_AP_0_step

// Step function(s) for robustSpec_v6_f_AP_1_ctx
void robustSpec_v6_f_AP_1_step(robustSpec_v6_SamplePoint SP,_real *mu){
   _real _split_47;
   _real _split_46;
   _real _split_45;

  _split_45 = SP.s[0] - SP.s[2];
  robustSpec_v6_Abs_step(_split_45,&_split_46); 
  Lustre_slash_step(_split_46,SP.s[2],&_split_47); 
  *mu = 0.1 - _split_47;

} // End of robustSpec_v6_f_AP_1_step

